// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only

// Olivares AI control-plane API, v1 (gRPC).
//
// This is a focused, frozen MIRROR of the REST surface — not full parity. New
// endpoints land in REST first; this proto carries a representative tenant-scoped
// slice (server info, agent CRUD, audit verification) that exercises the same
// authenticate -> resolve-tenant -> authorize path as REST. buf guards it from
// incompatible change; a breaking change requires olivares.api.v2.
//
// Authentication is the "authorization: Bearer <token>" metadata, identical to
// the REST header. The tenant is the request's `tenant` field; a bound token's
// tenant must match it (the same confused-deputy guard as the REST header).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: apiv1/api.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_apiv1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_apiv1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_apiv1_api_proto_rawDescGZIP(), []int{0}
}

type ServerInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Engine          string                 `protobuf:"bytes,2,opt,name=engine,proto3" json:"engine,omitempty"`
	SetupRequired   bool                   `protobuf:"varint,3,opt,name=setup_required,json=setupRequired,proto3" json:"setup_required,omitempty"`
	LicenseStatus   string                 `protobuf:"bytes,4,opt,name=license_status,json=licenseStatus,proto3" json:"license_status,omitempty"`
	LicenseLicensee string                 `protobuf:"bytes,5,opt,name=license_licensee,json=licenseLicensee,proto3" json:"license_licensee,omitempty"`
	// Attested display-only commercial labels (empty for community/none). They gate
	// nothing — informational mirror of the REST server-info license badge (LICENSING.md).
	LicensePlan        string `protobuf:"bytes,6,opt,name=license_plan,json=licensePlan,proto3" json:"license_plan,omitempty"`
	LicenseSupportTier string `protobuf:"bytes,7,opt,name=license_support_tier,json=licenseSupportTier,proto3" json:"license_support_tier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_apiv1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apiv1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_apiv1_api_proto_rawDescGZIP(), []int{1}
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *ServerInfo) GetSetupRequired() bool {
	if x != nil {
		return x.SetupRequired
	}
	return false
}

func (x *ServerInfo) GetLicenseStatus() string {
	if x != nil {
		return x.LicenseStatus
	}
	return ""
}

func (x *ServerInfo) GetLicenseLicensee() string {
	if x != nil {
		return x.LicenseLicensee
	}
	return ""
}

func (x *ServerInfo) GetLicensePlan() string {
	if x != nil {
		return x.LicensePlan
	}
	return ""
}

func (x *ServerInfo) GetLicenseSupportTier() string {
	if x != nil {
		return x.LicenseSupportTier
	}
	return ""
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	ExternalId    string                 `protobuf:"bytes,5,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Version       int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_apiv1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_apiv1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_apiv1_api_proto_rawDescGZIP(), []int{2}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Agent) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Agent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Agent) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Agent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Agent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_apiv1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiv1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_apiv1_api_proto_rawDescGZIP(), []int{3}
}

func (x *ListAgentsRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ListAgentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAgentsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_apiv1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiv1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_apiv1_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListAgentsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_apiv1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiv1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_apiv1_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *GetAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	ExternalId    string                 `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_apiv1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiv1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_apiv1_api_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAgentRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CreateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAgentRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateAgentRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *CreateAgentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type VerifyAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	From          int64                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAuditRequest) Reset() {
	*x = VerifyAuditRequest{}
	mi := &file_apiv1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAuditRequest) ProtoMessage() {}

func (x *VerifyAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiv1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAuditRequest.ProtoReflect.Descriptor instead.
func (*VerifyAuditRequest) Descriptor() ([]byte, []int) {
	return file_apiv1_api_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyAuditRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *VerifyAuditRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

type VerifyAuditResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Ok      bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ChainOk bool                   `protobuf:"varint,2,opt,name=chain_ok,json=chainOk,proto3" json:"chain_ok,omitempty"`
	Checked int64                  `protobuf:"varint,3,opt,name=checked,proto3" json:"checked,omitempty"`
	// checkpoints_ok is a BOOLEAN and a young chain has no checkpoints yet, so `false` has
	// meant two opposite things since this message was written: "a checkpoint exists and did
	// NOT verify" (tamper, act now) and "nothing has been attested yet" (normal, wait). REST
	// has carried the distinction as `checkpoints.status` — ok | failed | pending — from the
	// start; this surface could not express it, so a gRPC client saw ok=true beside
	// checkpoints_ok=false and had no way to tell an untouched new ledger from a broken one.
	CheckpointsOk     bool  `protobuf:"varint,4,opt,name=checkpoints_ok,json=checkpointsOk,proto3" json:"checkpoints_ok,omitempty"`
	CheckpointCount   int32 `protobuf:"varint,5,opt,name=checkpoint_count,json=checkpointCount,proto3" json:"checkpoint_count,omitempty"`
	LatestAttestedSeq int64 `protobuf:"varint,6,opt,name=latest_attested_seq,json=latestAttestedSeq,proto3" json:"latest_attested_seq,omitempty"`
	// checkpoint_status is that third answer, added 2026-08-06. Field 7 is additive, so an
	// older client keeps reading 1-6 unchanged; `checkpoints_ok` stays exactly what it always
	// was rather than being redefined under existing readers.
	CheckpointStatus string `protobuf:"bytes,7,opt,name=checkpoint_status,json=checkpointStatus,proto3" json:"checkpoint_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyAuditResponse) Reset() {
	*x = VerifyAuditResponse{}
	mi := &file_apiv1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAuditResponse) ProtoMessage() {}

func (x *VerifyAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiv1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAuditResponse.ProtoReflect.Descriptor instead.
func (*VerifyAuditResponse) Descriptor() ([]byte, []int) {
	return file_apiv1_api_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyAuditResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyAuditResponse) GetChainOk() bool {
	if x != nil {
		return x.ChainOk
	}
	return false
}

func (x *VerifyAuditResponse) GetChecked() int64 {
	if x != nil {
		return x.Checked
	}
	return 0
}

func (x *VerifyAuditResponse) GetCheckpointsOk() bool {
	if x != nil {
		return x.CheckpointsOk
	}
	return false
}

func (x *VerifyAuditResponse) GetCheckpointCount() int32 {
	if x != nil {
		return x.CheckpointCount
	}
	return 0
}

func (x *VerifyAuditResponse) GetLatestAttestedSeq() int64 {
	if x != nil {
		return x.LatestAttestedSeq
	}
	return 0
}

func (x *VerifyAuditResponse) GetCheckpointStatus() string {
	if x != nil {
		return x.CheckpointStatus
	}
	return ""
}

var File_apiv1_api_proto protoreflect.FileDescriptor

const file_apiv1_api_proto_rawDesc = "" +
	"\n" +
	"\x0fapiv1/api.proto\x12\x0folivares.api.v1\"\a\n" +
	"\x05Empty\"\x8c\x02\n" +
	"\n" +
	"ServerInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06engine\x18\x02 \x01(\tR\x06engine\x12%\n" +
	"\x0esetup_required\x18\x03 \x01(\bR\rsetupRequired\x12%\n" +
	"\x0elicense_status\x18\x04 \x01(\tR\rlicenseStatus\x12)\n" +
	"\x10license_licensee\x18\x05 \x01(\tR\x0flicenseLicensee\x12!\n" +
	"\flicense_plan\x18\x06 \x01(\tR\vlicensePlan\x120\n" +
	"\x14license_support_tier\x18\a \x01(\tR\x12licenseSupportTier\"\xed\x01\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1f\n" +
	"\vexternal_id\x18\x05 \x01(\tR\n" +
	"externalId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"Y\n" +
	"\x11ListAgentsRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"w\n" +
	"\x12ListAgentsResponse\x12.\n" +
	"\x06agents\x18\x01 \x03(\v2\x16.olivares.api.v1.AgentR\x06agents\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"9\n" +
	"\x0fGetAgentRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x8d\x01\n" +
	"\x12CreateAgentRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1f\n" +
	"\vexternal_id\x18\x04 \x01(\tR\n" +
	"externalId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"@\n" +
	"\x12VerifyAuditRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x03R\x04from\"\x89\x02\n" +
	"\x13VerifyAuditResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x19\n" +
	"\bchain_ok\x18\x02 \x01(\bR\achainOk\x12\x18\n" +
	"\achecked\x18\x03 \x01(\x03R\achecked\x12%\n" +
	"\x0echeckpoints_ok\x18\x04 \x01(\bR\rcheckpointsOk\x12)\n" +
	"\x10checkpoint_count\x18\x05 \x01(\x05R\x0fcheckpointCount\x12.\n" +
	"\x13latest_attested_seq\x18\x06 \x01(\x03R\x11latestAttestedSeq\x12+\n" +
	"\x11checkpoint_status\x18\a \x01(\tR\x10checkpointStatus2\x97\x03\n" +
	"\fControlPlane\x12D\n" +
	"\rGetServerInfo\x12\x16.olivares.api.v1.Empty\x1a\x1b.olivares.api.v1.ServerInfo\x12U\n" +
	"\n" +
	"ListAgents\x12\".olivares.api.v1.ListAgentsRequest\x1a#.olivares.api.v1.ListAgentsResponse\x12D\n" +
	"\bGetAgent\x12 .olivares.api.v1.GetAgentRequest\x1a\x16.olivares.api.v1.Agent\x12J\n" +
	"\vCreateAgent\x12#.olivares.api.v1.CreateAgentRequest\x1a\x16.olivares.api.v1.Agent\x12X\n" +
	"\vVerifyAudit\x12#.olivares.api.v1.VerifyAuditRequest\x1a$.olivares.api.v1.VerifyAuditResponseB;Z9github.com/olivaresai/olivares/core/api/genpb/apiv1;apiv1b\x06proto3"

var (
	file_apiv1_api_proto_rawDescOnce sync.Once
	file_apiv1_api_proto_rawDescData []byte
)

func file_apiv1_api_proto_rawDescGZIP() []byte {
	file_apiv1_api_proto_rawDescOnce.Do(func() {
		file_apiv1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiv1_api_proto_rawDesc), len(file_apiv1_api_proto_rawDesc)))
	})
	return file_apiv1_api_proto_rawDescData
}

var file_apiv1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_apiv1_api_proto_goTypes = []any{
	(*Empty)(nil),               // 0: olivares.api.v1.Empty
	(*ServerInfo)(nil),          // 1: olivares.api.v1.ServerInfo
	(*Agent)(nil),               // 2: olivares.api.v1.Agent
	(*ListAgentsRequest)(nil),   // 3: olivares.api.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),  // 4: olivares.api.v1.ListAgentsResponse
	(*GetAgentRequest)(nil),     // 5: olivares.api.v1.GetAgentRequest
	(*CreateAgentRequest)(nil),  // 6: olivares.api.v1.CreateAgentRequest
	(*VerifyAuditRequest)(nil),  // 7: olivares.api.v1.VerifyAuditRequest
	(*VerifyAuditResponse)(nil), // 8: olivares.api.v1.VerifyAuditResponse
}
var file_apiv1_api_proto_depIdxs = []int32{
	2, // 0: olivares.api.v1.ListAgentsResponse.agents:type_name -> olivares.api.v1.Agent
	0, // 1: olivares.api.v1.ControlPlane.GetServerInfo:input_type -> olivares.api.v1.Empty
	3, // 2: olivares.api.v1.ControlPlane.ListAgents:input_type -> olivares.api.v1.ListAgentsRequest
	5, // 3: olivares.api.v1.ControlPlane.GetAgent:input_type -> olivares.api.v1.GetAgentRequest
	6, // 4: olivares.api.v1.ControlPlane.CreateAgent:input_type -> olivares.api.v1.CreateAgentRequest
	7, // 5: olivares.api.v1.ControlPlane.VerifyAudit:input_type -> olivares.api.v1.VerifyAuditRequest
	1, // 6: olivares.api.v1.ControlPlane.GetServerInfo:output_type -> olivares.api.v1.ServerInfo
	4, // 7: olivares.api.v1.ControlPlane.ListAgents:output_type -> olivares.api.v1.ListAgentsResponse
	2, // 8: olivares.api.v1.ControlPlane.GetAgent:output_type -> olivares.api.v1.Agent
	2, // 9: olivares.api.v1.ControlPlane.CreateAgent:output_type -> olivares.api.v1.Agent
	8, // 10: olivares.api.v1.ControlPlane.VerifyAudit:output_type -> olivares.api.v1.VerifyAuditResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apiv1_api_proto_init() }
func file_apiv1_api_proto_init() {
	if File_apiv1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiv1_api_proto_rawDesc), len(file_apiv1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apiv1_api_proto_goTypes,
		DependencyIndexes: file_apiv1_api_proto_depIdxs,
		MessageInfos:      file_apiv1_api_proto_msgTypes,
	}.Build()
	File_apiv1_api_proto = out.File
	file_apiv1_api_proto_goTypes = nil
	file_apiv1_api_proto_depIdxs = nil
}
