{{- /*
SPDX-FileCopyrightText: 2026 Olivares.AI
SPDX-License-Identifier: AGPL-3.0-only
*/ -}}
{{- if .Values.core.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "olivares.core.fullname" . }}
  labels:
    {{- include "olivares.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "olivares.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: core
  ports:
    - name: https
      port: {{ .Values.service.httpPort }}
      targetPort: https
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
{{- end }}
