# SPDX-FileCopyrightText: 2026 Olivares.AI
# SPDX-License-Identifier: AGPL-3.0-only
#
# olivares-selinux: the Olivares AI appliance's SELinux policy module, packaged the way Fedora's independent-policy
# guideline describes (a noarch -selinux package; priority 200 comes from %selinux_modules_install). Its three sources
# are generated by appliance/selinux/generate.py from access.tsv and contexts.tsv; build them from that directory:
#   rpmbuild -bb --define "_sourcedir $PWD/appliance/selinux" appliance/selinux/olivares-selinux.spec
%global modulename olivares
%global selinuxtype targeted

Name:           olivares-selinux
Version:        1.0.0
Release:        1%{?dist}
Summary:        SELinux policy module of the Olivares AI appliance
License:        AGPL-3.0-only
URL:            https://github.com/olivaresai/olivares
Source0:        %{modulename}.te
Source1:        %{modulename}.fc
Source2:        %{modulename}.if
BuildArch:      noarch
BuildRequires:  selinux-policy-devel
BuildRequires:  bzip2
BuildRequires:  make
Requires:       selinux-policy-%{selinuxtype}
Requires(post): selinux-policy-%{selinuxtype}
Requires(post): policycoreutils-python-utils
Requires(postun): policycoreutils-python-utils
%{?selinux_requires_min}

%description
The SELinux policy module olivares confines the Olivares AI appliance's services under the targeted policy,
enforcing: the Appliance Console, the repair console on tty1, the power and support-bundle helpers, the
return-point units, first boot and the product engine, each in its own domain entered only through its
program. It labels the appliance's files, and on first install records its four ports.

%prep
%setup -q -c -T
cp -p %{SOURCE0} %{SOURCE1} %{SOURCE2} .

%build
make -f %{_datadir}/selinux/devel/Makefile %{modulename}.pp
bzip2 -9 %{modulename}.pp

%install
install -D -m 0644 %{modulename}.pp.bz2 %{buildroot}%{_datadir}/selinux/packages/%{selinuxtype}/%{modulename}.pp.bz2
install -D -p -m 0644 %{modulename}.if %{buildroot}%{_datadir}/selinux/devel/include/distributed/%{modulename}.if

%pre
%selinux_relabel_pre -s %{selinuxtype}

%post
%selinux_modules_install -s %{selinuxtype} %{_datadir}/selinux/packages/%{selinuxtype}/%{modulename}.pp.bz2
# Without a loaded policy (an image build, a container) semanage writes the store and does not reload (-N). A failed
# import is named on stderr and the scriptlet still exits 0, as every scriptlet must; the next upgrade repairs it.
if selinuxenabled; then reload=; else reload=-N; fi
if [ "$1" -eq 1 ]; then
# First install. One transaction for the four ports. port -m changes only a record the policy holds for exactly
# that port: Fedora has one for 8443 (http_port_t), so 8443 is modified. 8444 and 11434 lie only in the unreserved
# range and 9443 only in pki_ca_port_t's 9443-9447 range, so each gets its own, narrower record with port -a.
%{_sbindir}/semanage import -S %{selinuxtype} $reload <<'OLIVARES_PORTS' || echo "olivares-selinux: semanage could not record the ports 8443, 8444, 9443 and 11434; the appliance's services cannot bind or reach them until it does (see semanage port -l -C)" >&2
port -a -t olivares_grpc_port_t -p tcp 8444
port -a -t olivares_model_runtime_port_t -p tcp 11434
port -m -t olivares_console_port_t -p tcp 8443
port -a -t olivares_portal_port_t -p tcp 9443
OLIVARES_PORTS
fi
if [ "$1" -ge 2 ]; then
# Upgrade. Add any of the four records that is missing (a first install whose import failed, a record deleted by
# hand) with the same operation as the first install; a record that is there is left as it is.
records=$(%{_sbindir}/semanage port -l -C 2>/dev/null || :)
repair=$(while read -r type port record; do
if ! echo "$records" | grep -Eq "^${type}[[:space:]]+tcp[[:space:]]+${port}[[:space:]]*\$"; then echo "$record"; fi
done <<'OLIVARES_PORTS'
olivares_grpc_port_t 8444 port -a -t olivares_grpc_port_t -p tcp 8444
olivares_model_runtime_port_t 11434 port -a -t olivares_model_runtime_port_t -p tcp 11434
olivares_console_port_t 8443 port -m -t olivares_console_port_t -p tcp 8443
olivares_portal_port_t 9443 port -a -t olivares_portal_port_t -p tcp 9443
OLIVARES_PORTS
)
if [ -n "$repair" ]; then
echo "$repair" | %{_sbindir}/semanage import -S %{selinuxtype} $reload || echo "olivares-selinux: semanage could not add the missing records among the ports 8443, 8444, 9443 and 11434; the appliance's services cannot bind or reach them until it does (see semanage port -l -C)" >&2
fi
fi

%postun
if [ "$1" -eq 0 ]; then
# Erase only. The port records name the module's types, so they are deleted before the module leaves.
if selinuxenabled; then reload=; else reload=-N; fi
%{_sbindir}/semanage import -S %{selinuxtype} $reload <<'OLIVARES_PORTS' || echo "olivares-selinux: semanage could not delete the port records of 8443, 8444, 9443 and 11434 (see semanage port -l -C)" >&2
port -d -p tcp 8444
port -d -p tcp 11434
port -d -p tcp 8443
port -d -p tcp 9443
OLIVARES_PORTS
%selinux_modules_uninstall -s %{selinuxtype} %{modulename}
fi

%posttrans
%selinux_relabel_post -s %{selinuxtype}

%files
%{_datadir}/selinux/packages/%{selinuxtype}/%{modulename}.pp.bz2
%{_datadir}/selinux/devel/include/distributed/%{modulename}.if
%ghost %verify(not md5 size mode mtime) %{_sharedstatedir}/selinux/%{selinuxtype}/active/modules/200/%{modulename}

%changelog
* Sun Sep 27 2026 Olivares.AI <enterprise@olivares.ai> - 1.0.0-1
- A failed port import is named on stderr; an upgrade adds any of the four port records that is missing.
- The appliance's SELinux policy module, generated from its rule tables.
