// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: Apache-2.0

// @olivaresai/client — first-party TypeScript client for the Olivares AI
// control plane REST API (the published /v1 contract). The Client class is the
// generated operation layer (operations.gen.ts, regenerated by
// `task sdk:generate`) on top of the hand-written transport core (core.ts).
// Governing policy: https://olivares.ai/docs.

export {
  APIError,
  ClientCore,
  VERSION,
  type ClientOptions,
  type DeprecationNotice,
  type Json,
  type JsonInput,
  type RequestOptions,
} from "./core.js";
export { Client } from "./operations.gen.js";
export { API_VERSION, SPEC_HASH, STABILITY_POLICY } from "./version.gen.js";
