// Code generated by clients/generator from the Olivares OpenAPI snapshots (stable core + beta module routes); DO NOT EDIT.

/** The control-plane API contract major this client is generated against. */
export const API_VERSION = "v1";
/** SHA-256 binding the OpenAPI snapshots (stable + beta) the operation layer was generated from. */
export const SPEC_HASH = "7ba1caee75b2092bdd7e5de30b8c3bf9de48fad83e8320a4695362c05d1eaa0b";
/** The public versioning/deprecation/sunset policy governing this surface. */
export const STABILITY_POLICY = "https://olivares.ai/docs";
