// Code generated by clients/generator from the Olivares OpenAPI snapshots (stable core + beta module routes); DO NOT EDIT.

/** The control-plane API contract major this client is generated against. */
export const API_VERSION = "v1";
/** SHA-256 binding the OpenAPI snapshots (stable + beta) the operation layer was generated from. */
export const SPEC_HASH = "641d97ca7da284483cf51d3cab34825780d11114851df95754385b8eb0361086";
/** The public versioning/deprecation/sunset policy governing this surface. */
export const STABILITY_POLICY = "https://olivares.ai/docs";
