// Code generated by clients/generator from the Olivares OpenAPI snapshots (stable core + beta module routes); DO NOT EDIT.

/** The control-plane API contract major this client is generated against. */
export const API_VERSION = "v1";
/** SHA-256 binding the OpenAPI snapshots (stable + beta) the operation layer was generated from. */
export const SPEC_HASH = "0a3ae0cb1b43e677bf5a00cfdb62b1e11a54ce076180aafa0c7537d78cf6357b";
/** The public versioning/deprecation/sunset policy governing this surface. */
export const STABILITY_POLICY = "https://olivares.ai/docs";
