// Code generated by clients/generator from the Olivares OpenAPI snapshots
// (stable core + beta module routes); DO NOT EDIT.

package olivares

// APIVersion is the control-plane API contract major this client is generated
// against; the SDK's own MAJOR tracks it from GA on (stability policy).
const APIVersion = "v1"

// SpecHash binds the OpenAPI snapshots the operation layer was generated
// from (the stable core + beta module-route documents under web/openapi).
const SpecHash = "016b467b0934c254bc48f178ff02d7d1242a4feb05b0f97d0467ddd459ea2c45"

// StabilityPolicy is the public versioning/deprecation/sunset commitment
// governing this surface.
const StabilityPolicy = "https://olivares.ai/docs"
