// Code generated by clients/generator from the Olivares OpenAPI snapshots
// (stable core + beta module routes); DO NOT EDIT.

package olivares

// APIVersion is the control-plane API contract major this client is generated
// against; the SDK's own MAJOR tracks it from GA on (stability policy).
const APIVersion = "v1"

// SpecHash binds the OpenAPI snapshots the operation layer was generated
// from (the stable core + beta module-route documents under web/openapi).
const SpecHash = "2793a247ca86bd6b9e4aa19953ab2947ffa491900c03ec1e6ba55c56232b4702"

// StabilityPolicy is the public versioning/deprecation/sunset commitment
// governing this surface.
const StabilityPolicy = "https://olivares.ai/docs"
