// Code generated by clients/generator from the Olivares OpenAPI snapshots
// (stable core + beta module routes); DO NOT EDIT.

package olivares

// APIVersion is the control-plane API contract major this client is generated
// against; the SDK's own MAJOR tracks it from GA on (stability policy).
const APIVersion = "v1"

// SpecHash binds the OpenAPI snapshots the operation layer was generated
// from (the stable core + beta module-route documents under web/openapi).
const SpecHash = "0a3ae0cb1b43e677bf5a00cfdb62b1e11a54ce076180aafa0c7537d78cf6357b"

// StabilityPolicy is the public versioning/deprecation/sunset commitment
// governing this surface.
const StabilityPolicy = "https://olivares.ai/docs"
