// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: Apache-2.0

// Olivares AI connector/module wire contract, v1.
//
// This is the STABLE, versioned contract that every out-of-process connector
// and module speaks to the engine. Changes are gated by buf's breaking-change
// detector; an incompatible change requires a new major package (olivares.sdk.v2)
// and a bump of the go-plugin protocol version (see handshake.go).
//
// Vocabulary fields (access mode, signal source, confidence, severity, event
// type) are strings, not closed proto enums, because the Go SDK models them as
// open string types — a third-party connector may introduce its own signal
// source without an SDK release. The payload shape, by contrast, is closed: an
// Observation/Event payload is a oneof of the known message types plus a JSON
// fallback for module-defined event payloads.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: olivaresv1/v1.proto

package olivaresv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SourceService_Describe_FullMethodName = "/olivares.sdk.v1.SourceService/Describe"
	SourceService_Open_FullMethodName     = "/olivares.sdk.v1.SourceService/Open"
	SourceService_Gather_FullMethodName   = "/olivares.sdk.v1.SourceService/Gather"
	SourceService_Close_FullMethodName    = "/olivares.sdk.v1.SourceService/Close"
)

// SourceServiceClient is the client API for SourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SourceService is served by a SourceConnector plugin. Gather is server-
// streaming: the plugin streams observations to the host, which lifts each onto
// the event bus. The stream ends when the source's run completes (batch) or the
// host cancels the RPC (streaming source).
type SourceServiceClient interface {
	Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DescribeResponse, error)
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*Empty, error)
	Gather(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Observation], error)
	Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type sourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceServiceClient(cc grpc.ClientConnInterface) SourceServiceClient {
	return &sourceServiceClient{cc}
}

func (c *sourceServiceClient) Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, SourceService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SourceService_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) Gather(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Observation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SourceService_ServiceDesc.Streams[0], SourceService_Gather_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Observation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SourceService_GatherClient = grpc.ServerStreamingClient[Observation]

func (c *sourceServiceClient) Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SourceService_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceServiceServer is the server API for SourceService service.
// All implementations must embed UnimplementedSourceServiceServer
// for forward compatibility.
//
// SourceService is served by a SourceConnector plugin. Gather is server-
// streaming: the plugin streams observations to the host, which lifts each onto
// the event bus. The stream ends when the source's run completes (batch) or the
// host cancels the RPC (streaming source).
type SourceServiceServer interface {
	Describe(context.Context, *Empty) (*DescribeResponse, error)
	Open(context.Context, *OpenRequest) (*Empty, error)
	Gather(*Empty, grpc.ServerStreamingServer[Observation]) error
	Close(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedSourceServiceServer()
}

// UnimplementedSourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceServiceServer struct{}

func (UnimplementedSourceServiceServer) Describe(context.Context, *Empty) (*DescribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedSourceServiceServer) Open(context.Context, *OpenRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedSourceServiceServer) Gather(*Empty, grpc.ServerStreamingServer[Observation]) error {
	return status.Errorf(codes.Unimplemented, "method Gather not implemented")
}
func (UnimplementedSourceServiceServer) Close(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedSourceServiceServer) mustEmbedUnimplementedSourceServiceServer() {}
func (UnimplementedSourceServiceServer) testEmbeddedByValue()                       {}

// UnsafeSourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceServiceServer will
// result in compilation errors.
type UnsafeSourceServiceServer interface {
	mustEmbedUnimplementedSourceServiceServer()
}

func RegisterSourceServiceServer(s grpc.ServiceRegistrar, srv SourceServiceServer) {
	// If the following call pancis, it indicates UnimplementedSourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SourceService_ServiceDesc, srv)
}

func _SourceService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Describe(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_Gather_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SourceServiceServer).Gather(m, &grpc.GenericServerStream[Empty, Observation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SourceService_GatherServer = grpc.ServerStreamingServer[Observation]

func _SourceService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Close(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SourceService_ServiceDesc is the grpc.ServiceDesc for SourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "olivares.sdk.v1.SourceService",
	HandlerType: (*SourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _SourceService_Describe_Handler,
		},
		{
			MethodName: "Open",
			Handler:    _SourceService_Open_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _SourceService_Close_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Gather",
			Handler:       _SourceService_Gather_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "olivaresv1/v1.proto",
}

const (
	OutputService_Describe_FullMethodName = "/olivares.sdk.v1.OutputService/Describe"
	OutputService_Open_FullMethodName     = "/olivares.sdk.v1.OutputService/Open"
	OutputService_Notify_FullMethodName   = "/olivares.sdk.v1.OutputService/Notify"
	OutputService_Close_FullMethodName    = "/olivares.sdk.v1.OutputService/Close"
)

// OutputServiceClient is the client API for OutputService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OutputService is served by an OutputConnector plugin.
type OutputServiceClient interface {
	Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DescribeResponse, error)
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*Empty, error)
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type outputServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOutputServiceClient(cc grpc.ClientConnInterface) OutputServiceClient {
	return &outputServiceClient{cc}
}

func (c *outputServiceClient) Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, OutputService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outputServiceClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OutputService_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outputServiceClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, OutputService_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outputServiceClient) Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OutputService_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutputServiceServer is the server API for OutputService service.
// All implementations must embed UnimplementedOutputServiceServer
// for forward compatibility.
//
// OutputService is served by an OutputConnector plugin.
type OutputServiceServer interface {
	Describe(context.Context, *Empty) (*DescribeResponse, error)
	Open(context.Context, *OpenRequest) (*Empty, error)
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	Close(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedOutputServiceServer()
}

// UnimplementedOutputServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutputServiceServer struct{}

func (UnimplementedOutputServiceServer) Describe(context.Context, *Empty) (*DescribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedOutputServiceServer) Open(context.Context, *OpenRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedOutputServiceServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedOutputServiceServer) Close(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedOutputServiceServer) mustEmbedUnimplementedOutputServiceServer() {}
func (UnimplementedOutputServiceServer) testEmbeddedByValue()                       {}

// UnsafeOutputServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutputServiceServer will
// result in compilation errors.
type UnsafeOutputServiceServer interface {
	mustEmbedUnimplementedOutputServiceServer()
}

func RegisterOutputServiceServer(s grpc.ServiceRegistrar, srv OutputServiceServer) {
	// If the following call pancis, it indicates UnimplementedOutputServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OutputService_ServiceDesc, srv)
}

func _OutputService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutputService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputServiceServer).Describe(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutputService_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputServiceServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutputService_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputServiceServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutputService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutputService_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputServiceServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutputService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutputService_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputServiceServer).Close(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// OutputService_ServiceDesc is the grpc.ServiceDesc for OutputService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutputService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "olivares.sdk.v1.OutputService",
	HandlerType: (*OutputServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _OutputService_Describe_Handler,
		},
		{
			MethodName: "Open",
			Handler:    _OutputService_Open_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _OutputService_Notify_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _OutputService_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "olivaresv1/v1.proto",
}

const (
	ContentSourceService_Describe_FullMethodName  = "/olivares.sdk.v1.ContentSourceService/Describe"
	ContentSourceService_Open_FullMethodName      = "/olivares.sdk.v1.ContentSourceService/Open"
	ContentSourceService_List_FullMethodName      = "/olivares.sdk.v1.ContentSourceService/List"
	ContentSourceService_Fetch_FullMethodName     = "/olivares.sdk.v1.ContentSourceService/Fetch"
	ContentSourceService_FetchACL_FullMethodName  = "/olivares.sdk.v1.ContentSourceService/FetchACL"
	ContentSourceService_DeltaList_FullMethodName = "/olivares.sdk.v1.ContentSourceService/DeltaList"
	ContentSourceService_Close_FullMethodName     = "/olivares.sdk.v1.ContentSourceService/Close"
)

// ContentSourceServiceClient is the client API for ContentSourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContentSourceService is served by a ContentSource plugin. List and DeltaList
// are server-streaming so a host can pull refs/changes without embedding the
// connector. FetchACL and DeltaList are called only when Describe.capabilities
// includes "content.delta".
type ContentSourceServiceClient interface {
	Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DescribeResponse, error)
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*Empty, error)
	List(ctx context.Context, in *ContentListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContentDocRef], error)
	Fetch(ctx context.Context, in *ContentFetchRequest, opts ...grpc.CallOption) (*ContentDocument, error)
	FetchACL(ctx context.Context, in *ContentFetchRequest, opts ...grpc.CallOption) (*ContentACLResult, error)
	DeltaList(ctx context.Context, in *ContentDeltaRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContentChange], error)
	Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type contentSourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContentSourceServiceClient(cc grpc.ClientConnInterface) ContentSourceServiceClient {
	return &contentSourceServiceClient{cc}
}

func (c *contentSourceServiceClient) Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, ContentSourceService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentSourceServiceClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ContentSourceService_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentSourceServiceClient) List(ctx context.Context, in *ContentListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContentDocRef], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContentSourceService_ServiceDesc.Streams[0], ContentSourceService_List_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ContentListRequest, ContentDocRef]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContentSourceService_ListClient = grpc.ServerStreamingClient[ContentDocRef]

func (c *contentSourceServiceClient) Fetch(ctx context.Context, in *ContentFetchRequest, opts ...grpc.CallOption) (*ContentDocument, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentDocument)
	err := c.cc.Invoke(ctx, ContentSourceService_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentSourceServiceClient) FetchACL(ctx context.Context, in *ContentFetchRequest, opts ...grpc.CallOption) (*ContentACLResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentACLResult)
	err := c.cc.Invoke(ctx, ContentSourceService_FetchACL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentSourceServiceClient) DeltaList(ctx context.Context, in *ContentDeltaRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContentChange], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContentSourceService_ServiceDesc.Streams[1], ContentSourceService_DeltaList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ContentDeltaRequest, ContentChange]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContentSourceService_DeltaListClient = grpc.ServerStreamingClient[ContentChange]

func (c *contentSourceServiceClient) Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ContentSourceService_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentSourceServiceServer is the server API for ContentSourceService service.
// All implementations must embed UnimplementedContentSourceServiceServer
// for forward compatibility.
//
// ContentSourceService is served by a ContentSource plugin. List and DeltaList
// are server-streaming so a host can pull refs/changes without embedding the
// connector. FetchACL and DeltaList are called only when Describe.capabilities
// includes "content.delta".
type ContentSourceServiceServer interface {
	Describe(context.Context, *Empty) (*DescribeResponse, error)
	Open(context.Context, *OpenRequest) (*Empty, error)
	List(*ContentListRequest, grpc.ServerStreamingServer[ContentDocRef]) error
	Fetch(context.Context, *ContentFetchRequest) (*ContentDocument, error)
	FetchACL(context.Context, *ContentFetchRequest) (*ContentACLResult, error)
	DeltaList(*ContentDeltaRequest, grpc.ServerStreamingServer[ContentChange]) error
	Close(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedContentSourceServiceServer()
}

// UnimplementedContentSourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentSourceServiceServer struct{}

func (UnimplementedContentSourceServiceServer) Describe(context.Context, *Empty) (*DescribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedContentSourceServiceServer) Open(context.Context, *OpenRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedContentSourceServiceServer) List(*ContentListRequest, grpc.ServerStreamingServer[ContentDocRef]) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedContentSourceServiceServer) Fetch(context.Context, *ContentFetchRequest) (*ContentDocument, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedContentSourceServiceServer) FetchACL(context.Context, *ContentFetchRequest) (*ContentACLResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchACL not implemented")
}
func (UnimplementedContentSourceServiceServer) DeltaList(*ContentDeltaRequest, grpc.ServerStreamingServer[ContentChange]) error {
	return status.Errorf(codes.Unimplemented, "method DeltaList not implemented")
}
func (UnimplementedContentSourceServiceServer) Close(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedContentSourceServiceServer) mustEmbedUnimplementedContentSourceServiceServer() {}
func (UnimplementedContentSourceServiceServer) testEmbeddedByValue()                              {}

// UnsafeContentSourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentSourceServiceServer will
// result in compilation errors.
type UnsafeContentSourceServiceServer interface {
	mustEmbedUnimplementedContentSourceServiceServer()
}

func RegisterContentSourceServiceServer(s grpc.ServiceRegistrar, srv ContentSourceServiceServer) {
	// If the following call pancis, it indicates UnimplementedContentSourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentSourceService_ServiceDesc, srv)
}

func _ContentSourceService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentSourceServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentSourceService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentSourceServiceServer).Describe(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentSourceService_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentSourceServiceServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentSourceService_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentSourceServiceServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentSourceService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContentListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContentSourceServiceServer).List(m, &grpc.GenericServerStream[ContentListRequest, ContentDocRef]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContentSourceService_ListServer = grpc.ServerStreamingServer[ContentDocRef]

func _ContentSourceService_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentFetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentSourceServiceServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentSourceService_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentSourceServiceServer).Fetch(ctx, req.(*ContentFetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentSourceService_FetchACL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentFetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentSourceServiceServer).FetchACL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentSourceService_FetchACL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentSourceServiceServer).FetchACL(ctx, req.(*ContentFetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentSourceService_DeltaList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContentDeltaRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContentSourceServiceServer).DeltaList(m, &grpc.GenericServerStream[ContentDeltaRequest, ContentChange]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContentSourceService_DeltaListServer = grpc.ServerStreamingServer[ContentChange]

func _ContentSourceService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentSourceServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentSourceService_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentSourceServiceServer).Close(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentSourceService_ServiceDesc is the grpc.ServiceDesc for ContentSourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentSourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "olivares.sdk.v1.ContentSourceService",
	HandlerType: (*ContentSourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _ContentSourceService_Describe_Handler,
		},
		{
			MethodName: "Open",
			Handler:    _ContentSourceService_Open_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _ContentSourceService_Fetch_Handler,
		},
		{
			MethodName: "FetchACL",
			Handler:    _ContentSourceService_FetchACL_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _ContentSourceService_Close_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _ContentSourceService_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeltaList",
			Handler:       _ContentSourceService_DeltaList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "olivaresv1/v1.proto",
}

const (
	IngestService_Push_FullMethodName = "/olivares.sdk.v1.IngestService/Push"
)

// IngestServiceClient is the client API for IngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IngestService is served BY THE CORE and dialed by a collector daemon. Push is
// client-streaming: the collector streams observations to the core, which lifts
// each onto the event bus exactly as an in-process source's Sink would, so the
// SAME SourceConnector contract drives both the in-host (B) and remote (C)
// transports. The channel is gRPC + mTLS (a verified collector client cert); the
// collector additionally presents a bearer token and the core authorizes ingest
// per tenant (docs/SECURITY-HARDENING.md, §3). The observation payload is the SAME sealed oneof a
// plugin streams over SourceService — no new wire shape, no raw payload.
type IngestServiceClient interface {
	Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestEnvelope, IngestSummary], error)
}

type ingestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestServiceClient(cc grpc.ClientConnInterface) IngestServiceClient {
	return &ingestServiceClient{cc}
}

func (c *ingestServiceClient) Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestEnvelope, IngestSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestService_ServiceDesc.Streams[0], IngestService_Push_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestEnvelope, IngestSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_PushClient = grpc.ClientStreamingClient[IngestEnvelope, IngestSummary]

// IngestServiceServer is the server API for IngestService service.
// All implementations must embed UnimplementedIngestServiceServer
// for forward compatibility.
//
// IngestService is served BY THE CORE and dialed by a collector daemon. Push is
// client-streaming: the collector streams observations to the core, which lifts
// each onto the event bus exactly as an in-process source's Sink would, so the
// SAME SourceConnector contract drives both the in-host (B) and remote (C)
// transports. The channel is gRPC + mTLS (a verified collector client cert); the
// collector additionally presents a bearer token and the core authorizes ingest
// per tenant (docs/SECURITY-HARDENING.md, §3). The observation payload is the SAME sealed oneof a
// plugin streams over SourceService — no new wire shape, no raw payload.
type IngestServiceServer interface {
	Push(grpc.ClientStreamingServer[IngestEnvelope, IngestSummary]) error
	mustEmbedUnimplementedIngestServiceServer()
}

// UnimplementedIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestServiceServer struct{}

func (UnimplementedIngestServiceServer) Push(grpc.ClientStreamingServer[IngestEnvelope, IngestSummary]) error {
	return status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedIngestServiceServer) mustEmbedUnimplementedIngestServiceServer() {}
func (UnimplementedIngestServiceServer) testEmbeddedByValue()                       {}

// UnsafeIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestServiceServer will
// result in compilation errors.
type UnsafeIngestServiceServer interface {
	mustEmbedUnimplementedIngestServiceServer()
}

func RegisterIngestServiceServer(s grpc.ServiceRegistrar, srv IngestServiceServer) {
	// If the following call pancis, it indicates UnimplementedIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestService_ServiceDesc, srv)
}

func _IngestService_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServiceServer).Push(&grpc.GenericServerStream[IngestEnvelope, IngestSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_PushServer = grpc.ClientStreamingServer[IngestEnvelope, IngestSummary]

// IngestService_ServiceDesc is the grpc.ServiceDesc for IngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "olivares.sdk.v1.IngestService",
	HandlerType: (*IngestServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _IngestService_Push_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "olivaresv1/v1.proto",
}

const (
	ModuleService_Describe_FullMethodName = "/olivares.sdk.v1.ModuleService/Describe"
	ModuleService_Init_FullMethodName     = "/olivares.sdk.v1.ModuleService/Init"
	ModuleService_Start_FullMethodName    = "/olivares.sdk.v1.ModuleService/Start"
	ModuleService_Stop_FullMethodName     = "/olivares.sdk.v1.ModuleService/Stop"
)

// ModuleServiceClient is the client API for ModuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModuleService is served by a Module plugin.
type ModuleServiceClient interface {
	Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DescribeResponse, error)
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Empty, error)
	Start(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type moduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModuleServiceClient(cc grpc.ClientConnInterface) ModuleServiceClient {
	return &moduleServiceClient{cc}
}

func (c *moduleServiceClient) Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, ModuleService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ModuleService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Start(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ModuleService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ModuleService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServiceServer is the server API for ModuleService service.
// All implementations must embed UnimplementedModuleServiceServer
// for forward compatibility.
//
// ModuleService is served by a Module plugin.
type ModuleServiceServer interface {
	Describe(context.Context, *Empty) (*DescribeResponse, error)
	Init(context.Context, *InitRequest) (*Empty, error)
	Start(context.Context, *Empty) (*Empty, error)
	Stop(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedModuleServiceServer()
}

// UnimplementedModuleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModuleServiceServer struct{}

func (UnimplementedModuleServiceServer) Describe(context.Context, *Empty) (*DescribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedModuleServiceServer) Init(context.Context, *InitRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedModuleServiceServer) Start(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedModuleServiceServer) Stop(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedModuleServiceServer) mustEmbedUnimplementedModuleServiceServer() {}
func (UnimplementedModuleServiceServer) testEmbeddedByValue()                       {}

// UnsafeModuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModuleServiceServer will
// result in compilation errors.
type UnsafeModuleServiceServer interface {
	mustEmbedUnimplementedModuleServiceServer()
}

func RegisterModuleServiceServer(s grpc.ServiceRegistrar, srv ModuleServiceServer) {
	// If the following call pancis, it indicates UnimplementedModuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModuleService_ServiceDesc, srv)
}

func _ModuleService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Describe(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Start(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ModuleService_ServiceDesc is the grpc.ServiceDesc for ModuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "olivares.sdk.v1.ModuleService",
	HandlerType: (*ModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _ModuleService_Describe_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _ModuleService_Init_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _ModuleService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _ModuleService_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "olivaresv1/v1.proto",
}

const (
	HostService_Publish_FullMethodName   = "/olivares.sdk.v1.HostService/Publish"
	HostService_Subscribe_FullMethodName = "/olivares.sdk.v1.HostService/Subscribe"
	HostService_Log_FullMethodName       = "/olivares.sdk.v1.HostService/Log"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostService is served by the ENGINE and dialed by a module plugin through the
// go-plugin broker, giving an out-of-process module the same bus/log surface an
// in-process module gets from sdk.Host.
type HostServiceClient interface {
	Publish(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Empty, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	Log(ctx context.Context, in *LogRecord, opts ...grpc.CallOption) (*Empty, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) Publish(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostService_ServiceDesc.Streams[0], HostService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostService_SubscribeClient = grpc.ServerStreamingClient[Event]

func (c *hostServiceClient) Log(ctx context.Context, in *LogRecord, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
//
// HostService is served by the ENGINE and dialed by a module plugin through the
// go-plugin broker, giving an out-of-process module the same bus/log surface an
// in-process module gets from sdk.Host.
type HostServiceServer interface {
	Publish(context.Context, *Event) (*Empty, error)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	Log(context.Context, *LogRecord) (*Empty, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) Publish(context.Context, *Event) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedHostServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedHostServiceServer) Log(context.Context, *LogRecord) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call pancis, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Publish(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostService_SubscribeServer = grpc.ServerStreamingServer[Event]

func _HostService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Log(ctx, req.(*LogRecord))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "olivares.sdk.v1.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _HostService_Publish_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _HostService_Log_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _HostService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "olivaresv1/v1.proto",
}
