# SPDX-FileCopyrightText: 2026 Olivares.AI
# SPDX-License-Identifier: AGPL-3.0-only
# tmpfiles.d(5): the data directory, owned by the service account. It holds the audit
# ledger, the audit signing key and TLS material, so nothing here removes or ages it.
d /var/lib/olivares 0750 olivares olivares -
