// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.

// Code generated by scripts/generate-module-spec.py; DO NOT EDIT.
package registry

import (
	"fmt"

	"github.com/olivaresai/olivares/core/api"
	accessmap "github.com/olivaresai/olivares/modules/access-map"
	capabilities "github.com/olivaresai/olivares/modules/capabilities"
	catalog "github.com/olivaresai/olivares/modules/catalog"
	claudeadoption "github.com/olivaresai/olivares/modules/claudeadoption"
	compliance "github.com/olivaresai/olivares/modules/compliance"
	consoleviews "github.com/olivaresai/olivares/modules/consoleviews"
	deploy "github.com/olivaresai/olivares/modules/deploy"
	evals "github.com/olivaresai/olivares/modules/evals"
	eventing "github.com/olivaresai/olivares/modules/eventing"
	finops "github.com/olivaresai/olivares/modules/finops"
	gitpublish "github.com/olivaresai/olivares/modules/gitpublish"
	governance "github.com/olivaresai/olivares/modules/governance"
	health "github.com/olivaresai/olivares/modules/health"
	inferenceproxy "github.com/olivaresai/olivares/modules/inferenceproxy"
	inventory "github.com/olivaresai/olivares/modules/inventory"
	knowledge "github.com/olivaresai/olivares/modules/knowledge"
	liveingest "github.com/olivaresai/olivares/modules/liveingest"
	models "github.com/olivaresai/olivares/modules/models"
	notify "github.com/olivaresai/olivares/modules/notify"
	observability "github.com/olivaresai/olivares/modules/observability"
	orchestration "github.com/olivaresai/olivares/modules/orchestration"
	postureexport "github.com/olivaresai/olivares/modules/posture-export"
	recording "github.com/olivaresai/olivares/modules/recording"
	redteam "github.com/olivaresai/olivares/modules/redteam"
	reporting "github.com/olivaresai/olivares/modules/reporting"
	sandbox "github.com/olivaresai/olivares/modules/sandbox"
	security "github.com/olivaresai/olivares/modules/security"
	sessioncockpit "github.com/olivaresai/olivares/modules/sessioncockpit"
	sessions "github.com/olivaresai/olivares/modules/sessions"
	siemforward "github.com/olivaresai/olivares/modules/siemforward"
	skills "github.com/olivaresai/olivares/modules/skills"
	sourcescope "github.com/olivaresai/olivares/modules/sourcescope"
	voice "github.com/olivaresai/olivares/modules/voice"
)

func newDefault(namespace string, built map[string]api.Module) (api.Module, error) {
	switch namespace {
	case "accessmap":
		return accessmap.New(), nil
	case "capabilities":
		return capabilities.New(), nil
	case "adoption":
		return claudeadoption.New(), nil
	case "sourcescope":
		return sourcescope.New(), nil
	case "catalog":
		return catalog.New(), nil
	case "skills":
		return skills.New(skills.Options{}), nil
	case "compliance":
		return compliance.New(), nil
	case "consoleviews":
		return consoleviews.New(), nil
	case "deploy":
		return deploy.New(), nil
	case "evals":
		return evals.New(), nil
	case "eventing":
		return eventing.New(), nil
	case "finops":
		return finops.New(), nil
	case "gitpublish":
		return gitpublish.New(gitpublish.Options{}), nil
	case "governance":
		return governance.New(), nil
	case "claude-policy":
		return governance.NewPolicyConsole(), nil
	case "claude-agents":
		return governance.NewAgentsConsole(), nil
	case "identity":
		return governance.NewIdentityConsole(), nil
	case "health":
		return health.New(), nil
	case "inventory":
		return inventory.New(), nil
	case "knowledge":
		return knowledge.New(), nil
	case "liveingest":
		return liveingest.New(), nil
	case "models":
		return models.New(), nil
	case "inferenceproxy":
		return inferenceproxy.New(), nil
	case "notify":
		return notify.New(), nil
	case "observability":
		return observability.New(), nil
	case "orchestration":
		return orchestration.New(), nil
	case "posture":
		return postureexport.New(), nil
	case "recording":
		return recording.New(), nil
	case "redteam":
		return redteam.New(), nil
	case "reporting":
		return reporting.New(), nil
	case "sandbox":
		return sandbox.New(), nil
	case "security":
		return security.New(), nil
	case "siemforward":
		eventingInput, ok := built["eventing"].(*eventing.Module)
		if !ok {
			return nil, fmt.Errorf("module %s needs a %s constructor input", "siemforward", "eventing")
		}
		return siemforward.New(eventingInput), nil
	case "sessions":
		return sessions.New(), nil
	case "voice":
		return voice.New(), nil
	case "session-cockpit":
		return sessioncockpit.NewPlaceholder(), nil
	default:
		return nil, fmt.Errorf("module spec %q has no generated constructor; run scripts/generate-module-spec.py", namespace)
	}
}
