// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.

//go:build release

package firstparty

import "embed"

// bins holds the plugin binaries in a release build. The explicit
// bins/claude-source pattern is a compile-time fail-closed guard: all:bins alone
// would match PLACEHOLDER and silently allow a release with zero real plugins.
// Go refuses to compile this file until the flagship connector has been built;
// all:bins then embeds the complete canonical payload generated by
// scripts/build-connectors.sh.
//
//go:embed all:bins bins/claude-source
var bins embed.FS
