// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.

package main

import (
	"crypto/ed25519"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"

	"github.com/spf13/cobra"

	"github.com/olivaresai/olivares/core/api"
	"github.com/olivaresai/olivares/core/audit"
)

// newOpenAPICmd prints an OpenAPI 3.1 document to stdout, for client codegen. It
// is the reproducible source for the web client's typed codegen and the Go/Python/
// TypeScript SDKs: it dumps the SAME documents the engine serves WITHOUT needing a
// running server, so `task openapi:dump` can refresh the committed snapshots and CI
// can diff them against this Go source.
//
//   - default:  GET /openapi.json      — the STABLE core contract (web/openapi/openapi.json).
//   - --beta:   GET /openapi.beta.json — the BETA module-route document (web/openapi/openapi.beta.json),
//     reflected from the routes the product's modules register.
func newOpenAPICmd() *cobra.Command {
	var beta bool
	cmd := &cobra.Command{
		Use:   "openapi",
		Short: "Print an OpenAPI 3.1 document (stable core, or --beta module routes) for client codegen",
		Long: "openapi prints the deterministic OpenAPI 3.1 document generated by this binary. The\n" +
			"default is the stable core contract; --beta reflects the registered module routes.",
		Example: `  olivares openapi > web/openapi/openapi.json
  olivares openapi --beta > web/openapi/openapi.beta.json`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			doc := api.OpenAPIDocument()
			if beta {
				d, err := moduleOpenAPIDocument()
				if err != nil {
					return err
				}
				doc = d
			}
			// Indent deterministically so the committed snapshot has a stable,
			// reviewable diff; trailing newline matches POSIX text-file convention.
			// render-exempt: the JSON document IS this command's output, not a
			// report about something. `openapi` exists to emit a spec for client
			// codegen; a "text" rendering of an OpenAPI document is not a thing,
			// and a generator reading stdout must get the spec byte-for-byte.
			b, err := json.MarshalIndent(doc, "", "  ")
			if err != nil {
				return fmt.Errorf("marshal openapi document: %w", err)
			}
			_, err = fmt.Fprintf(cmd.OutOrStdout(), "%s\n", b)
			return err
		},
	}
	cmd.Flags().BoolVar(&beta, "beta", false,
		"print the BETA module-route document (/v1/m/<ns>/…) instead of the stable core contract")
	return cmd
}

// moduleOpenAPIDocument builds the beta module-route document WITHOUT a running
// server: it constructs the production module set (buildModules is pure wiring with
// no I/O) and reflects the routes each module registers. The ephemeral signer and
// the silent logger exist only to satisfy buildModules; no route registration
// depends on them, so the document is reproducible.
func moduleOpenAPIDocument() (map[string]any, error) {
	_, priv, err := ed25519.GenerateKey(nil)
	if err != nil {
		return nil, fmt.Errorf("ephemeral signer key: %w", err)
	}
	signer, err := audit.NewSigner(priv)
	if err != nil {
		return nil, fmt.Errorf("ephemeral signer: %w", err)
	}
	log := slog.New(slog.NewTextHandler(io.Discard, nil))
	set, err := buildModules(signer, nil, nil, nil, nil, sourcesConfig{}, log)
	if err != nil {
		return nil, fmt.Errorf("load module operator config: %w", err)
	}
	return api.ModuleOpenAPIDocument(set.all), nil
}
