// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.

package main

import (
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/olivaresai/olivares/core/release"
)

func TestReleaseManifestVersionHelpStableAcrossBuilds(t *testing.T) {
	original := version
	t.Cleanup(func() { version = original })
	var usage string
	for _, build := range []string{"dev", "26.1001", "26.11"} {
		t.Run(build, func(t *testing.T) {
			version = build
			cmd := newReleaseManifestCmd()
			flag := cmd.Flags().Lookup("version")
			if !strings.Contains(flag.Usage, "MAJOR.MINOR") || !strings.Contains(flag.Usage, "required") {
				t.Errorf("version flag must describe the required MAJOR.MINOR input: %q", flag.Usage)
			}
			if usage != "" && flag.Usage != usage {
				t.Errorf("generated reference depends on build version: %q != %q", flag.Usage, usage)
			}
			usage = flag.Usage
			if !strings.Contains(cmd.Example, "--version "+build+" ") {
				t.Errorf("command example must use build version %q: %s", build, cmd.Example)
			}
		})
	}
}

// TestReleaseManifestGeneratorRoundTrip proves the PRODUCER (`release manifest`)
// emits a manifest the CONSUMER (core/release.VerifyManifest) accepts: build a dir
// of fake archives, sign, then verify + confirm the recorded digests are real. This
// closes the loop the client e2e opens with hand-built manifests.
func TestReleaseManifestGeneratorRoundTrip(t *testing.T) {
	dir := t.TempDir()
	// Two platform archives + a FIPS variant + noise that must be ignored.
	write := func(name string, b []byte) {
		if err := os.WriteFile(filepath.Join(dir, name), b, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	amd := []byte("fake-linux-amd64-archive")
	arm := []byte("fake-darwin-arm64-archive")
	write("olivares_26.800_linux_amd64.tar.gz", amd)
	write("olivares_26.800_darwin_arm64.tar.gz", arm)
	write("olivares_26.800_fips_linux_amd64.tar.gz", []byte("fips-variant-skip-me"))
	write("checksums.txt", []byte("noise"))

	// A signing key (32-byte seed form).
	pub, priv, _ := ed25519.GenerateKey(nil)
	seed := priv.Seed()
	keyFile := filepath.Join(dir, "sign.key")
	if err := os.WriteFile(keyFile, []byte(base64.StdEncoding.EncodeToString(seed)), 0o600); err != nil {
		t.Fatal(err)
	}
	outPath := filepath.Join(dir, "manifest.json")

	cmd := newReleaseCmd()
	var buf bytes.Buffer
	cmd.SetOut(&buf)
	cmd.SetErr(&buf)
	cmd.SetArgs([]string{"manifest", "--channel", "security", "--version", "26.800",
		"--dir", dir, "--min-version", "26.600", "--advisory", "CVE-2026-1", "--security",
		"--rollout", "50", "--out", outPath})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("release manifest: %v\n%s", err, buf.String())
	}
	// The release custodian signs the exact CI-generated bytes in a separate off-box command. This
	// must not regenerate released_at or any artifact digest.
	cmd = newReleaseCmd()
	buf.Reset()
	cmd.SetOut(&buf)
	cmd.SetErr(&buf)
	// This fixture's checksums.txt is deliberate noise (it exists to prove the
	// generator never treats it as an artifact), so the cross-check cannot run
	// here; this case is about signing NOT regenerating released_at or digests.
	cmd.SetArgs([]string{"sign-manifest", "--manifest", outPath, "--sign-key", "@" + keyFile, "--unsafe-no-crosscheck"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("release sign-manifest: %v\n%s", err, buf.String())
	}

	mb, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}
	sigB64, err := os.ReadFile(outPath + ".sig")
	if err != nil {
		t.Fatalf("signature not written: %v", err)
	}
	sig, err := base64.StdEncoding.DecodeString(string(bytes.TrimSpace(sigB64)))
	if err != nil {
		t.Fatal(err)
	}
	m, err := release.VerifyManifest(mb, sig, pub)
	if err != nil {
		t.Fatalf("generated manifest must verify against the derived pubkey: %v", err)
	}
	if m.Version != "26.800" || m.Channel != release.ChannelSecurity || !m.Security {
		t.Fatalf("manifest fields wrong: %+v", m)
	}
	if len(m.Artifacts) != 2 { // fips + checksums.txt skipped
		t.Fatalf("want 2 platform artifacts (fips/noise skipped), got %d: %+v", len(m.Artifacts), m.Platforms())
	}
	// The recorded digest must be the REAL digest of the file on disk.
	a, ok := m.ArtifactFor("linux", "amd64")
	if !ok {
		t.Fatal("missing linux/amd64 artifact")
	}
	if err := release.VerifyArtifactSHA256(amd, a.SHA256); err != nil {
		t.Fatalf("recorded digest does not match the archive bytes: %v", err)
	}
	if m.Rollout.Percentage == nil || *m.Rollout.Percentage != 50 {
		t.Fatalf("rollout must be 50, got %+v", m.Rollout)
	}
	// Without --edition the manifest states none: the public channel manifest must stay
	// readable by binaries that refuse unknown fields.
	if m.Edition != "" || bytes.Contains(mb, []byte(`"edition"`)) {
		t.Fatalf("a manifest generated without --edition must not carry the field: %q", m.Edition)
	}

	// --edition community is signed into the bytes (REL.4b).
	cmd = newReleaseCmd()
	buf.Reset()
	cmd.SetOut(&buf)
	cmd.SetErr(&buf)
	cmd.SetArgs([]string{"manifest", "--version", "26.800", "--dir", dir, "--edition", "community",
		"--out", outPath, "--sign-key", "@" + keyFile})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("release manifest --edition: %v\n%s", err, buf.String())
	}
	if mb, err = os.ReadFile(outPath); err != nil {
		t.Fatal(err)
	}
	if sigB64, err = os.ReadFile(outPath + ".sig"); err != nil {
		t.Fatal(err)
	}
	if sig, err = base64.StdEncoding.DecodeString(string(bytes.TrimSpace(sigB64))); err != nil {
		t.Fatal(err)
	}
	if m, err = release.VerifyManifest(mb, sig, pub); err != nil || m.Edition != release.EditionCommunity {
		t.Fatalf("--edition community must be signed into the manifest, got %q, %v", m.Edition, err)
	}

	// A blank --edition is a mistake, not a request for an undeclared manifest.
	cmd = newReleaseCmd()
	cmd.SetOut(&buf)
	cmd.SetErr(&buf)
	cmd.SetArgs([]string{"manifest", "--version", "26.800", "--dir", dir, "--edition", "", "--out", outPath})
	if err := cmd.Execute(); err == nil || !strings.Contains(err.Error(), "--edition is empty") {
		t.Fatalf("a blank --edition must be refused, got %v", err)
	}
}

// TestReleaseVerifyManifestCrossChecksDigests is the M-01 regression at the CLI
// seam: the command the ceremony runbook and the protected dispatch both call must
// refuse a manifest whose digests do not match the cosign-verified checksums.txt,
// and must actually re-hash the published bytes when given --dir (the previous
// dispatch "proof" ran `upgrade --check`, which returns at IsUpToDate before any
// digest is touched — vacuous for a same-version manifest).
func TestReleaseVerifyManifestCrossChecksDigests(t *testing.T) {
	dir := t.TempDir()
	amd := []byte("published-linux-amd64-archive")
	arm := []byte("published-darwin-arm64-archive")
	writeFile := func(name string, b []byte) string {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, b, 0o644); err != nil {
			t.Fatal(err)
		}
		return p
	}
	writeFile("olivares_26.800_linux_amd64.tar.gz", amd)
	writeFile("olivares_26.800_darwin_arm64.tar.gz", arm)

	// Phase 1: CI generates the unsigned, digest-bound manifest with a freshness bound.
	manifestPath := filepath.Join(dir, "stable-manifest.json")
	run := func(args ...string) (string, error) {
		cmd := newReleaseCmd()
		var buf bytes.Buffer
		cmd.SetOut(&buf)
		cmd.SetErr(&buf)
		cmd.SetArgs(args)
		err := cmd.Execute()
		return buf.String(), err
	}
	if outStr, err := run("manifest", "--channel", "stable", "--version", "26.800",
		"--dir", dir, "--expires-in", "2160h", "--out", manifestPath); err != nil {
		t.Fatalf("release manifest: %v\n%s", err, outStr)
	}

	// The signed checksums.txt goreleaser produced, covering more files than the
	// manifest lists (FIPS variant) — extra entries must not be an error.
	sum := func(b []byte) string { s := sha256.Sum256(b); return hex.EncodeToString(s[:]) }
	checksums := filepath.Join(dir, "checksums.txt")
	good := fmt.Sprintf("%s  olivares_26.800_linux_amd64.tar.gz\n%s  olivares_26.800_darwin_arm64.tar.gz\n%s  olivares_26.800_fips_linux_amd64.tar.gz\n",
		sum(amd), sum(arm), strings.Repeat("c", 64))
	if err := os.WriteFile(checksums, []byte(good), 0o644); err != nil {
		t.Fatal(err)
	}

	// Pre-ceremony cross-check (no --sig): must pass and must re-hash the bytes.
	outStr, err := run("verify-manifest", "--manifest", manifestPath, "--checksums", checksums,
		"--dir", dir, "--expect-channel", "stable", "--expect-version", "26.800", "--require-expiry")
	if err != nil {
		t.Fatalf("a matching manifest must cross-check clean: %v\n%s", err, outStr)
	}
	for _, want := range []string{"olivares_26.800_linux_amd64.tar.gz", "re-hashed and bound", "OK:"} {
		if !strings.Contains(outStr, want) {
			t.Errorf("cross-check output must contain %q, got:\n%s", want, outStr)
		}
	}

	// THE ATTACK: the draft manifest is swapped between phase 1 and the ceremony for
	// one pointing at a malicious archive. checksums.txt is cosign-signed elsewhere
	// and cannot follow, so the cross-check must be a hard failure.
	evil := []byte("malicious-archive-the-attacker-uploaded")
	swapped := filepath.Join(dir, "swapped-manifest.json")
	mb, err := os.ReadFile(manifestPath)
	if err != nil {
		t.Fatal(err)
	}
	tampered := strings.Replace(string(mb), sum(amd), sum(evil), 1)
	if tampered == string(mb) {
		t.Fatal("test setup: the linux/amd64 digest was not present in the manifest")
	}
	if err := os.WriteFile(swapped, []byte(tampered), 0o644); err != nil {
		t.Fatal(err)
	}
	outStr, err = run("verify-manifest", "--manifest", swapped, "--checksums", checksums)
	if err == nil {
		t.Fatalf("a substituted manifest digest MUST fail the cross-check; output:\n%s", outStr)
	}
	if !strings.Contains(err.Error(), "REFUSING") || !strings.Contains(err.Error(), "Do NOT sign it") {
		t.Errorf("the failure must tell the custodian not to sign, got: %v", err)
	}

	// The generator now carries a freshness bound BY DEFAULT: the air-gap path
	// forwards --expires-in only when the operator sets it, so an unset flag used to
	// mint a signed manifest a mirror can replay forever. Producing one must now take
	// an explicit, loudly-warned opt-out.
	if outStr, err := run("manifest", "--channel", "stable", "--version", "26.800",
		"--dir", dir, "--out", filepath.Join(dir, "default-expiry.json")); err != nil {
		t.Fatalf("release manifest: %v\n%s", err, outStr)
	}
	if _, err := run("verify-manifest", "--manifest", filepath.Join(dir, "default-expiry.json"),
		"--checksums", checksums); err != nil {
		t.Errorf("the generator must carry a freshness bound with no --expires-in given: %v", err)
	}

	// A manifest without a freshness bound must be REFUSED BY DEFAULT (M-02 + the
	// inverted default): requiring the bound used to be opt-in, so a custodian who
	// merely forgot --require-expiry got `anti-freeze DISABLED` followed by `OK:` —
	// a check that fails open.
	noExpiry := filepath.Join(dir, "no-expiry-manifest.json")
	if outStr, err := run("manifest", "--channel", "stable", "--version", "26.800",
		"--dir", dir, "--no-expiry", "--out", noExpiry); err != nil {
		t.Fatalf("release manifest --no-expiry: %v\n%s", err, outStr)
	}
	if outStr, err := run("verify-manifest", "--manifest", noExpiry, "--checksums", checksums); err == nil {
		t.Errorf("a manifest with no expires must be refused BY DEFAULT (anti-freeze disabled); output:\n%s", outStr)
	}
	if _, err := run("verify-manifest", "--manifest", noExpiry, "--checksums", checksums, "--require-expiry"); err == nil {
		t.Error("the legacy --require-expiry flag must still refuse an expiry-less manifest")
	}
	if _, err := run("verify-manifest", "--manifest", noExpiry, "--checksums", checksums, "--allow-no-expiry"); err != nil {
		t.Errorf("--allow-no-expiry is the explicit opt-out and must still cross-check: %v", err)
	}

	// --dir must bind to the REAL bytes: corrupt a published archive on disk and the
	// digest cross-check (which still passes against checksums.txt) must not save it.
	if err := os.WriteFile(filepath.Join(dir, "olivares_26.800_darwin_arm64.tar.gz"), evil, 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := run("verify-manifest", "--manifest", manifestPath, "--checksums", checksums); err != nil {
		t.Fatalf("the document-level cross-check is unaffected by on-disk bytes: %v", err)
	}
	if _, err := run("verify-manifest", "--manifest", manifestPath, "--checksums", checksums, "--dir", dir); err == nil {
		t.Error("--dir must re-hash the published bytes and reject a corrupted archive")
	}
}

// TestReleaseVerifyManifestSignatureUsesEmbeddedAnchor proves the --sig path is the
// real client-side check: it verifies against the embedded OTA anchor (here supplied
// with --pubkey, since a test binary embeds none) and rejects a signature minted by
// any other key — which is exactly what the protected dispatch relies on.
func TestReleaseVerifyManifestSignatureUsesEmbeddedAnchor(t *testing.T) {
	dir := t.TempDir()
	amd := []byte("published-linux-amd64-archive")
	if err := os.WriteFile(filepath.Join(dir, "olivares_26.800_linux_amd64.tar.gz"), amd, 0o644); err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(amd)
	checksums := filepath.Join(dir, "checksums.txt")
	if err := os.WriteFile(checksums, fmt.Appendf(nil, "%s  olivares_26.800_linux_amd64.tar.gz\n", hex.EncodeToString(sum[:])), 0o644); err != nil {
		t.Fatal(err)
	}

	otaPub, otaPriv, _ := ed25519.GenerateKey(nil)
	otherPub, otherPriv, _ := ed25519.GenerateKey(nil)
	keyFile := func(name string, priv ed25519.PrivateKey) string {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(base64.StdEncoding.EncodeToString(priv.Seed())), 0o600); err != nil {
			t.Fatal(err)
		}
		return p
	}
	otaKey := keyFile("ota.key", otaPriv)
	otherKey := keyFile("other.key", otherPriv)

	manifestPath := filepath.Join(dir, "stable-manifest.json")
	run := func(args ...string) (string, error) {
		cmd := newReleaseCmd()
		var buf bytes.Buffer
		cmd.SetOut(&buf)
		cmd.SetErr(&buf)
		cmd.SetArgs(args)
		err := cmd.Execute()
		return buf.String(), err
	}
	if outStr, err := run("manifest", "--channel", "stable", "--version", "26.800",
		"--dir", dir, "--expires-in", "2160h", "--out", manifestPath); err != nil {
		t.Fatalf("release manifest: %v\n%s", err, outStr)
	}
	if outStr, err := run("sign-manifest", "--manifest", manifestPath, "--sign-key", "@"+otaKey, "--checksums", checksums); err != nil {
		t.Fatalf("sign-manifest: %v\n%s", err, outStr)
	}

	sigPath := manifestPath + ".sig"
	outStr, err := run("verify-manifest", "--manifest", manifestPath, "--sig", sigPath,
		"--pubkey", base64.StdEncoding.EncodeToString(otaPub), "--checksums", checksums,
		"--dir", dir, "--require-expiry")
	if err != nil {
		t.Fatalf("the OTA anchor must accept its own signature over bound bytes: %v\n%s", err, outStr)
	}
	if !strings.Contains(outStr, "signature: OK") {
		t.Errorf("output must report the verified signature, got:\n%s", outStr)
	}

	// A signature minted by any other key (e.g. the online license key) must not pass.
	if outStr, err := run("sign-manifest", "--manifest", manifestPath, "--sign-key", "@"+otherKey, "--checksums", checksums); err != nil {
		t.Fatalf("sign-manifest: %v\n%s", err, outStr)
	}
	if _, err := run("verify-manifest", "--manifest", manifestPath, "--sig", sigPath,
		"--pubkey", base64.StdEncoding.EncodeToString(otaPub), "--checksums", checksums); err == nil {
		t.Error("a manifest signed by a foreign key must not verify under the OTA anchor")
	}
	_ = otherPub
}

// TestReleaseVerifyManifestRefusesSubstitutedPolicy is the MAJOR-2 regression at the
// CLI seam. The digest cross-check binds the manifest to the artifacts cosign signed
// and NOTHING else: an attacker with `contents: write` who swaps the draft asset can
// leave every digest byte-identical and instead move the POLICY levers, all of which
// the custodian's signature then blesses:
//
//	min_version: 99.0   -> the whole fleet is refused every future upgrade
//	rollout.percentage: 0 -> the unattended security auto-update installs for nobody
//	rollout.start_at far  -> same suppression, by a different field
//	expires: 2999-…       -> the anti-freeze bound is re-opened permanently
//	security: false       -> a security release stops being urgent to clients
//
// Before the fix every one of these produced `OK:` — and verify-manifest did not even
// PRINT the fields, so the human review could not catch what the machine did not.
func TestReleaseVerifyManifestRefusesSubstitutedPolicy(t *testing.T) {
	dir := t.TempDir()
	amd := []byte("published-linux-amd64-archive")
	if err := os.WriteFile(filepath.Join(dir, "olivares_26.800_linux_amd64.tar.gz"), amd, 0o644); err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(amd)
	checksums := filepath.Join(dir, "checksums.txt")
	if err := os.WriteFile(checksums, fmt.Appendf(nil,
		"%s  olivares_26.800_linux_amd64.tar.gz\n%s  olivares_26.800_fips_linux_amd64.tar.gz\n",
		hex.EncodeToString(sum[:]), strings.Repeat("d", 64)), 0o644); err != nil {
		t.Fatal(err)
	}
	run := func(args ...string) (string, error) {
		cmd := newReleaseCmd()
		var buf bytes.Buffer
		cmd.SetOut(&buf)
		cmd.SetErr(&buf)
		cmd.SetArgs(args)
		err := cmd.Execute()
		return buf.String(), err
	}

	base := filepath.Join(dir, "stable-manifest.json")
	if outStr, err := run("manifest", "--channel", "stable", "--version", "26.800",
		"--dir", dir, "--expires-in", "2160h", "--out", base); err != nil {
		t.Fatalf("release manifest: %v\n%s", err, outStr)
	}
	// The honest manifest passes AND prints every policy field for human review.
	outStr, err := run("verify-manifest", "--manifest", base, "--checksums", checksums,
		"--dir", dir, "--expect-channel", "stable", "--expect-version", "26.800")
	if err != nil {
		t.Fatalf("the honest manifest must pass: %v\n%s", err, outStr)
	}
	for _, want := range []string{"POLICY THE SIGNATURE WILL COVER", "min_version:", "rollout:", "notes:", "advisories:", "expires:", "OK:"} {
		if !strings.Contains(outStr, want) {
			t.Errorf("verify-manifest must print policy field %q for the custodian to review, got:\n%s", want, outStr)
		}
	}

	mb, err := os.ReadFile(base)
	if err != nil {
		t.Fatal(err)
	}
	// Each case rewrites ONLY policy — every artifact digest stays exactly the one
	// cosign attested, so the cross-check alone still passes.
	substitute := func(t *testing.T, name, old, new string) string {
		t.Helper()
		s := strings.Replace(string(mb), old, new, 1)
		if s == string(mb) {
			t.Fatalf("test setup: %q not found in the generated manifest", old)
		}
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(s), 0o644); err != nil {
			t.Fatal(err)
		}
		return p
	}

	for _, tc := range []struct {
		name, old, new, wantIn string
	}{
		{
			// The fleet-wide kill switch: nobody can ever satisfy min_version 99.0,
			// so cmd_upgrade.go's MinTooOld gate refuses every node, forever.
			name:   "min_version-locks-the-fleet",
			old:    "\"version\": \"26.800\",",
			new:    "\"version\": \"26.800\",\n  \"min_version\": \"99.0\",",
			wantIn: "permanently blocks the whole fleet",
		},
		{
			// A channel relabelled `security` that carries neither the security flag
			// nor an advisory: the shape of a manifest hand-edited to ride the
			// out-of-band lane while saying nothing about what it fixes.
			name:   "security-channel-without-the-security-flag",
			old:    "\"channel\": \"stable\",",
			new:    "\"channel\": \"security\",",
			wantIn: "security is false",
		},
		{
			// Free text is shown to every operator and verified by nothing.
			name:   "notes-carrying-a-plaintext-url",
			old:    "\"released_at\":",
			new:    "\"notes\": \"urgent: fetch the fix from http://olivares-updates.example\",\n  \"released_at\":",
			wantIn: "",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			p := substitute(t, tc.name+".json", tc.old, tc.new)
			out, err := run("verify-manifest", "--manifest", p, "--checksums", checksums, "--dir", dir)
			if tc.wantIn == "" {
				// Not fatal — legitimate publishers do write notes. But it must be
				// surfaced loudly, because nothing else in the chain looks at it.
				if err != nil {
					t.Fatalf("notes are legitimate and must not fail closed: %v\n%s", err, out)
				}
				for _, want := range []string{"verified by NOTHING", "http:// URL"} {
					if !strings.Contains(out, want) {
						t.Errorf("operator-visible free text must be flagged for review (%q), got:\n%s", want, out)
					}
				}
				return
			}
			if err == nil {
				t.Fatalf("a substituted policy must be REFUSED even though every digest is honest; output:\n%s", out)
			}
			if !strings.Contains(err.Error(), "REFUSING") || !strings.Contains(err.Error(), "Do NOT sign") {
				t.Errorf("the failure must tell the custodian not to sign, got: %v", err)
			}
			if !strings.Contains(err.Error(), tc.wantIn) {
				t.Errorf("the failure must explain the lever that was moved (%q), got: %v", tc.wantIn, err)
			}
		})
	}

	// expires pushed far into the future: the anti-freeze bound is present, valid,
	// not stale — and useless. Only an upper bound catches it.
	t.Run("expires-reopens-antifreeze", func(t *testing.T) {
		far := time.Now().UTC().Add(500 * 24 * time.Hour).Format(time.RFC3339)
		var m map[string]any
		if err := json.Unmarshal(mb, &m); err != nil {
			t.Fatal(err)
		}
		m["expires"] = far
		b, _ := json.MarshalIndent(m, "", "  ")
		p := filepath.Join(dir, "far-expiry.json")
		if err := os.WriteFile(p, append(b, '\n'), 0o644); err != nil {
			t.Fatal(err)
		}
		out, err := run("verify-manifest", "--manifest", p, "--checksums", checksums, "--dir", dir)
		if err == nil {
			t.Fatalf("an expires far beyond the bound must be REFUSED; output:\n%s", out)
		}
		if !strings.Contains(err.Error(), "anti-freeze") && !strings.Contains(err.Error(), "freeze") {
			t.Errorf("the failure must name the anti-freeze defense, got: %v", err)
		}
		// The documented ceiling is a flag, not a hardcode: an operator who genuinely
		// wants a longer window says so on the record.
		if _, err := run("verify-manifest", "--manifest", p, "--checksums", checksums,
			"--dir", dir, "--max-expires-in", "13000h"); err != nil {
			t.Errorf("--max-expires-in must be the explicit, audited escape hatch: %v", err)
		}
	})

	// A SECURITY manifest whose rollout is paused reaches nobody — the one thing the
	// out-of-band channel exists to prevent.
	t.Run("paused-security-rollout", func(t *testing.T) {
		secPath := filepath.Join(dir, "security-manifest.json")
		if outStr, err := run("manifest", "--channel", "security", "--version", "26.800",
			"--dir", dir, "--expires-in", "2160h", "--advisory", "GHSA-xxxx-yyyy-zzzz",
			"--rollout", "0", "--out", secPath); err != nil {
			t.Fatalf("release manifest: %v\n%s", err, outStr)
		}
		out, err := run("verify-manifest", "--manifest", secPath, "--checksums", checksums,
			"--dir", dir, "--expect-channel", "security")
		if err == nil {
			t.Fatalf("a paused SECURITY rollout must be REFUSED; output:\n%s", out)
		}
		if !strings.Contains(err.Error(), "rollout.percentage is 0") {
			t.Errorf("the failure must name the suppressed rollout, got: %v", err)
		}
		if _, err := run("verify-manifest", "--manifest", secPath, "--checksums", checksums,
			"--dir", dir, "--expect-channel", "security", "--allow-paused-rollout"); err != nil {
			t.Errorf("--allow-paused-rollout is the deliberate opt-in and must pass: %v", err)
		}
	})

	// The manifest may not re-point a platform at the FIPS archive: its digest IS in
	// the cosign-signed checksums.txt, so the digest cross-check alone waves it through.
	t.Run("platform-remapped-to-fips-variant", func(t *testing.T) {
		var m map[string]any
		if err := json.Unmarshal(mb, &m); err != nil {
			t.Fatal(err)
		}
		arts, _ := m["artifacts"].([]any)
		a0, _ := arts[0].(map[string]any)
		a0["filename"] = "olivares_26.800_fips_linux_amd64.tar.gz"
		a0["sha256"] = strings.Repeat("d", 64) // the REAL digest of the FIPS archive
		b, _ := json.MarshalIndent(m, "", "  ")
		p := filepath.Join(dir, "fips-remap.json")
		if err := os.WriteFile(p, append(b, '\n'), 0o644); err != nil {
			t.Fatal(err)
		}
		out, err := run("verify-manifest", "--manifest", p, "--checksums", checksums)
		if err == nil {
			t.Fatalf("remapping linux/amd64 onto the FIPS archive must be REFUSED; output:\n%s", out)
		}
		if !strings.Contains(err.Error(), "olivares_26.800_linux_amd64.tar.gz") {
			t.Errorf("the failure must name the archive that platform must carry, got: %v", err)
		}
	})
}

// TestReleaseSignManifestRefusesToSignBlind pins the belt on the SIGNING command
// itself. The ceremony's protection used to live only in the runbook: the custodian
// was told to cross-check, then invoked a sign command that would happily sign any
// JSON that parsed. Under incident pressure — exactly when a substituted draft asset
// is most likely and the runbook step is most likely skipped — that is the whole
// trust anchor signing an attacker's digests. The signer now re-runs the cross-check
// itself, so skipping the manual step cannot produce a signature.
func TestReleaseSignManifestRefusesToSignBlind(t *testing.T) {
	dir := t.TempDir()
	archive := []byte("published-linux-amd64-archive")
	if err := os.WriteFile(filepath.Join(dir, "olivares_26.800_linux_amd64.tar.gz"), archive, 0o644); err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(archive)
	checksums := filepath.Join(dir, "checksums.txt")
	if err := os.WriteFile(checksums, fmt.Appendf(nil, "%s  olivares_26.800_linux_amd64.tar.gz\n", hex.EncodeToString(sum[:])), 0o644); err != nil {
		t.Fatal(err)
	}
	_, otaPriv, _ := ed25519.GenerateKey(nil)
	otaKey := filepath.Join(dir, "ota.key")
	if err := os.WriteFile(otaKey, []byte(base64.StdEncoding.EncodeToString(otaPriv.Seed())), 0o600); err != nil {
		t.Fatal(err)
	}
	manifestPath := filepath.Join(dir, "stable-manifest.json")
	run := func(args ...string) (string, error) {
		cmd := newReleaseCmd()
		var buf bytes.Buffer
		cmd.SetOut(&buf)
		cmd.SetErr(&buf)
		cmd.SetArgs(args)
		return buf.String(), cmd.Execute()
	}
	if out, err := run("manifest", "--channel", "stable", "--version", "26.800",
		"--dir", dir, "--expires-in", "2160h", "--out", manifestPath); err != nil {
		t.Fatalf("release manifest: %v\n%s", err, out)
	}

	// 1) No --checksums at all: the signer refuses rather than signing blind.
	if _, err := run("sign-manifest", "--manifest", manifestPath, "--sign-key", "@"+otaKey); err == nil {
		t.Fatal("sign-manifest must refuse to sign without --checksums")
	}

	// 2) THE ATTACK: the draft manifest is substituted after checksums.txt was
	//    signed. Digests no longer describe the published bytes; the signer must
	//    refuse even though the JSON is perfectly valid.
	mb, err := os.ReadFile(manifestPath)
	if err != nil {
		t.Fatal(err)
	}
	forged := strings.Replace(string(mb), hex.EncodeToString(sum[:]),
		strings.Repeat("a", len(hex.EncodeToString(sum[:]))), 1)
	if forged == string(mb) {
		t.Fatal("test setup: the digest was not substituted")
	}
	forgedPath := filepath.Join(dir, "forged-manifest.json")
	if err := os.WriteFile(forgedPath, []byte(forged), 0o644); err != nil {
		t.Fatal(err)
	}
	out, err := run("sign-manifest", "--manifest", forgedPath, "--sign-key", "@"+otaKey, "--checksums", checksums)
	if err == nil {
		t.Fatal("sign-manifest must refuse a manifest whose digests contradict the signed checksums")
	}
	if !strings.Contains(err.Error()+out, "REFUSING to sign") {
		t.Errorf("the refusal must name the substitution, got: %v\n%s", err, out)
	}
	if _, statErr := os.Stat(forgedPath + ".sig"); statErr == nil {
		t.Error("no signature may be written for a refused manifest")
	}
}

func TestReleaseManifestRejectsNonReleaseIdentities(t *testing.T) {
	for _, flag := range []string{"--version", "--min-version"} {
		for _, value := range []string{"1.0", "1.1", "1.10", "1.299", "2.0", "dev", "vdev", "v", "1.0.1", "26.10.2", "v1.0", "1.0-rc.1", "1.0+meta", " 1.0", "1.0\n", " "} {
			t.Run(flag+"/"+value, func(t *testing.T) {
				dir := t.TempDir()
				archiveVersion := "1.0"
				if flag == "--version" {
					archiveVersion = value
					// The old producer stripped v before looking for archives.
					archiveVersion = strings.TrimPrefix(strings.TrimSpace(archiveVersion), "v")
				}
				archive := filepath.Join(dir, "olivares_"+archiveVersion+"_linux_amd64.tar.gz")
				if err := os.WriteFile(archive, []byte("grammar fixture archive"), 0o644); err != nil {
					t.Fatal(err)
				}
				out := filepath.Join(dir, "manifest.json")
				args := []string{"manifest", "--version", "1.0", "--dir", dir, "--out", out}
				args = append(args, flag, value)
				cmd := newReleaseCmd()
				var buf bytes.Buffer
				cmd.SetOut(&buf)
				cmd.SetErr(&buf)
				cmd.SetArgs(args)
				err := cmd.Execute()
				wantValid := value == "1.0" || value == "1.1" || value == "1.10" || value == "1.299" || value == "2.0"
				if (err == nil) != wantValid {
					t.Fatalf("release manifest %s=%q: %v; want valid=%t; %s", flag, value, err, wantValid, buf.String())
				}
				if !wantValid {
					if _, statErr := os.Stat(out); !os.IsNotExist(statErr) {
						t.Fatalf("invalid identity wrote a manifest: %v", statErr)
					}
					return
				}
				b, err := os.ReadFile(out)
				if err != nil {
					t.Fatal(err)
				}
				m, err := release.ParseManifest(b)
				if err != nil {
					t.Fatal(err)
				}
				if (flag == "--version" && m.Version != value) || (flag == "--min-version" && m.MinVersion != value) {
					t.Fatalf("producer changed the release identity: %+v", m)
				}
			})
		}
	}
}

func TestReleaseVerifyManifestExpectedVersion(t *testing.T) {
	dir := t.TempDir()
	archiveName := "olivares_1.0_linux_amd64.tar.gz"
	archive := []byte("expected-version fixture archive")
	if err := os.WriteFile(filepath.Join(dir, archiveName), archive, 0o644); err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(archive)
	checksums := filepath.Join(dir, "checksums.txt")
	if err := os.WriteFile(checksums, fmt.Appendf(nil, "%x  %s\n", sum, archiveName), 0o644); err != nil {
		t.Fatal(err)
	}
	manifest := filepath.Join(dir, "manifest.json")
	run := func(args ...string) (string, error) {
		cmd := newReleaseCmd()
		var buf bytes.Buffer
		cmd.SetOut(&buf)
		cmd.SetErr(&buf)
		cmd.SetArgs(args)
		err := cmd.Execute()
		return buf.String(), err
	}
	if out, err := run("manifest", "--version", "1.0", "--dir", dir, "--out", manifest); err != nil {
		t.Fatalf("generate valid manifest: %v\n%s", err, out)
	}
	for _, tc := range []struct {
		name, value, wantError string
		omitted                bool
	}{
		{name: "omitted", omitted: true},
		{name: "matching", value: "1.0"},
		{name: "mismatched", value: "1.1", wantError: `manifest version is "1.0", expected "1.1"`},
		{name: "exact-identity", value: "01.0", wantError: `manifest version is "1.0", expected "01.0"`},
		{name: "empty", value: "", wantError: "--expect-version"},
		{name: "prefix", value: "v1.0", wantError: "--expect-version"},
		{name: "prefix-only", value: "v", wantError: "--expect-version"},
		{name: "surrounding-spaces", value: " 1.0 ", wantError: "--expect-version"},
		{name: "whitespace-only", value: " \t\n", wantError: "--expect-version"},
		{name: "trailing-newline", value: "1.0\n", wantError: "--expect-version"},
		{name: "unstamped", value: "dev", wantError: "--expect-version"},
		{name: "prefixed-unstamped", value: "vdev", wantError: "--expect-version"},
		{name: "patch", value: "1.0.1", wantError: "--expect-version"},
		{name: "calver", value: "26.10.2", wantError: "--expect-version"},
		{name: "prerelease", value: "1.0-rc.1", wantError: "--expect-version"},
		{name: "rehearsal", value: "0.0-rehearsal.1", wantError: "--expect-version"},
		{name: "metadata", value: "1.0+meta", wantError: "--expect-version"},
		{name: "missing-minor", value: "1", wantError: "--expect-version"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			args := []string{"verify-manifest", "--manifest", manifest, "--checksums", checksums, "--dir", dir}
			if !tc.omitted {
				args = append(args, "--expect-version", tc.value)
			}
			out, err := run(args...)
			if tc.wantError != "" {
				if err == nil || !strings.Contains(err.Error(), "REFUSING") || !strings.Contains(err.Error(), tc.wantError) {
					t.Fatalf("--expect-version=%q: want refusal containing %q, got %v\n%s", tc.value, tc.wantError, err, out)
				}
				if strings.Contains(out, "OK:") {
					t.Fatalf("refused expectation printed a success verdict:\n%s", out)
				}
				return
			}
			if err != nil || !strings.Contains(out, "OK: stable manifest for 1.0") || !strings.Contains(out, "re-hashed and bound") {
				t.Fatalf("valid expectation must verify the manifest and archive: %v\n%s", err, out)
			}
		})
	}
}

func TestReleaseVerifyManifestExpectedVersionHelp(t *testing.T) {
	usage := newReleaseVerifyManifestCmd().Flags().Lookup("expect-version").Usage
	if !strings.Contains(usage, "MAJOR.MINOR") || strings.Contains(usage, "leading v is ignored") {
		t.Fatalf("--expect-version must describe the bare release grammar: %q", usage)
	}
}
