// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.

// Code generated by scripts/config-env-docs; DO NOT EDIT.

package main

const configEnvironmentHelp = "Environment variables (process values override activation defaults):\n" +
	"  OLIVARES_ACTOR\n" +
	"    Default `--actor` for the decision-bearing eventing verbs, so a scripted change still records who made it.\n" +
	"  OLIVARES_ADMIN_DSN\n" +
	"    Privileged connection string the Kubernetes operator uses for schema migration, separate from the least-privilege runtime role.\n" +
	"  OLIVARES_AGENTCORE_EXPORT_CONFIG\n" +
	"    Path to the JSON configuration of the AgentCore usage export.\n" +
	"  OLIVARES_AGENT_GATEWAY_CONFIG\n" +
	"    Path to the JSON configuration of the MCP agent gateway.\n" +
	"  OLIVARES_ALLOW_CLEARTEXT\n" +
	"    Dangerous opt-in: lets a request carrying a credential reach a NON-loopback host over plain HTTP, for surfaces with no --allow-cleartext flag of their own.\n" +
	"  OLIVARES_APPROVAL_BRIDGE_CONFIG\n" +
	"    Path to the JSON configuration of the bridge that routes approvals to an external system.\n" +
	"  OLIVARES_AUDIT_ARCHIVE_*\n" +
	"    Family prefix for the audit archive settings listed above.\n" +
	"  OLIVARES_AUDIT_ARCHIVE_CONFIG\n" +
	"    Path to the JSON settings for the Business Regulated Operations `s3archive` sink. Secret-bearing, so it is a file rather than a value.\n" +
	"  OLIVARES_AUDIT_ARCHIVE_DIR\n" +
	"    Root directory for the `dir` archive sink.\n" +
	"  OLIVARES_AUDIT_ARCHIVE_INTERVAL\n" +
	"    How often sealed audit segments are archived, as a Go duration. Default: 24h.\n" +
	"  OLIVARES_AUDIT_ARCHIVE_RETAIN_DAYS\n" +
	"    How long archived audit segments are retained, in days. Default: 2555.\n" +
	"  OLIVARES_AUDIT_ARCHIVE_SEGMENT_EVENTS\n" +
	"    How many events a sealed archive segment holds before the next one is started.\n" +
	"  OLIVARES_AUDIT_ARCHIVE_SINK\n" +
	"    Where sealed audit segments are archived: unset for off, `dir` for a local directory, `s3archive` for object storage in Business Regulated Operations.\n" +
	"  OLIVARES_AUDIT_LEGALHOLD_INTERVAL\n" +
	"    How often the long-horizon legal-hold sweep runs, as a Go duration.\n" +
	"  OLIVARES_AUDIT_LEGALHOLD_RECONCILE\n" +
	"    Boolean switch, not a file path, for the long-horizon legal-hold reconciler that places object-lock legal holds on the archived audit segments of tenants under an active legal hold. Read only by the Business edition (Regulated Operations), when the engine starts; a change takes effect after a restart. Only a value `strconv.ParseBool` accepts as true, such as `true` or `1`, turns it on; unset, false and unparsable values leave it off without an error. It also stays off unless the audit archive is configured on a sink that can place object-lock legal holds.\n" +
	"  OLIVARES_AUDIT_META_BLINDING\n" +
	"    Whether audit metadata commitments are written blinded, and how strictly that is required.\n" +
	"  OLIVARES_AUDIT_SIGNING_KEY\n" +
	"    Audit checkpoint signing key, inline. Prefer the file form so the key never sits in a process environment.\n" +
	"  OLIVARES_AUDIT_SIGNING_KEY_FILE\n" +
	"    Path to the audit checkpoint signing key. This is the operator-held form.\n" +
	"  OLIVARES_AUDIT_SIGNING_KEY_WRAPPED_FILE\n" +
	"    Path to the audit signing key wrapped by a key management service, unwrapped at boot.\n" +
	"  OLIVARES_AUDIT_SPOOL_MAX_BYTES\n" +
	"    Upper bound on the on-disk audit spool before the full-spool rule applies.\n" +
	"  OLIVARES_AUDIT_SPOOL_ON_FULL\n" +
	"    What happens when the audit spool is full: the deny-closed posture refuses the write rather than dropping the record.\n" +
	"  OLIVARES_AUTHZEN_ALLOWED_CIDRS\n" +
	"    Comma-separated CIDR ranges allowed to reach the AuthZEN endpoints. Unset leaves the endpoint reachable wherever the listener is.\n" +
	"  OLIVARES_AUTHZEN_DISABLED\n" +
	"    Set to a true value to turn the AuthZEN decision endpoint off.\n" +
	"  OLIVARES_AUTHZEN_EXPORT_DISABLED\n" +
	"    Set to a true value to turn the AuthZEN export endpoint off.\n" +
	"  OLIVARES_AUTHZEN_SEARCH_DISABLED\n" +
	"    Set to a true value to turn the AuthZEN search endpoints off while leaving decisions on.\n" +
	"  OLIVARES_BASE_URL\n" +
	"    Public base URL of this engine, used where an absolute link back to it has to be produced.\n" +
	"  OLIVARES_BUS_CONFIG\n" +
	"    Path to the JSON configuration of the message bus the engine publishes on.\n" +
	"  OLIVARES_CAEP_TRANSMITTER_CONFIG\n" +
	"    Path to the JSON configuration of the CAEP transmitter that pushes shared-signal events.\n" +
	"  OLIVARES_CATALOG_SIGNING_KEY\n" +
	"    Catalog signing key, inline. Prefer the file form.\n" +
	"  OLIVARES_CATALOG_SIGNING_KEY_FILE\n" +
	"    Path to the catalog signing key.\n" +
	"  OLIVARES_CATALOG_SIGNING_KEY_WRAPPED_FILE\n" +
	"    Path to the catalog signing key wrapped by a key management service.\n" +
	"  OLIVARES_CIRCUIT_BREAKER_CONFIG\n" +
	"    Boolean switch, not a file path despite the `_CONFIG` suffix, for the runtime circuit breaker; its per-tenant rules are not set here. Read only by the Business edition (AI Runtime Security), when the engine starts; a change takes effect after a restart. Unset or a `strconv.ParseBool` false value leaves the breaker off. A value that is not a boolean is logged as an error and also leaves it off. A true value turns it on when module data is available; otherwise a warning is logged and it stays off.\n" +
	"  OLIVARES_CLAUDE_ADMIN_ACTUATOR_CONFIG\n" +
	"    Path to the JSON configuration of the administrative actuator that applies changes at the model provider.\n" +
	"  OLIVARES_CLAUDE_ADMIN_KEY\n" +
	"    Administrative API key used to read identity posture from the model provider.\n" +
	"  OLIVARES_CLAUDE_ERASER_CONFIG\n" +
	"    Path to the JSON configuration of the erasure actuator that carries out deletion requests.\n" +
	"  OLIVARES_CLAUDE_FILES_CONFIG\n" +
	"    Path to the JSON configuration of the provider file inventory scan.\n" +
	"  OLIVARES_CLAUDE_INFERENCE_KEY\n" +
	"    API key the engine uses for its own inference calls. Unset leaves the inference-backed features off.\n" +
	"  OLIVARES_CLAUDE_WORKSPACE_ID\n" +
	"    Workspace whose identity posture is read, when the administrative key spans several.\n" +
	"  OLIVARES_CLI_CONFIG\n" +
	"    Path to the CLI configuration file, replacing the default per-user location. Used by hermetic automation.\n" +
	"  OLIVARES_CLI_TRAMPOLINE\n" +
	"    Set to `1` inside a re-executed child process so the binary runs the requested subcommand instead of the outer test harness.\n" +
	"  OLIVARES_CODEX_HOOK_*\n" +
	"    Family prefix for the Codex hook client and server settings listed above.\n" +
	"  OLIVARES_CODEX_HOOK_ACCOUNT\n" +
	"    Account the Codex hook client reports.\n" +
	"  OLIVARES_CODEX_HOOK_AGENT\n" +
	"    Agent identity the Codex hook client reports.\n" +
	"  OLIVARES_CODEX_HOOK_ORG\n" +
	"    Organization the Codex hook client reports.\n" +
	"  OLIVARES_CODEX_HOOK_PEP_CONFIG\n" +
	"    Path to the JSON configuration of the Codex hook enforcement point server.\n" +
	"  OLIVARES_CODEX_HOOK_TENANT\n" +
	"    Tenant the Codex hook client reports.\n" +
	"  OLIVARES_CODEX_HOOK_TOKEN\n" +
	"    Token the Codex hook client presents to the enforcement point.\n" +
	"  OLIVARES_CODEX_HOOK_URL\n" +
	"    Base URL of the enforcement point the Codex hook client calls.\n" +
	"  OLIVARES_COMMUNICATION_ACTIVATION\n" +
	"    REQUESTED K3 communication activation (`on` or `off`; default off), parsed at boot by cmd/olivares/communicationcomposition.go. `on` binds the local outbox pump witness and enables the dual runtime credential posture before the first leadership election; whether a communication credential can actually be minted is decided per launch from the EFFECTIVE readiness conjunction (store proof, sealer, directory resolver, permissions, pump), never from this flag alone. `on` needs both keyring files below; when either is not declared, cannot be opened or does not load, boot continues with K3 OFF and the cause visible (composition log, pump lane verdict `custody_unavailable`, non-effective readiness) while core, K1 and K2 serve. Only an unrecognized value is a configuration error.\n" +
	"  OLIVARES_COMMUNICATION_CONTENT_KEYRING_FILE\n" +
	"    Path to the JSON keyring the communication content sealer loads at boot (cmd/olivares/boot.go). Secret-bearing, so it is a file rather than a value: sealed message bodies are verified against the keys it carries, and an engine started without it cannot open content sealed by a peer that had one.\n" +
	"  OLIVARES_COMMUNICATION_CURSOR_KEYRING_FILE\n" +
	"    Path to the JSON keyring (`olivares.communication-cursor-keyring.v1`) that signs and verifies inbox cursor navigation tokens, loaded at boot through the same custody mechanism as the content keyring (cmd/olivares/communicationcursorkeyring.go). Secret-bearing, so it is a file rather than a value; a rotated-out key marked `retired_at` keeps verifying for the token retention window and is dropped afterwards, and a restart never mints a fresh key.\n" +
	"  OLIVARES_COMMUNICATION_TOKEN\n" +
	"    The session's own communication credential, injected by the session launcher and read by message commands. Reserved on the launch path; operators must not supply it. Its value is always redacted.\n" +
	"  OLIVARES_COMPUTER_USE_CONFIG\n" +
	"    Path to the JSON policy file of the computer-use gate. Read only by the Business edition (AI Runtime Security). Unset leaves the gate off; a file that cannot be read or parsed makes it deny all computer use until the file is fixed and the engine is restarted.\n" +
	"  OLIVARES_CONFIG_STRICT\n" +
	"    Set to `1` to make `olivares config effective` and `config validate` reject any unrecognized `OLIVARES_*` key.\n" +
	"  OLIVARES_CONTENT_FIREWALL_CONFIG\n" +
	"    Path to the JSON policy file of the content firewall that inspects inference traffic in the inline proxy. Read only by the Business edition (AI Runtime Security). Unset leaves that inspection off; a file that cannot be read or parsed makes the firewall deny every request it inspects until the file is fixed and the engine is restarted.\n" +
	"  OLIVARES_CONTEXT_MAX_TOKENS\n" +
	"    Upper bound on the context a governed session may assemble, in tokens.\n" +
	"  OLIVARES_CONTEXT_STRATEGY\n" +
	"    Which strategy assembles a governed session's context when the bound is reached.\n" +
	"  OLIVARES_CREDENTIAL_MINTER_CONFIG\n" +
	"    Path to the JSON configuration of the per-server upstream credential minter (RFC 8693 token exchange) of the MCP gateway. Secret-bearing, so it is a file rather than a value. Read by the Enterprise edition when the engine starts and builds the gateway for an upstream URL. Unset keeps the static upstream credential; a file that cannot be read or parsed denies every upstream credential until the file is fixed and the engine is restarted.\n" +
	"  OLIVARES_DATA_DIR\n" +
	"    Data directory used when `--data-dir` is not given: audit signing key, TLS material and, for SQLite, the store file.\n" +
	"  OLIVARES_DB_MAX_CONNS\n" +
	"    Upper bound on pooled database connections. Unset leaves the driver default.\n" +
	"  OLIVARES_DEPLOY_EXECUTOR_CONFIG\n" +
	"    Path to the JSON configuration of the executor that applies deployment changes.\n" +
	"  OLIVARES_DR_KEK_FILE\n" +
	"    Path to a raw 32-byte key-encryption key for backups, for the path where a key management service does the unwrapping.\n" +
	"  OLIVARES_DR_OFFSITE_*\n" +
	"    Family prefix for the offsite replication settings listed above.\n" +
	"  OLIVARES_DR_OFFSITE_ACCESS_KEY_ID_FILE\n" +
	"    Path to the file holding the offsite access key id, so the credential stays out of the environment.\n" +
	"  OLIVARES_DR_OFFSITE_BUCKET\n" +
	"    Offsite bucket for disaster-recovery bundles. Setting it turns offsite replication on.\n" +
	"  OLIVARES_DR_OFFSITE_ENDPOINT\n" +
	"    S3-compatible endpoint for offsite replication. Unset means AWS S3 in the configured region.\n" +
	"  OLIVARES_DR_OFFSITE_PREFIX\n" +
	"    Key prefix for bundles inside the offsite bucket.\n" +
	"  OLIVARES_DR_OFFSITE_REGION\n" +
	"    Region for offsite replication.\n" +
	"  OLIVARES_DR_OFFSITE_SECRET_ACCESS_KEY_FILE\n" +
	"    Path to the file holding the offsite secret access key.\n" +
	"  OLIVARES_DR_OFFSITE_SESSION_TOKEN_FILE\n" +
	"    Path to the file holding an offsite session token, for temporary credentials.\n" +
	"  OLIVARES_DR_PASSPHRASE_FILE\n" +
	"    Path to the backup passphrase file, from which the backup key-encryption key is derived.\n" +
	"  OLIVARES_DR_SCHEDULE_INTERVAL\n" +
	"    How often the scheduled backup runs, as a Go duration.\n" +
	"  OLIVARES_DSN\n" +
	"    Store connection string injected by the Kubernetes operator into the engine it manages.\n" +
	"  OLIVARES_DURABLE_BUS_CONFIG\n" +
	"    Path to the JSON configuration of the durable bus, for at-least-once delivery across replicas.\n" +
	"  OLIVARES_ELICITATION_MEDIATOR_CONFIG\n" +
	"    Path to the JSON policy file of the MCP elicitation mediator. Read only by the Business edition (AI Runtime Security). Unset leaves mediation off; a file that cannot be read or parsed makes the mediator deny every elicitation until the file is fixed and the engine is restarted.\n" +
	"  OLIVARES_EMBEDDINGS_*\n" +
	"    Family prefix from which the per-provider embeddings keys are built, by appending the provider name and then the setting.\n" +
	"  OLIVARES_EMBEDDINGS_BASE_URL\n" +
	"    Endpoint the openai-compatible embeddings provider is called at.\n" +
	"  OLIVARES_EMBEDDINGS_DIM\n" +
	"    Vector dimension the openai-compatible provider returns, which has to match the index.\n" +
	"  OLIVARES_EMBEDDINGS_GEO\n" +
	"    Region or data-residency hint sent to the openai-compatible provider.\n" +
	"  OLIVARES_EMBEDDINGS_KEY\n" +
	"    Api key for the openai-compatible embeddings provider.\n" +
	"  OLIVARES_EMBEDDINGS_MODEL\n" +
	"    Embedding model requested from the openai-compatible provider.\n" +
	"  OLIVARES_EMBEDDINGS_OPENAI_BASE_URL\n" +
	"    Endpoint the openai embeddings provider is called at.\n" +
	"  OLIVARES_EMBEDDINGS_OPENAI_COMPAT_BASE_URL\n" +
	"    Endpoint the openai-compatible embeddings provider is called at.\n" +
	"  OLIVARES_EMBEDDINGS_OPENAI_COMPAT_DIM\n" +
	"    Vector dimension the openai-compatible provider returns, which has to match the index.\n" +
	"  OLIVARES_EMBEDDINGS_OPENAI_COMPAT_GEO\n" +
	"    Region or data-residency hint sent to the openai-compatible provider.\n" +
	"  OLIVARES_EMBEDDINGS_OPENAI_COMPAT_KEY\n" +
	"    Api key for the openai-compatible embeddings provider.\n" +
	"  OLIVARES_EMBEDDINGS_OPENAI_COMPAT_MODEL\n" +
	"    Embedding model requested from the openai-compatible provider.\n" +
	"  OLIVARES_EMBEDDINGS_OPENAI_DIM\n" +
	"    Vector dimension the openai provider returns, which has to match the index.\n" +
	"  OLIVARES_EMBEDDINGS_OPENAI_GEO\n" +
	"    Region or data-residency hint sent to the openai provider.\n" +
	"  OLIVARES_EMBEDDINGS_OPENAI_KEY\n" +
	"    Api key for the openai embeddings provider.\n" +
	"  OLIVARES_EMBEDDINGS_OPENAI_MODEL\n" +
	"    Embedding model requested from the openai provider.\n" +
	"  OLIVARES_EMBEDDINGS_PROVIDER\n" +
	"    Which embeddings provider is used, pinning one instead of taking the first that is configured.\n" +
	"  OLIVARES_EMBEDDINGS_REQUIRE\n" +
	"    Set to a true value to make a missing or unusable embeddings provider a refusal rather than a degraded index.\n" +
	"  OLIVARES_EMBEDDINGS_SELF_HOSTED_BASE_URL\n" +
	"    Endpoint the self-hosted embeddings provider is called at.\n" +
	"  OLIVARES_EMBEDDINGS_SELF_HOSTED_DIM\n" +
	"    Vector dimension the self-hosted provider returns, which has to match the index.\n" +
	"  OLIVARES_EMBEDDINGS_SELF_HOSTED_GEO\n" +
	"    Region or data-residency hint sent to the self-hosted provider.\n" +
	"  OLIVARES_EMBEDDINGS_SELF_HOSTED_KEY\n" +
	"    Api key for the self-hosted embeddings provider.\n" +
	"  OLIVARES_EMBEDDINGS_SELF_HOSTED_MODEL\n" +
	"    Embedding model requested from the self-hosted provider.\n" +
	"  OLIVARES_EMBEDDINGS_VOYAGE_BASE_URL\n" +
	"    Endpoint the voyage embeddings provider is called at.\n" +
	"  OLIVARES_EMBEDDINGS_VOYAGE_DIM\n" +
	"    Vector dimension the voyage provider returns, which has to match the index.\n" +
	"  OLIVARES_EMBEDDINGS_VOYAGE_GEO\n" +
	"    Region or data-residency hint sent to the voyage provider.\n" +
	"  OLIVARES_EMBEDDINGS_VOYAGE_KEY\n" +
	"    Api key for the voyage embeddings provider.\n" +
	"  OLIVARES_EMBEDDINGS_VOYAGE_MODEL\n" +
	"    Embedding model requested from the voyage provider.\n" +
	"  OLIVARES_EVALS_MONITOR_WINDOW\n" +
	"    Time window the evaluation monitor scores, as a Go duration.\n" +
	"  OLIVARES_EVENTING_ALLOW_LOOPBACK\n" +
	"    Set to a true value to allow loopback destinations. Single-box development only, because the default refusal is what blocks server-side request forgery.\n" +
	"  OLIVARES_EVENTING_DISPATCH_INTERVAL\n" +
	"    How often queued events are dispatched, as a Go duration. `0` disables the pump. Default: 15s.\n" +
	"  OLIVARES_EVENTING_EGRESS_POLICY\n" +
	"    Path to the JSON policy that decides which destinations outbound events may reach. A policy that does not parse leaves eventing unwired rather than open.\n" +
	"  OLIVARES_EVENTING_RETENTION\n" +
	"    How long delivered events are kept for replay, as a Go duration. Default: 168h.\n" +
	"  OLIVARES_EVENTING_SECRET_KEY\n" +
	"    Key that encrypts eventing subscription signing secrets at rest.\n" +
	"  OLIVARES_EXECUTION_ENVIRONMENT_ID\n" +
	"    Explicit execution-environment reference for this node, read at boot by cmd/olivares/providerprofiles.go. Unset, the engine generates one identity once into `execution-environment-id` in the data directory (0600, atomic exclusive create) and reuses it; set, the value must be 1..256 printable bytes with no whitespace, colon or vertical bar, and a malformed value refuses boot instead of degrading in silence. It is REQUIRED on a topology with only shared state and no node-local data directory: there, without it, profiled session launches stay deny-closed.\n" +
	"  OLIVARES_EXTRA_ARGS\n" +
	"    Extra `serve` arguments appended by the packaged service unit, for operators who configure the daemon through an environment file.\n" +
	"  OLIVARES_FINOPS_ADMISSION_LEGACY_WRITERS_STOPPED_AT\n" +
	"    Instant every writer of the earlier FinOps admission build stopped, as an RFC 3339 time in UTC ending in `Z`. Read once at startup. Recovery retires a claim those writers left, but only once five minutes have passed since this instant and only while no row they left is dated later; empty, the default, or text that is not such an instant retires none.\n" +
	"  OLIVARES_GITPUBLISH_SWEEP_INTERVAL\n" +
	"    How often the Git publication sweep settles stale dispatches and re-observes uncertain publications, as a Go duration. `0` disables it. Default: 1m.\n" +
	"  OLIVARES_GROK_HOOK_*\n" +
	"    Family prefix for the Grok Build hook client and server settings listed above.\n" +
	"  OLIVARES_GROK_HOOK_ACCOUNT\n" +
	"    Account the Grok Build hook client reports.\n" +
	"  OLIVARES_GROK_HOOK_AGENT\n" +
	"    Agent identity the Grok Build hook client reports.\n" +
	"  OLIVARES_GROK_HOOK_ORG\n" +
	"    Organization the Grok Build hook client reports.\n" +
	"  OLIVARES_GROK_HOOK_PEP_CONFIG\n" +
	"    Path to the JSON configuration of the Grok Build hook enforcement point server. Absent mounts nothing; a path given must be readable and valid or startup fails closed.\n" +
	"  OLIVARES_GROK_HOOK_TENANT\n" +
	"    Tenant the Grok Build hook client acts in.\n" +
	"  OLIVARES_GROK_HOOK_TOKEN\n" +
	"    Bearer credential the Grok Build hook client presents to the enforcement point.\n" +
	"  OLIVARES_GROK_HOOK_URL\n" +
	"    Endpoint of the enforcement point the Grok Build hook client calls; unset denies, deny-closed.\n" +
	"  OLIVARES_GUARDIAN_SWEEP_INTERVAL\n" +
	"    How often the guardian sweep runs, as a Go duration. `0` disables it.\n" +
	"  OLIVARES_HA_LEADER_GATE\n" +
	"    Set to `1` to make background loops run only on the elected leader, so a multi-replica deployment does not run them twice.\n" +
	"  OLIVARES_HA_LEADER_LABEL\n" +
	"    Label this replica publishes when it holds leadership, so an operator can route to the leader.\n" +
	"  OLIVARES_HITL_CONFIG\n" +
	"    Path to the JSON configuration of the human-in-the-loop review path.\n" +
	"  OLIVARES_HOOK_FIREWALL_CONFIG\n" +
	"    Path to the JSON configuration of the data-loss firewall that runs inside the hook. Unset leaves that half off.\n" +
	"  OLIVARES_HOOK_PEP_*\n" +
	"    Family prefix for the Claude Code hook client and server settings listed above.\n" +
	"  OLIVARES_HOOK_PEP_ACCOUNT\n" +
	"    Account the Claude Code hook client reports.\n" +
	"  OLIVARES_HOOK_PEP_AGENT\n" +
	"    Agent identity the Claude Code hook client reports.\n" +
	"  OLIVARES_HOOK_PEP_CONFIG\n" +
	"    Path to the JSON configuration of the hook enforcement point server.\n" +
	"  OLIVARES_HOOK_PEP_ORG\n" +
	"    Organization the Claude Code hook client reports.\n" +
	"  OLIVARES_HOOK_PEP_TENANT\n" +
	"    Tenant the Claude Code hook client reports.\n" +
	"  OLIVARES_HOOK_PEP_TOKEN\n" +
	"    Token the Claude Code hook client presents to the enforcement point.\n" +
	"  OLIVARES_HOOK_PEP_URL\n" +
	"    Base URL of the enforcement point the Claude Code hook client calls.\n" +
	"  OLIVARES_INCIDENTLOOP_CONFIG\n" +
	"    Path to the JSON configuration of the incident close-the-loop subscriber. Read by the Business edition.\n" +
	"  OLIVARES_INFERENCE_PROXY_CONFIG\n" +
	"    Path to the JSON configuration of the governed inference proxy.\n" +
	"  OLIVARES_INGEST_TOKEN\n" +
	"    Bearer token the collector ingest endpoint requires from telemetry senders.\n" +
	"  OLIVARES_INSECURE\n" +
	"    Set to `1` to let the CLI talk to a plaintext or untrusted-TLS endpoint. Local development only.\n" +
	"  OLIVARES_INVITE_MAIL_DESTINATION\n" +
	"    Name of the email destination in the notification file, scoped to no tenant, that invitations are mailed through. Without it, and without a declared console address, invite mode is unavailable.\n" +
	"  OLIVARES_KEY_CUSTODY\n" +
	"    Custody posture required of the audit signing key: whether a raw on-disk key is accepted or a wrapped one is demanded.\n" +
	"  OLIVARES_KEY_WRAP*\n" +
	"    Family stem naming the key management backend that wraps signing keys.\n" +
	"  OLIVARES_KEY_WRAP_*\n" +
	"    Family prefix from which the per-backend key-wrapping keys are built.\n" +
	"  OLIVARES_KEY_WRAP_AWS_KEY_ID\n" +
	"    Key identifier in AWS KMS. Used by the backend that wraps the signing keys.\n" +
	"  OLIVARES_KEY_WRAP_AWS_REGION\n" +
	"    Region of the AWS KMS key. Used by the backend that wraps the signing keys.\n" +
	"  OLIVARES_KEY_WRAP_AZURE_KEY_NAME\n" +
	"    Key name in Azure Key Vault. Used by the backend that wraps the signing keys.\n" +
	"  OLIVARES_KEY_WRAP_AZURE_KEY_VERSION\n" +
	"    Key version in Azure Key Vault. Unset uses the current version. Used by the backend that wraps the signing keys.\n" +
	"  OLIVARES_KEY_WRAP_AZURE_TOKEN\n" +
	"    Token used against Azure Key Vault. Used by the backend that wraps the signing keys.\n" +
	"  OLIVARES_KEY_WRAP_AZURE_VAULT_URL\n" +
	"    Azure Key Vault URL. Used by the backend that wraps the signing keys.\n" +
	"  OLIVARES_KEY_WRAP_GCP_KEY\n" +
	"    Fully qualified key version name in Google Cloud KMS. Used by the backend that wraps the signing keys.\n" +
	"  OLIVARES_KEY_WRAP_GCP_TOKEN\n" +
	"    Token used against Google Cloud KMS. Used by the backend that wraps the signing keys.\n" +
	"  OLIVARES_KEY_WRAP_GCP_TOKEN_FILE\n" +
	"    Path to the file holding the token used against Google Cloud KMS. Used by the backend that wraps the signing keys.\n" +
	"  OLIVARES_KEY_WRAP_OLD\n" +
	"    Previous key management backend during a rewrap migration, so keys wrapped by it can still be unwrapped.\n" +
	"  OLIVARES_LEDGER_CUSTODY\n" +
	"    Custody posture required of the ledger checkpoint signer, the ledger counterpart of the audit key posture.\n" +
	"  OLIVARES_LEDGER_KMS_*\n" +
	"    Family prefix from which the per-backend ledger signer keys are built.\n" +
	"  OLIVARES_LEDGER_KMS_AWS_KEY_ID\n" +
	"    Key identifier in AWS KMS. Used by the backend that signs audit checkpoints.\n" +
	"  OLIVARES_LEDGER_KMS_AWS_REGION\n" +
	"    Region of the AWS KMS key. Used by the backend that signs audit checkpoints.\n" +
	"  OLIVARES_LEDGER_KMS_AWS_SIGNING_ALG\n" +
	"    Signing algorithm requested from AWS KMS. Used by the backend that signs audit checkpoints.\n" +
	"  OLIVARES_LEDGER_KMS_AZURE_KEY_NAME\n" +
	"    Key name in Azure Key Vault. Used by the backend that signs audit checkpoints.\n" +
	"  OLIVARES_LEDGER_KMS_AZURE_KEY_VERSION\n" +
	"    Key version in Azure Key Vault. Unset uses the current version. Used by the backend that signs audit checkpoints.\n" +
	"  OLIVARES_LEDGER_KMS_AZURE_TOKEN\n" +
	"    Token used against Azure Key Vault. Used by the backend that signs audit checkpoints.\n" +
	"  OLIVARES_LEDGER_KMS_AZURE_VAULT_URL\n" +
	"    Azure Key Vault URL. Used by the backend that signs audit checkpoints.\n" +
	"  OLIVARES_LEDGER_KMS_GCP_KEY\n" +
	"    Fully qualified key version name in Google Cloud KMS. Used by the backend that signs audit checkpoints.\n" +
	"  OLIVARES_LEDGER_KMS_GCP_TOKEN\n" +
	"    Token used against Google Cloud KMS. Used by the backend that signs audit checkpoints.\n" +
	"  OLIVARES_LEDGER_KMS_GCP_TOKEN_FILE\n" +
	"    Path to the file holding the token used against Google Cloud KMS. Used by the backend that signs audit checkpoints.\n" +
	"  OLIVARES_LEDGER_SIGNER\n" +
	"    Off-box checkpoint signer to use: which key management backend signs audit checkpoints instead of a local key.\n" +
	"  OLIVARES_LICENSE\n" +
	"    License document itself, inline, for deployments that cannot mount a file.\n" +
	"  OLIVARES_LICENSE_PATH\n" +
	"    Path to the license document on disk. Takes effect before the inline form.\n" +
	"  OLIVARES_LICENSE_PUBKEY\n" +
	"    Public key the engine verifies the license signature against.\n" +
	"  OLIVARES_LIVEINGEST_INSPECT_OBSERVED_REFS\n" +
	"    Set to `1` to make live ingest inspect observed references, which costs more per event.\n" +
	"  OLIVARES_LOGIN_ENFORCEMENT\n" +
	"    Break-glass switch, not a file path, for login enforcement (require-SSO and the login IP allow-list). Read by every build when the engine starts; a change takes effect after a restart. `off`, `0`, `false`, `no` or `disabled`, in any letter case and ignoring surrounding whitespace, selects the operator break-glass; unset or any other value leaves enforcement to the posture stored through the console. A build that links the enforcement component then stops enforcing that posture regardless of what is stored, and logs a warning. A build that does not link it records the same deliberate selection: the engine skips the startup refusal it would otherwise make when this deployment has enforcement history and a posture configured, and appends a durable operator-recovery event when the node is promoted.\n" +
	"  OLIVARES_LOGIN_TRUSTED_PROXIES\n" +
	"    Comma-separated IPv4/IPv6 proxy CIDRs trusted to supply X-Forwarded-For for the password-login throttle address only. Empty trusts none. The --login-trusted-proxies flag takes precedence, including an explicit empty value. Invalid CIDRs or empty list entries refuse startup. Read once at startup; policy, session and audit keep the transport peer. See docs/SECURITY-HARDENING.md for the 8192-byte and 64-entry request bounds.\n" +
	"  OLIVARES_LOG_LEVEL\n" +
	"    Minimum log level the engine emits: `debug`, `info`, `warn` or `error`.\n" +
	"  OLIVARES_MCP_TASK_KILLSWITCH_SWEEP\n" +
	"    How often a running MCP task is re-checked against the kill switch, as a Go duration.\n" +
	"  OLIVARES_METRICS_ALLOWED_CIDRS\n" +
	"    Comma-separated CIDR ranges allowed to scrape the metrics endpoint.\n" +
	"  OLIVARES_METRICS_TOKEN\n" +
	"    Bearer token the metrics endpoint requires. Unset leaves the endpoint unauthenticated behind whatever the listener exposes.\n" +
	"  OLIVARES_MODEL_GATEWAY_CHAT_MODE\n" +
	"    Activation mode for synchronous governed Chat dispatch. Unset or `disabled` keeps it off; `development_precheck` opts into the existing non-atomic, fail-open routing precheck, not a hard monetary budget. Any other value stops startup. Default: disabled.\n" +
	"  OLIVARES_MODEL_GATEWAY_PROFILES_CONFIG\n" +
	"    Path to the local JSON file of immutable model-gateway execution profiles. Unset loads no profiles; an unreadable or invalid file stops startup.\n" +
	"  OLIVARES_NHI_ACTUATORS_CONFIG\n" +
	"    Path to the JSON configuration of the actuators that act on non-human identities.\n" +
	"  OLIVARES_NIS2INCIDENT_CONFIG\n" +
	"    Path to the JSON configuration of NIS2 incident reporting. Read by the Business edition.\n" +
	"  OLIVARES_NOTIFY_CONFIG\n" +
	"    Path to the JSON list of notification destinations. Secret-bearing, so it stays out of the store.\n" +
	"  OLIVARES_NOTIFY_DISPATCH_INTERVAL\n" +
	"    How often queued notifications are dispatched, as a Go duration. `0` disables the pump.\n" +
	"  OLIVARES_OIDC_*\n" +
	"    Family prefix for the OIDC federation settings listed above.\n" +
	"  OLIVARES_OIDC_CLIENT_ID\n" +
	"    OIDC client id for this engine. Required when the protocol is `oidc`.\n" +
	"  OLIVARES_OIDC_CLIENT_SECRET\n" +
	"    OIDC client secret for this engine. Required when the protocol is `oidc`.\n" +
	"  OLIVARES_OIDC_GROUPS_CLAIM\n" +
	"    ID-token or UserInfo claim carrying group membership. Unset leaves group mapping off.\n" +
	"  OLIVARES_OIDC_ISSUER\n" +
	"    OIDC issuer URL. Required when the protocol is `oidc`.\n" +
	"  OLIVARES_ONBOARDING_CONFIG\n" +
	"    Path to the JSON configuration of the onboarding readiness assessor. Read by the Business edition each time `olivares enterprise readiness` runs, not when the engine starts. `{}` selects the standard profile. Unset, or a file that cannot be read or parsed, makes that command report that onboarding readiness is not configured.\n" +
	"  OLIVARES_ORCH_CADENCE_INTERVAL\n" +
	"    How often the orchestration cadence loop runs, as a Go duration. `0` disables it.\n" +
	"  OLIVARES_ORCH_DISPATCH_CONFIG\n" +
	"    Path to the JSON configuration for orchestration dispatch targets.\n" +
	"  OLIVARES_ORCH_WORKFLOW_INTERVAL\n" +
	"    How often the orchestration workflow loop advances waiting runs, as a Go duration. Default: 15s.\n" +
	"  OLIVARES_ORCH_WORKFLOW_MAX\n" +
	"    Upper bound on concurrently advancing workflow runs.\n" +
	"  OLIVARES_ORCH_WORKFLOW_STEPS_MAX\n" +
	"    Upper bound on the steps one workflow run may take, which stops a loop from running forever.\n" +
	"  OLIVARES_OTA_PUBKEY\n" +
	"    Public key the engine verifies a downloaded update bundle against.\n" +
	"  OLIVARES_OTEL_*\n" +
	"    Family prefix for the trace export settings listed above.\n" +
	"  OLIVARES_OTEL_ENABLED\n" +
	"    Set to a true value to export traces. Setting an endpoint turns export on as well.\n" +
	"  OLIVARES_OTEL_ENDPOINT\n" +
	"    OTLP endpoint traces are exported to. Falls back to the standard `OTEL_EXPORTER_OTLP_ENDPOINT`.\n" +
	"  OLIVARES_OTEL_GENAI_COMPAT\n" +
	"    Set to a true value to also emit the generative-AI semantic-convention attributes on spans.\n" +
	"  OLIVARES_OTEL_INSECURE\n" +
	"    Set to a true value to export traces over plaintext. Local development only.\n" +
	"  OLIVARES_OTEL_PROTOCOL\n" +
	"    OTLP protocol used for export. Falls back to the standard `OTEL_EXPORTER_OTLP_PROTOCOL`.\n" +
	"  OLIVARES_OTEL_PROVIDER_BAGGAGE_ALLOWLIST\n" +
	"    JSON array of exact HTTP(S) origin, baggage key and non-secret control values allowed through the mounted AnthropicHTTPClient; empty denies baggage. Invalid policy reports a bounded reason once at construction and suppresses baggage without blocking inference. Default: [].\n" +
	"  OLIVARES_OTEL_SAMPLE_RATIO\n" +
	"    Fraction of traces sampled, between 0 and 1.\n" +
	"  OLIVARES_OTEL_SERVICE_NAME\n" +
	"    Service name reported on exported traces.\n" +
	"  OLIVARES_PDF_RENDER_TIMEOUT\n" +
	"    Maximum time one Chromium render of a PDF report may take, as a positive Go duration with units. Read by the reporting add-on for each render; a value that is not a positive duration is refused by name before Chromium is started. Raise it on slow hosts where a structural render does not fit the default. Default: 30s.\n" +
	"  OLIVARES_PDP_CEDAR_FILE\n" +
	"    Path to the Cedar policy file, for the `cedar` decision point.\n" +
	"  OLIVARES_PDP_ENGINE\n" +
	"    External policy decision point to add on top of the native engine: `cedar`, `opa` or `none`.\n" +
	"  OLIVARES_PDP_OPA_PATH\n" +
	"    Decision path queried under the Open Policy Agent endpoint.\n" +
	"  OLIVARES_PDP_OPA_TOKEN\n" +
	"    Bearer token for the Open Policy Agent endpoint.\n" +
	"  OLIVARES_PDP_OPA_URL\n" +
	"    Base URL of the Open Policy Agent endpoint, for the `opa` decision point.\n" +
	"  OLIVARES_PIV_CONFIG\n" +
	"    Path to the JSON configuration for Business Identity & Scale smart-card privileged login. Community refuses serving with this setting; data backup remains available.\n" +
	"  OLIVARES_POLICY_MAX_STALENESS\n" +
	"    How stale a cached policy decision may be before it is refused, as a Go duration.\n" +
	"  OLIVARES_POLICY_SIGNING_KEY\n" +
	"    Policy bundle signing key, inline. Prefer the file form.\n" +
	"  OLIVARES_POLICY_SIGNING_KEY_FILE\n" +
	"    Path to the policy bundle signing key.\n" +
	"  OLIVARES_POLICY_SIGNING_KEY_WRAPPED_FILE\n" +
	"    Path to the policy signing key wrapped by a key management service.\n" +
	"  OLIVARES_PQC_POSTURE_CONFIG\n" +
	"    Path to the JSON configuration of the post-quantum posture assessor. Read by the Business edition each time `olivares enterprise pqc-posture` runs, not when the engine starts. `{}` selects CNSA 2.0 with a 2033 target year. Unset, or a file that cannot be read or parsed, makes that command report that PQC posture is not configured.\n" +
	"  OLIVARES_PUBLIC_URL\n" +
	"    The address a browser reaches this console at, as scheme://host[:port]. It is what the startup panel prints and what the WebAuthn relying party is derived from, and it is independent of the listen address. The --public-url flag wins over this variable, and passing that flag empty clears it. Read at start-up only: a change takes a restart. Refused values are reported by field and failure class and are never echoed, and support bundles keep this value redacted.\n" +
	"  OLIVARES_RATELIMIT_CONFIG\n" +
	"    Path to the JSON rate-limit policy the engine applies to its own endpoints.\n" +
	"  OLIVARES_RATELIMIT_STORE\n" +
	"    Where rate-limit counters live, which decides whether limits are per replica or shared.\n" +
	"  OLIVARES_RENDER_INSPECTOR_CONFIG\n" +
	"    Path to the JSON policy file of the inspector for rendered MCP App content. Read only by the Business edition (AI Runtime Security). Unset leaves that inspection off; a file that cannot be read or parsed makes the inspector deny all rendered content until the file is fixed and the engine is restarted.\n" +
	"  OLIVARES_REPORTING_CONFIG\n" +
	"    Path to the JSON configuration of the reporting add-on. Read by the Business edition.\n" +
	"  OLIVARES_REPORTING_SCHEDULE_INTERVAL\n" +
	"    How often scheduled reports are generated, as a Go duration.\n" +
	"  OLIVARES_REPORT_CACHE_DIR\n" +
	"    Directory where generated report artifacts are cached.\n" +
	"  OLIVARES_RETENTION_GOVERNOR_CONFIG\n" +
	"    Path to the JSON configuration of the regulatory retention-floor governor. Read only by the Business edition (Regulated Operations), when the engine starts. Unset enforces no retention floor; a file that cannot be read or parsed floors every retention class at 100 years until the file is fixed and the engine is restarted.\n" +
	"  OLIVARES_RETENTION_SWEEP_INTERVAL\n" +
	"    How often the retention sweep deletes data past its retention window, as a Go duration.\n" +
	"  OLIVARES_RTBF_DEPTH_CONFIG\n" +
	"    Path to the JSON configuration of the RTBF crypto-shred coordinator. Read only by the Business edition (Regulated Operations), when the engine starts. Unset leaves open-core crypto-shredding unchanged; a file that cannot be read or parsed blocks every shred until the file is fixed and the engine is restarted.\n" +
	"  OLIVARES_SAML_*\n" +
	"    Family prefix for the SAML federation settings listed above.\n" +
	"  OLIVARES_SAML_ACS_URL\n" +
	"    Assertion consumer service URL of this service provider, where the identity provider posts the assertion.\n" +
	"  OLIVARES_SAML_EMAIL_ATTRIBUTE\n" +
	"    Assertion attribute carrying the user's email. Unset tries the common attribute names.\n" +
	"  OLIVARES_SAML_GROUPS_ATTRIBUTE\n" +
	"    Multi-valued assertion attribute carrying group membership. Unset leaves group mapping off.\n" +
	"  OLIVARES_SAML_IDP_METADATA_URL\n" +
	"    Identity-provider metadata URL, from which the SAML endpoints and certificate are read.\n" +
	"  OLIVARES_SAML_IDP_SSO_URL\n" +
	"    Identity-provider single sign-on URL, for the path where metadata is not fetched.\n" +
	"  OLIVARES_SAML_SP_CERT_PEM\n" +
	"    Service-provider encryption certificate in PEM, published as the encryption key descriptor.\n" +
	"  OLIVARES_SAML_SP_ENTITY_ID\n" +
	"    Entity id this engine presents as the SAML service provider. Required when the protocol is `saml`.\n" +
	"  OLIVARES_SAML_SP_KEY_PEM\n" +
	"    Service-provider encryption private key in PEM, which decrypts encrypted assertions.\n" +
	"  OLIVARES_SAML_SP_SIGN_CERT_PEM\n" +
	"    Service-provider signing certificate in PEM, published as the signing key descriptor.\n" +
	"  OLIVARES_SAML_SP_SIGN_KEY_PEM\n" +
	"    Service-provider signing private key in PEM, which signs authentication requests.\n" +
	"  OLIVARES_SANDBOX_RUNTIME_CONFIG\n" +
	"    Path to the JSON configuration of the sandbox runtime that isolates agent execution.\n" +
	"  OLIVARES_SECRETREF_*\n" +
	"    Family of settings for external secret-reference backends, including token-file references.\n" +
	"  OLIVARES_SECRETREF_AWS_REGION\n" +
	"    Region used for AWS Secrets Manager references. Falls back to `AWS_REGION` and `AWS_DEFAULT_REGION`.\n" +
	"  OLIVARES_SECRETREF_AZURE_API_VERSION\n" +
	"    Azure Key Vault API version requested.\n" +
	"  OLIVARES_SECRETREF_AZURE_TOKEN\n" +
	"    Token used against Azure Key Vault.\n" +
	"  OLIVARES_SECRETREF_AZURE_VAULT_URL\n" +
	"    Default Azure Key Vault URL for references that do not name one.\n" +
	"  OLIVARES_SECRETREF_GCP_ENDPOINT\n" +
	"    Endpoint override for Google Secret Manager.\n" +
	"  OLIVARES_SECRETREF_GCP_PROJECT\n" +
	"    Default Google Cloud project for Secret Manager references that do not name one.\n" +
	"  OLIVARES_SECRETREF_GCP_TOKEN\n" +
	"    Token used against Google Secret Manager.\n" +
	"  OLIVARES_SECRETREF_INFISICAL_ENV\n" +
	"    Default Infisical environment for references that do not name one.\n" +
	"  OLIVARES_SECRETREF_INFISICAL_TOKEN\n" +
	"    Token used against Infisical.\n" +
	"  OLIVARES_SECRETREF_INFISICAL_URL\n" +
	"    Base URL of the Infisical server secret references resolve against.\n" +
	"  OLIVARES_SECRETREF_INFISICAL_WORKSPACE_ID\n" +
	"    Default Infisical workspace for references that do not name one.\n" +
	"  OLIVARES_SECRETREF_K8S_APISERVER\n" +
	"    Kubernetes API server secret references resolve against.\n" +
	"  OLIVARES_SECRETREF_K8S_CA_FILE\n" +
	"    Path to the certificate authority bundle used to verify the Kubernetes API.\n" +
	"  OLIVARES_SECRETREF_K8S_TOKEN_FILE\n" +
	"    Path to the service-account token file used against the Kubernetes API.\n" +
	"  OLIVARES_SECRETREF_VAULT_ADDR\n" +
	"    Address of the HashiCorp Vault server secret references resolve against. Falls back to `VAULT_ADDR`.\n" +
	"  OLIVARES_SECRETREF_VAULT_NAMESPACE\n" +
	"    Vault namespace secret references resolve in. Falls back to `VAULT_NAMESPACE`.\n" +
	"  OLIVARES_SECRETREF_VAULT_TOKEN\n" +
	"    Token used against HashiCorp Vault.\n" +
	"  OLIVARES_SECRET_STORE_KEY\n" +
	"    Key that encrypts operator secrets held in the store.\n" +
	"  OLIVARES_SERVERTOOL_EGRESS_CONFIG\n" +
	"    Path to the JSON grants file of the egress gate for provider server tools (web search, web fetch, code execution) in the inline proxy. Read only by the Business edition (AI Runtime Security). Unset keeps those tools observe-only; a file that cannot be read or parsed denies every recognized egress server tool until the file is fixed and the engine is restarted.\n" +
	"  OLIVARES_SERVER_URL\n" +
	"    Base URL of the engine the CLI talks to, when `--server` is not given.\n" +
	"  OLIVARES_SESSIONS_AGENT_LINK_LISTEN\n" +
	"    Listen address of the agent link, as `host:port`: the mutual-TLS endpoint an edition built on this tree serves for its node agents. Read at startup; empty, the default, means no listener. The Community build does not read it.\n" +
	"  OLIVARES_SESSIONS_MANAGED_STOP_ADMISSION_TIMEOUT\n" +
	"    Maximum time to admit a managed Stop request, as a positive Go duration with units. Read at startup; invalid or nonpositive values prevent startup. This does not bound process teardown. Default: 10s.\n" +
	"  OLIVARES_SESSION_BUDGET_AVAILABILITY\n" +
	"    Whether session budget enforcement is required, and what happens when the budget service cannot answer.\n" +
	"  OLIVARES_SESSION_CONTEXT_AVAILABILITY\n" +
	"    Whether session context governance is required, and what happens when the context service cannot answer.\n" +
	"  OLIVARES_SESSION_KILLSWITCH_SWEEP\n" +
	"    How often an active session is re-checked against the kill switch, as a Go duration. `0` leaves only the check at launch. Default: 15s.\n" +
	"  OLIVARES_SESSION_PEP_TOKEN_FILE\n" +
	"    Path to the file holding the token the session enforcement point requires.\n" +
	"  OLIVARES_SESSION_PEP_URL\n" +
	"    Base URL of the policy enforcement point a governed agent session calls before acting.\n" +
	"  OLIVARES_SESSION_RUNTIME_*\n" +
	"    Family prefix for the session runtime settings listed above.\n" +
	"  OLIVARES_SESSION_RUNTIME_BASE_URL\n" +
	"    Base URL the launched session runtime calls back to.\n" +
	"  OLIVARES_SESSION_RUNTIME_CLAUDE_BIN\n" +
	"    Executable the session runtime launches. Default: claude.\n" +
	"  OLIVARES_SESSION_RUNTIME_CODEX_BIN\n" +
	"    Explicit override selecting the official Codex executable instead of the newest verified managed install or `codex` on the engine's `PATH`. The driver is registered at boot even when unset; launch is refused if no executable resolves.\n" +
	"  OLIVARES_SESSION_RUNTIME_GEMINI_BIN\n" +
	"    Pinned official Gemini CLI executable the session runtime may operate; unset, the Gemini CLI installed on this node is found when a session launches.\n" +
	"  OLIVARES_SESSION_RUNTIME_GROK_BIN\n" +
	"    Explicit override selecting the official Grok executable instead of the newest verified managed install or `grok` on the engine's `PATH`. The driver is registered at boot even when unset; launch is refused if no executable resolves.\n" +
	"  OLIVARES_SESSION_RUNTIME_OPENCODE_BIN\n" +
	"    Explicit override selecting the official OpenCode executable instead of the newest verified managed install or `opencode` on the engine's `PATH`. The driver is registered at boot even when unset; launch is refused if no executable resolves.\n" +
	"  OLIVARES_SESSION_RUNTIME_TOKEN_FILE\n" +
	"    Path to the file holding the session runtime's credential, refreshed by rotation.\n" +
	"  OLIVARES_SESSION_RUNTIME_TOKEN_TTL\n" +
	"    Lifetime of a minted session runtime credential, as a Go duration. Default: 15m.\n" +
	"  OLIVARES_SESSION_RUNTIME_WIF\n" +
	"    Whether the session runtime takes its credential from workload identity federation instead of a token file.\n" +
	"  OLIVARES_SESSION_RUNTIME_WIF_RULE\n" +
	"    Which federation rule the session runtime exchanges its workload identity under.\n" +
	"  OLIVARES_SESSION_WORKTREE_BRANCH_PREFIX\n" +
	"    Prefix of the branch a session gets when it is started with a new git worktree; git checks the resulting branch name. Default: olivares/.\n" +
	"  OLIVARES_SESSION_WORKTREE_DIR\n" +
	"    Directory that holds the git worktrees of sessions started with a new worktree; the default is session-worktrees in the data directory.\n" +
	"  OLIVARES_SIEM_FORWARD_INTERVAL\n" +
	"    How often signed ledger records are forwarded to the configured SIEM, as a Go duration.\n" +
	"  OLIVARES_SOURCES_CONFIG\n" +
	"    Path to the JSON file that wires real observation sources and identity roster providers before the engine starts.\n" +
	"  OLIVARES_SSO_PROTOCOL\n" +
	"    Single sign-on protocol to wire: `oidc` or `saml`. Unset means no federation, and the endpoints report it rather than half-wiring one.\n" +
	"  OLIVARES_SSO_SECRET_KEY\n" +
	"    Key that encrypts the federation client secret and service-provider private keys at rest.\n" +
	"  OLIVARES_TARGET_BINDING_KEY\n" +
	"    Key that binds an orchestration target to this deployment, inline. Prefer the file form.\n" +
	"  OLIVARES_TARGET_BINDING_KEY_FILE\n" +
	"    Path to the orchestration target binding key.\n" +
	"  OLIVARES_TENANT\n" +
	"    Default tenant for CLI commands, when `--tenant` is not given.\n" +
	"  OLIVARES_THREATINTEL_CONFIG\n" +
	"    Path to the JSON configuration of threat-intelligence ingest. Read by the Business edition.\n" +
	"  OLIVARES_THREATINTEL_SIGNING_KEY\n" +
	"    Signing key for threat-intelligence bundles the engine publishes.\n" +
	"  OLIVARES_TOKEN\n" +
	"    API token the CLI authenticates with, when no token flag such as `--token-file` is given.\n" +
	"  OLIVARES_TOOL_PIN_CONFIG\n" +
	"    Path to the optional JSON configuration (`require_pin_approval`) of the MCP tool-pin store, which the Business edition runs whether or not this is set. Read when the engine starts. Unset keeps trust on first use; a file that cannot be read or parsed requires operator approval for unknown tools until the file is fixed and the engine is restarted.\n" +
	"  OLIVARES_TOTP_SEED_KEY\n" +
	"    Base64-encoded 32-byte key that seals TOTP seeds at rest. Set the same key on HA nodes; when unset, the engine creates a private totp-seed.key in its data directory.\n" +
	"  OLIVARES_UPDATE_CHANNEL\n" +
	"    Release channel the update check asks for, such as `stable`.\n" +
	"  OLIVARES_UPDATE_ENDPOINT\n" +
	"    Base URL the update check queries. Unset leaves the update check off.\n" +
	"  OLIVARES_UPGRADE_TOKEN\n" +
	"    Download token `olivares upgrade` presents when fetching a build from a credentialed repository.\n" +
	"  OLIVARES_VECTOR_*\n" +
	"    Family prefix for the vector index settings listed above.\n" +
	"  OLIVARES_VECTOR_API_KEY\n" +
	"    API key for the external vector index.\n" +
	"  OLIVARES_VECTOR_BACKEND\n" +
	"    Which vector index backs knowledge search. Unset keeps the in-process index, which is the air-gapped default.\n" +
	"  OLIVARES_VECTOR_DIM\n" +
	"    Vector dimension of the index, which has to match the embeddings model.\n" +
	"  OLIVARES_VECTOR_DSN\n" +
	"    Connection string for the external vector index.\n" +
	"  OLIVARES_VECTOR_NAMESPACE\n" +
	"    Table or collection the vector index writes to. Default: knowledge_ann.\n" +
	"  OLIVARES_VECTOR_TIMEOUT\n" +
	"    Per-request timeout for the vector index, as a Go duration.\n" +
	"  OLIVARES_VOICE_CALL_CONFIG\n" +
	"    Path to the JSON configuration of the inbound voice webhook.\n" +
	"  OLIVARES_VOICE_DISPATCH_CONFIG\n" +
	"    Path to the JSON configuration of outbound voice dispatch.\n" +
	"  OLIVARES_WEBAUTHN_ORIGINS\n" +
	"    Comma-separated origins accepted for WebAuthn ceremonies.\n" +
	"  OLIVARES_WEBAUTHN_RPID\n" +
	"    WebAuthn relying-party id for the privileged-login flow. It has to match the site's registrable domain.\n" +
	"  OLIVARES_WEBAUTHN_RP_NAME\n" +
	"    Display name of the WebAuthn relying party, as shown by the authenticator.\n" +
	"  OLIVARES_WIF_*\n" +
	"    Family prefix for the workload identity federation settings listed above.\n" +
	"  OLIVARES_WIF_BASE_URL\n" +
	"    Endpoint the workload identity exchange is performed against.\n" +
	"  OLIVARES_WIF_REFRESH_SLACK\n" +
	"    How long before expiry a federated credential is refreshed, as a Go duration. Default: 60s.\n" +
	"  OLIVARES_WIF_SPIFFE_SOCKET\n" +
	"    Path to the SPIFFE workload API socket the engine fetches its identity from.\n" +
	"  OLIVARES_WIF_TRUST_DOMAIN\n" +
	"    SPIFFE trust domain accepted for workload identity.\n" +
	"  OLIVARES_WORK_OUTBOX_INTERVAL\n" +
	"    How often the work-kernel outbox is drained, as a Go duration. `0` disables the pump.\n" +
	"  OLIVARES_WORK_TOKEN\n" +
	"    The session's own scoped work credential, injected by the session launcher and read by work commands. Operators must not supply it. Its value is always redacted.\n"
