// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.

//go:build unix

package main

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"syscall"
	"testing"
)

// These tests verify the exact modes of license keygen file sinks under several
// process umasks. Each command runs in a child process because umask is
// process-wide; the parent test process does not change its own mask.
//
// The parent creates and verifies an owned 0700 directory before starting each
// child, then checks the resulting modes and artifacts. This isolates concurrent
// tests from the child's mask and lets a 0777 case reach file creation.
//
// This file is restricted to Unix because the child helper uses syscall.Umask.

const (
	// envUmaskChildMask is the ONLY door into the child helper below: no marker, no run.
	envUmaskChildMask = "OLIVARES_KEYGEN_UMASK_CHILD"
	envUmaskChildPriv = "OLIVARES_KEYGEN_UMASK_PRIVATE_SINK"
	envUmaskChildPub  = "OLIVARES_KEYGEN_UMASK_PUBLIC_SINK"
	// envUmaskChildMustFail states which outcome the child is posing, so a keygen that
	// SUCCEEDS where it had to be refused fails the child instead of passing quietly.
	envUmaskChildMustFail = "OLIVARES_KEYGEN_UMASK_MUST_FAIL"
)

func TestKeygenRestrictiveUmask(t *testing.T) {
	// Each mask is one child. 0077 is the mask the release-anchor ceremony actually ran
	// under and the one the defect was observed at; 0022 is the ordinary developer and CI
	// mask, so a fix that only ever gets exercised at 0077 cannot quietly break the case
	// that used to work; 0777 masks away every bit, so the file is CREATED 0000 and only a
	// chmod on the descriptor the process already owns can carry the promise.
	for _, mask := range []string{"0077", "0022", "0777"} {
		t.Run(mask, func(t *testing.T) {
			dir := ownedKeyDir(t)
			priv := filepath.Join(dir, "license.key")
			pub := filepath.Join(dir, "license.pub")

			stdout, stderr, err := runKeygenUmaskChild(t, mask, priv, pub, false)
			if err != nil {
				t.Fatalf("license keygen with both file sinks under umask %s: %v\n--- child stdout ---\n%s--- child stderr ---\n%s",
					mask, err, stdout, stderr)
			}
			// The promise, exactly: not "at most", not "close enough".
			assertPerm(t, priv, 0o600)
			assertPerm(t, pub, 0o644)
			assertGeneratedPair(t, priv, pub, stdout+stderr)
			// A ceremony that also dropped a temp file, or a second key, is not the two
			// files this command says it creates.
			assertDirHolds(t, dir, "license.key", "license.pub")
		})
	}

	// The public half cannot land, and the private half must not survive it.
	//
	// TestKeygenRemovesThePrivateKeyWhenThePublicHalfCannotLand poses the same obligation
	// with an unwritable directory, which is not a refusal at all for uid 0 — it SKIPS as
	// root, so on the account a release ceremony is most likely to run under there is no
	// coverage. An already-occupied path is refused by O_EXCL for every uid, so this
	// control grades the same promise everywhere, and it grades the part the observed run
	// got wrong: what is left ON DISK afterwards.
	t.Run("occupied-public-path", func(t *testing.T) {
		const keep = "DO-NOT-OVERWRITE\n"
		dir := ownedKeyDir(t)
		priv := filepath.Join(dir, "license.key")
		pub := filepath.Join(dir, "license.pub")
		if err := os.WriteFile(pub, []byte(keep), 0o644); err != nil { //nolint:gosec // the point of the fixture
			t.Fatal(err)
		}
		// WriteFile's perm is masked by THIS process's umask, which the test does not own.
		if err := os.Chmod(pub, 0o644); err != nil {
			t.Fatal(err)
		}

		stdout, stderr, err := runKeygenUmaskChild(t, "0077", priv, pub, true)
		if err != nil {
			t.Fatalf("the child that poses the occupied public path did not run to completion: %v\n--- child stdout ---\n%s--- child stderr ---\n%s",
				err, stdout, stderr)
		}
		if !strings.Contains(stderr, "already exists") {
			t.Fatalf("the refusal does not name the reason:\n%s", stderr)
		}
		if !strings.Contains(stderr, "was removed") {
			t.Fatalf("the refusal does not tell the operator the private half is gone:\n%s", stderr)
		}
		// No newly generated private orphan: an anchor whose public half never landed
		// matches nothing, and the operator cannot tell which half exists.
		if _, serr := os.Stat(priv); serr == nil {
			t.Fatal("the private key generated by the refused run was left behind")
		} else if !errors.Is(serr, fs.ErrNotExist) {
			t.Fatalf("stat the private sink: %v", serr)
		}
		// The file that was already there is the operator's, not this command's.
		got, rerr := os.ReadFile(pub)
		if rerr != nil {
			t.Fatal(rerr)
		}
		if string(got) != keep {
			t.Fatal("the pre-existing public file was modified by a run that refused it")
		}
		assertPerm(t, pub, 0o644)
		assertDirHolds(t, dir, "license.pub")
	})
}

// TestKeygenRestrictiveUmaskChild is the child body, and it is a helper rather than a
// case: without the marker it has nothing to do and skips. It is deliberately absent from
// the fixed selection its parent is run with, so it is reached only by re-exec.
//
// It sets the mask and runs the command; it asserts nothing about modes. Everything the
// parent needs is on disk or on these two streams afterwards, and keeping the grading out
// of here means a child that dies for an unrelated reason cannot be mistaken for a mode
// verdict.
func TestKeygenRestrictiveUmaskChild(t *testing.T) {
	mask := os.Getenv(envUmaskChildMask)
	if mask == "" {
		t.Skipf("child helper: reached only through %s, which TestKeygenRestrictiveUmask sets", envUmaskChildMask)
	}
	m, err := strconv.ParseInt(mask, 8, 32)
	if err != nil {
		t.Fatalf("%s=%q is not an octal mask: %v", envUmaskChildMask, mask, err)
	}
	priv, pub := os.Getenv(envUmaskChildPriv), os.Getenv(envUmaskChildPub)
	if priv == "" || pub == "" {
		t.Fatalf("the child needs both sinks; got %s=%q and %s=%q", envUmaskChildPriv, priv, envUmaskChildPub, pub)
	}
	// The one mode change in this file, in the one process that is allowed to make it.
	// Its parent directory already exists at 0700, created before this line could apply.
	syscall.Umask(int(m))

	root := newRootCmd()
	root.SetOut(os.Stdout)
	root.SetErr(os.Stderr)
	root.SetArgs([]string{"license", "keygen", "--out-private", priv, "--out-public", pub})
	rerr := root.Execute()
	if rerr != nil {
		// The root command sets SilenceErrors, so cobra prints nothing and main.go's
		// wrapper is what an operator actually reads. Reproduce that ONE line so the
		// parent grades the same diagnostic a real ceremony would print.
		fmt.Fprintln(os.Stderr, "Error:", rerr)
	}
	switch mustFail := os.Getenv(envUmaskChildMustFail) == "1"; {
	case mustFail && rerr == nil:
		t.Fatal("license keygen reported success while its public sink was already occupied")
	case !mustFail && rerr != nil:
		t.Fatalf("license keygen with both file sinks under umask %s: %v", mask, rerr)
	}
}

// runKeygenUmaskChild re-executes THIS test binary at the child helper and returns its two
// streams separately: stdout is where a leaked private key would appear, stderr is where
// the refusal is.
func runKeygenUmaskChild(t *testing.T, mask, priv, pub string, mustFail bool) (string, string, error) {
	t.Helper()
	fail := "0"
	if mustFail {
		fail = "1"
	}
	cmd := exec.Command(os.Args[0], "-test.run=^TestKeygenRestrictiveUmaskChild$", "-test.count=1")
	cmd.Env = append(os.Environ(),
		// TestMain turns the binary into the real CLI when this is "1". The child must be
		// a test process, so it is cleared here rather than assumed absent.
		"OLIVARES_CLI_TRAMPOLINE=",
		envUmaskChildMask+"="+mask,
		envUmaskChildPriv+"="+priv,
		envUmaskChildPub+"="+pub,
		envUmaskChildMustFail+"="+fail,
	)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	return stdout.String(), stderr.String(), err
}

// ownedKeyDir prepares the child's key directory at exactly 0700 before any child mask
// exists, the way a ceremony prepares custody: os.Mkdir's mode is masked by the mask of
// the process that calls it, so the mode is stated a second time and then verified.
func ownedKeyDir(t *testing.T) string {
	t.Helper()
	dir := filepath.Join(t.TempDir(), "keys")
	if err := os.Mkdir(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	assertPerm(t, dir, 0o700)
	return dir
}

// assertGeneratedPair proves the two files are ONE valid Ed25519 pair and that the private
// half never reached the child's output. Neither key value is ever printed: a failure here
// says which claim broke, not what the key was.
func assertGeneratedPair(t *testing.T, priv, pub, childOutput string) {
	t.Helper()
	privB64 := readOneKeyLine(t, priv)
	pubB64 := readOneKeyLine(t, pub)
	if pubB64 != publicOfLicensePrivate(t, privB64) {
		t.Fatal("the public file is not the public half of the private file: the ceremony minted an anchor that matches nothing")
	}
	// The whole purpose of --out-private is that the key does not pass through stdout.
	// The child's entire output is searched, not just the command's, because a leak that
	// arrived by another route is still a leak.
	if strings.Contains(childOutput, privB64) {
		t.Fatal("the private key value reached the child's output, which --out-private exists to prevent")
	}
}

// readOneKeyLine reads a key sink as the single line it is written as, without ever
// putting its contents in a failure message.
func readOneKeyLine(t *testing.T, path string) string {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	line := strings.TrimSuffix(string(raw), "\n")
	if line == "" || strings.Contains(line, "\n") {
		t.Fatalf("%s is not the single key line this command writes (%d bytes)", path, len(raw))
	}
	return line
}

func assertDirHolds(t *testing.T, dir string, want ...string) {
	t.Helper()
	ents, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := make([]string, 0, len(ents))
	for _, e := range ents {
		got = append(got, e.Name())
	}
	slices.Sort(got)
	slices.Sort(want)
	if !slices.Equal(got, want) {
		t.Fatalf("%s holds %v, want exactly %v", dir, got, want)
	}
}
