// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.

package main

import (
	"io/fs"
	"regexp"
	"strings"
	"testing"

	"github.com/olivaresai/olivares/core/webui"
)

// The CSP is written by hand and the document it protects is generated by the web
// build. Nothing tied the two together, so an asset the document started linking
// simply fell through to default-src 'none' and was refused -- silently in Go, and
// only visible in a browser console nobody was reading.
//
// That is not hypothetical: measured in a real browser on 2026-08-24, /login and
// /work each logged
//
//	Loading a manifest from 'http://127.0.0.1:.../site.webmanifest' violates the
//	following Content Security Policy directive: "default-src 'none'". Note that
//	'manifest-src' was not explicitly set, so 'default-src' is used as a fallback.
//
// while the SAME handler served that file with a 200. The product shipped the
// manifest, served it, linked it, and forbade it.
//
// The emission is CONDITIONAL: another lane walked 50 routes against a binary with
// the same defect and saw zero console errors, because Chromium fetches a manifest
// when it needs one, not on every load. A green browser run therefore proves
// nothing about the policy -- which is exactly why this is a test over the shipped
// document instead of a browser assertion.
//
// This test reads the SHIPPED document and requires the policy to name a directive
// for each fetch kind it links. It answers "could not look" rather than passing when
// the bundle is absent.
func TestCSPCoversEveryFetchTheShippedDocumentLinks(t *testing.T) {
	raw, err := fs.ReadFile(webui.FS(), "index.html")
	if err != nil {
		t.Skipf("NO HE PODIDO MIRAR: the embedded bundle has no index.html (%v); "+
			"this test has no subject in a build without the console", err)
	}
	html := string(raw)

	csp := buildCSP("test-nonce")

	// rel -> the directive that governs fetching it. Only kinds the document can
	// actually carry; an unknown rel is reported, never assumed harmless.
	governs := map[string]string{
		"manifest":   "manifest-src",
		"stylesheet": "style-src",
		"icon":       "img-src",
		// A modulepreload fetches JavaScript, so script-src governs it -- and the
		// shipped links carry nonce="__CSP_NONCE__" (substituted per response), which
		// is what authorizes them under 'nonce-…' 'strict-dynamic'. Checked against
		// the document, not assumed: the browser reported the manifest and ONLY the
		// manifest, which is the observation that separates these two cases. A
		// manifest link neither carries a nonce nor could use one.
		"modulepreload":    "script-src",
		"apple-touch-icon": "img-src",
		"mask-icon":        "img-src",
	}
	rels := regexp.MustCompile(`<link[^>]*\brel="([^"]+)"`).FindAllStringSubmatch(html, -1)
	if len(rels) == 0 {
		t.Fatalf("NO HE PODIDO MIRAR: no <link rel=...> in the shipped index.html; " +
			"either the document changed shape or this regexp stopped matching it")
	}
	seen := map[string]bool{}
	for _, m := range rels {
		for _, rel := range strings.Fields(m[1]) {
			rel = strings.ToLower(rel)
			if seen[rel] {
				continue
			}
			seen[rel] = true
			directive, known := governs[rel]
			if !known {
				t.Errorf(`the document links rel=%q and this test does not know which directive `+
					`governs it. Decide it deliberately and add it here -- an unknown fetch kind `+
					`falls back to default-src 'none' and is REFUSED, which is what this test exists `+
					`to stop happening in silence`, rel)
				continue
			}
			value, named := directiveValue(csp, directive)
			if !named {
				t.Errorf(`the document links rel=%q but the CSP names no %s, so it falls back to `+
					`default-src 'none' and the browser refuses it.`+"\n  policy: %s", rel, directive, csp)
				continue
			}
			// ⛔ NOMBRAR LA DIRECTIVA NO ES PERMITIR EL FETCH, y comprobar solo el nombre
			// dejaba pasar `manifest-src 'none'` — que es EXACTAMENTE la negativa silenciosa
			// que este test existe para cazar, con la directiva presente. Lo senalo una
			// revision sobre mi propio diff. Ahora se exige que su valor permita ALGO.
			if !permitsSomething(value) {
				t.Errorf(`the document links rel=%q and the CSP has %s %q, which permits nothing: `+
					`the browser refuses the fetch just as it would with no directive at all`,
					rel, directive, value)
			}
		}
	}

	// The non-firing direction: this test must not pass by finding nothing. If the
	// document stops linking a manifest, THIS assertion is what tells us to revisit,
	// instead of the test quietly becoming vacuous.
	if !seen["manifest"] {
		t.Errorf("the shipped document no longer links rel=\"manifest\", so the manifest-src " +
			"directive may now be dead weight -- confirm and remove it rather than leaving a " +
			"policy that describes a document that no longer exists")
	}
}

// directiveValue returns a directive's source list from a serialised CSP.
func directiveValue(csp, directive string) (string, bool) {
	for _, part := range strings.Split(csp, ";") {
		part = strings.TrimSpace(part)
		if part == directive || strings.HasPrefix(part, directive+" ") {
			return strings.TrimSpace(strings.TrimPrefix(part, directive)), true
		}
	}
	return "", false
}

// permitsSomething reports whether a source list can admit any fetch at all. An empty list
// and 'none' both mean "refuse everything", and a directive that refuses everything is not
// a weaker version of the fix -- it is the defect with a different spelling.
func permitsSomething(value string) bool {
	value = strings.TrimSpace(value)
	if value == "" {
		return false
	}
	for _, src := range strings.Fields(value) {
		if src != "'none'" {
			return true
		}
	}
	return false
}
