# SPDX-FileCopyrightText: 2026 Olivares.AI
# SPDX-License-Identifier: AGPL-3.0-only
# The recovery reboot's linkage records: root's alone, on persistent host state. The repair console
# creates each record exclusively inside the recovery directory and never creates, replaces or
# relabels the directories themselves; a missing or altered directory refuses the recovery reboot.
d /var/lib/olivares-power 0700 root root - -
d /var/lib/olivares-power/recovery 0700 root root - -
