// Code generated by clients/generator from the Olivares OpenAPI snapshots
// (stable core + beta module routes); DO NOT EDIT.

package ai.olivares.client;

/**
 * The API contract this client's operation layer was generated against. The SDK's
 * own semantic version is {@link ClientCore#VERSION}; its MAJOR tracks
 * {@link #API_VERSION} from GA on (the stability policy).
 */
public final class ApiMetadata {
    private ApiMetadata() {
    }

    /** The control-plane API contract major this client is generated against. */
    public static final String API_VERSION = "v1";

    /** SHA-256 binding the OpenAPI snapshots (stable core + beta module routes). */
    public static final String SPEC_HASH = "016b467b0934c254bc48f178ff02d7d1242a4feb05b0f97d0467ddd459ea2c45";

    /** The public versioning/deprecation/sunset policy governing this surface. */
    public static final String STABILITY_POLICY = "https://olivares.ai/docs";
}
