// Code generated by clients/generator from the Olivares OpenAPI snapshots
// (stable core + beta module routes); DO NOT EDIT.

package ai.olivares.client;

/**
 * The API contract this client's operation layer was generated against. The SDK's
 * own semantic version is {@link ClientCore#VERSION}; its MAJOR tracks
 * {@link #API_VERSION} from GA on (the stability policy).
 */
public final class ApiMetadata {
    private ApiMetadata() {
    }

    /** The control-plane API contract major this client is generated against. */
    public static final String API_VERSION = "v1";

    /** SHA-256 binding the OpenAPI snapshots (stable core + beta module routes). */
    public static final String SPEC_HASH = "7ba1caee75b2092bdd7e5de30b8c3bf9de48fad83e8320a4695362c05d1eaa0b";

    /** The public versioning/deprecation/sunset policy governing this surface. */
    public static final String STABILITY_POLICY = "https://olivares.ai/docs";
}
