// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"go/format"
	"strings"
)

const genHeaderGo = "// Code generated by clients/generator from the Olivares OpenAPI snapshots\n// (stable core + beta module routes); DO NOT EDIT.\n"

// goPathExpr renders the Go expression building a request path:
// /v1/agents/{id} → `"/v1/agents/"+pathEscape(id)`.
func goPathExpr(path string) string {
	var parts []string
	lit := ""
	for _, seg := range strings.Split(path, "/")[1:] {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			parts = append(parts, fmt.Sprintf("%q", lit+"/"))
			parts = append(parts, "pathEscape("+paramIdent(seg[1:len(seg)-1])+")")
			lit = ""
			continue
		}
		lit += "/" + seg
	}
	if lit != "" || len(parts) == 0 {
		parts = append(parts, fmt.Sprintf("%q", lit))
	}
	return strings.Join(parts, "+")
}

func emitGo(doc *Document) ([]byte, error) {
	var b strings.Builder
	b.WriteString(genHeaderGo)
	fmt.Fprintf(&b, "// API %s, spec sha256:%s.\n\n", doc.APIVersion, doc.SpecHash)
	b.WriteString("package olivares\n\nimport \"context\"\n\n")

	for _, op := range doc.Operations {
		name := op.goName()
		fmt.Fprintf(&b, "// %s calls %s %s: %s\n", name, op.Method, op.Path, sentence(op.Summary))
		if op.Stability != "" {
			fmt.Fprintf(&b, "//\n// Stability: %s.\n", op.Stability)
		}
		if op.HasBody && !op.bodyRequiredInSignature() {
			b.WriteString("//\n// The request body is optional; pass nil to omit it.\n")
		}
		if op.Deprecated {
			fmt.Fprintf(&b, "//\n// Deprecated: %s\n", op.docDeprecation())
		}
		var params []string
		params = append(params, "ctx context.Context")
		for _, p := range op.PathParams {
			params = append(params, paramIdent(p)+" string")
		}
		if op.HasBody {
			if op.RawReqBody {
				params = append(params, "body []byte")
			} else {
				params = append(params, "body any")
			}
		}
		params = append(params, "opts ...RequestOption")
		// The route template (op.Path) travels alongside the concrete path so
		// the core dedups deprecation signals per ENDPOINT, not per resource.
		if op.RawBody {
			fmt.Fprintf(&b, "func (c *Client) %s(%s) ([]byte, error) {\n", name, strings.Join(params, ", "))
			fmt.Fprintf(&b, "\treturn c.doRaw(ctx, %q, %q, %s, opts...)\n}\n\n", op.Method, op.Path, goPathExpr(op.Path))
			continue
		}
		// Raw REQUEST body: send the bytes as-is under the contract's exact
		// media type; the JSON response is decoded as usual.
		if op.RawReqBody {
			fmt.Fprintf(&b, "func (c *Client) %s(%s) (map[string]any, error) {\n", name, strings.Join(params, ", "))
			if op.RequestContentType == "" {
				fmt.Fprintf(&b, "\treturn c.doReqRaw(ctx, %q, %q, %s, body, opts...)\n}\n\n", op.Method, op.Path, goPathExpr(op.Path))
			} else {
				fmt.Fprintf(&b, "\treturn c.doReqRawWithType(ctx, %q, %q, %s, body, %q, opts...)\n}\n\n", op.Method, op.Path, goPathExpr(op.Path), op.RequestContentType)
			}
			continue
		}
		bodyArg := "nil"
		if op.HasBody {
			bodyArg = "body"
		}
		jsonSeam := "do"
		if op.HasBody && op.bodyRequiredInSignature() {
			jsonSeam = "doJSONRequired"
		}
		fmt.Fprintf(&b, "func (c *Client) %s(%s) (map[string]any, error) {\n", name, strings.Join(params, ", "))
		fmt.Fprintf(&b, "\treturn c.%s(ctx, %q, %q, %s, %s, opts...)\n}\n\n", jsonSeam, op.Method, op.Path, goPathExpr(op.Path), bodyArg)
	}
	return format.Source([]byte(b.String()))
}

func emitGoVersion(doc *Document) ([]byte, error) {
	var b strings.Builder
	b.WriteString(genHeaderGo)
	b.WriteString("\npackage olivares\n\n")
	b.WriteString("// APIVersion is the control-plane API contract major this client is generated\n")
	b.WriteString("// against; the SDK's own MAJOR tracks it from GA on (stability policy).\n")
	fmt.Fprintf(&b, "const APIVersion = %q\n\n", doc.APIVersion)
	b.WriteString("// SpecHash binds the OpenAPI snapshots the operation layer was generated\n")
	b.WriteString("// from (the stable core + beta module-route documents under web/openapi).\n")
	fmt.Fprintf(&b, "const SpecHash = %q\n", doc.SpecHash)
	if doc.StabilityPolicy != "" {
		b.WriteString("\n// StabilityPolicy is the public versioning/deprecation/sunset commitment\n// governing this surface.\n")
		fmt.Fprintf(&b, "const StabilityPolicy = %q\n", doc.StabilityPolicy)
	}
	return format.Source([]byte(b.String()))
}

// sentence normalises a spec summary into a doc sentence (capitalised, final stop).
func sentence(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "(no summary)."
	}
	if !strings.HasSuffix(s, ".") && !strings.HasSuffix(s, ")") {
		s += "."
	}
	return s
}
