// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"strings"
)

const genHeaderJava = "// Code generated by clients/generator from the Olivares OpenAPI snapshots\n// (stable core + beta module routes); DO NOT EDIT.\n"

// javaPathExpr renders the Java expression building a request path:
// /v1/agents/{id} → "/v1/agents/" + escapePath(id). escapePath is the
// hand-written core's RFC 3986 path-segment escaper (matching Go's pathEscape,
// Python's quote(safe="") and JS's encodeURIComponent).
func javaPathExpr(path string) string {
	var parts []string
	lit := ""
	for _, seg := range strings.Split(path, "/")[1:] {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			parts = append(parts, fmt.Sprintf("%q", lit+"/"))
			parts = append(parts, "escapePath("+paramIdent(seg[1:len(seg)-1])+")")
			lit = ""
			continue
		}
		lit += "/" + seg
	}
	if lit != "" || len(parts) == 0 {
		parts = append(parts, fmt.Sprintf("%q", lit))
	}
	return strings.Join(parts, " + ")
}

// emitJava writes the generated operation layer (Client.java): one public
// method per published operation on top of the hand-written ClientCore. Java
// has neither variadic options (Go) nor optional params (TS) nor kwargs
// (Python), so each operation is emitted as TWO overloads — a convenience form
// without RequestOptions (the common case) delegating to the full form — so a
// caller has the same "no options needed" ergonomics the other three SDKs give.
func emitJava(doc *Document) []byte {
	var b strings.Builder
	b.WriteString(genHeaderJava)
	fmt.Fprintf(&b, "// API %s, spec sha256:%s.\n\n", doc.APIVersion, doc.SpecHash)
	b.WriteString("package ai.olivares.client;\n\n")
	b.WriteString("import java.util.List;\nimport java.util.LinkedHashMap;\nimport java.util.Map;\nimport java.util.Objects;\n\n")
	b.WriteString("/**\n")
	b.WriteString(" * The control-plane API client: one method per published operation, on top of the\n")
	b.WriteString(" * hand-written transport core ({@link ClientCore}). Construct it from\n")
	b.WriteString(" * {@link ClientOptions}, or use {@link #of(String, String)} for the common case.\n")
	b.WriteString(" *\n")
	b.WriteString(" * <p>Ordinary operations use generic values ({@code Object} / {@code Map}); marked\n")
	b.WriteString(" * typed families use schema-derived records. Raw bytes retain their media type. Auth,\n")
	b.WriteString(" * tenancy, the single error envelope, cursor pagination, Retry-After-aware retries\n")
	b.WriteString(" * and the deprecation signal all live in {@link ClientCore}.\n")
	b.WriteString(" */\n")
	b.WriteString("public final class Client extends ClientCore {\n\n")
	b.WriteString("    /** Build a client from explicit options. */\n")
	b.WriteString("    public Client(ClientOptions options) {\n")
	b.WriteString("        super(options);\n")
	b.WriteString("    }\n\n")
	b.WriteString("    /**\n")
	b.WriteString("     * Build a client for {@code endpoint} (e.g. {@code https://olivares.example:8443})\n")
	b.WriteString("     * authenticating with the opaque bearer {@code token} (an {@code olvs_} session or\n")
	b.WriteString("     * {@code olvk_} API key; pass {@code \"\"} for the unauthenticated surface only).\n")
	b.WriteString("     */\n")
	b.WriteString("    public static Client of(String endpoint, String token) {\n")
	b.WriteString("        return new Client(ClientOptions.builder().endpoint(endpoint).token(token).build());\n")
	b.WriteString("    }\n")
	if documentHasSessionsCommunication(doc) {
		emitSessionsCommunicationJavaTypes(&b, doc.sessionsCommunicationSchemas)
		for _, op := range doc.Operations {
			if op.sessionsCommunicationTyped() && op.sessionsCommunicationHasInput() {
				emitJavaSessionsCommunicationInput(&b, op)
			}
		}
	}

	for _, op := range doc.Operations {
		if op.sessionsCommunicationTyped() {
			emitJavaSessionsCommunicationOp(&b, op)
			continue
		}
		emitJavaOp(&b, op)
	}
	b.WriteString("}\n")
	return []byte(b.String())
}

func emitJavaSessionsCommunicationInput(b *strings.Builder, op Operation) {
	components := make([]string, 0, len(op.Parameters)+1)
	var requiredReferences []string
	if bodyType := op.sessionsCommunicationBodyType(); bodyType != "" {
		components = append(components, "/* required */ "+bodyType+" body")
		requiredReferences = append(requiredReferences, "body")
	}
	for _, parameter := range op.Parameters {
		typ := "String"
		if parameter.Type == "integer" {
			typ = "long"
			if !parameter.Required {
				typ = "Long"
			}
		}
		required := "optional"
		if parameter.Required {
			required = "required"
			if typ == "String" {
				requiredReferences = append(requiredReferences, paramIdent(parameter.Name))
			}
		}
		components = append(components, "/* "+required+" */ "+typ+" "+paramIdent(parameter.Name))
	}
	fmt.Fprintf(b, "\n    public record %s(\n            %s\n    ) {\n",
		op.sessionsCommunicationInputType(), strings.Join(components, ",\n            "))
	if len(requiredReferences) > 0 {
		fmt.Fprintf(b, "        public %s {\n", op.sessionsCommunicationInputType())
		for _, field := range requiredReferences {
			fmt.Fprintf(b, "            Objects.requireNonNull(%s, %q);\n", field, field)
		}
		b.WriteString("        }\n")
	}
	b.WriteString("    }\n")
}

func emitJavaSessionsCommunicationOp(b *strings.Builder, op Operation) {
	name := op.javaName()
	ret := op.sessionsCommunicationResultType()
	var pathDecl, pathArgs []string
	for _, p := range op.PathParams {
		id := paramIdent(p)
		pathDecl = append(pathDecl, "String "+id)
		pathArgs = append(pathArgs, id)
	}
	if op.sessionsCommunicationHasInput() {
		pathDecl = append(pathDecl, op.sessionsCommunicationInputType()+" input")
		pathArgs = append(pathArgs, "input")
	}
	b.WriteString("\n")
	writeJavaDoc(b, op, false)
	fmt.Fprintf(b, "    public %s %s(%s) {\n", ret, name, strings.Join(pathDecl, ", "))
	deleg := append(append([]string{}, pathArgs...), "RequestOptions.NONE")
	fmt.Fprintf(b, "        return %s(%s);\n    }\n\n", name, strings.Join(deleg, ", "))
	writeJavaDoc(b, op, true)
	full := append(append([]string{}, pathDecl...), "RequestOptions options")
	fmt.Fprintf(b, "    public %s %s(%s) {\n", ret, name, strings.Join(full, ", "))
	b.WriteString("        Map<String, String> query = new LinkedHashMap<>();\n        Map<String, String> headers = new LinkedHashMap<>();\n")
	for _, parameter := range op.Parameters {
		target := "query"
		if parameter.In == "header" {
			target = "headers"
		}
		field := "input." + paramIdent(parameter.Name) + "()"
		if parameter.Required {
			fmt.Fprintf(b, "        %s.put(%q, String.valueOf(%s));\n", target, parameter.Name, field)
		} else {
			fmt.Fprintf(b, "        if (%s != null) %s.put(%q, String.valueOf(%s));\n", field, target, parameter.Name, field)
		}
	}
	b.WriteString("        RequestOptions callOptions = RequestOptions.contract(options, query, headers);\n")
	body := "null"
	seam := "doJson"
	if op.sessionsCommunicationBodyType() != "" {
		body = "input.body()"
		seam = "doJsonRequired"
	}
	fmt.Fprintf(b, "        return %s.from(%s(%q, %q, %s, %s, callOptions));\n    }\n",
		ret, seam, op.Method, op.Path, javaPathExpr(op.Path), body)
}

// emitJavaOp writes the two overloads for one operation.
func emitJavaOp(b *strings.Builder, op Operation) {
	name := op.javaName()
	ret := "Map<String, Object>"
	if op.RawBody {
		ret = "String"
	}

	var pathDecl, pathArgs []string
	for _, p := range op.PathParams {
		id := paramIdent(p)
		pathDecl = append(pathDecl, "String "+id)
		pathArgs = append(pathArgs, id)
	}
	bodyDecl := ""
	if op.HasBody {
		if op.RawReqBody {
			bodyDecl = "byte[] body"
		} else {
			bodyDecl = "Object body"
		}
	}

	// Convenience overload (no RequestOptions): carries the full javadoc and
	// delegates to the full form with RequestOptions.NONE.
	b.WriteString("\n")
	writeJavaDoc(b, op, false)
	if op.Deprecated {
		b.WriteString("    @Deprecated\n")
	}
	conv := append([]string{}, pathDecl...)
	if bodyDecl != "" {
		conv = append(conv, bodyDecl)
	}
	fmt.Fprintf(b, "    public %s %s(%s) {\n", ret, name, strings.Join(conv, ", "))
	deleg := append([]string{}, pathArgs...)
	if op.HasBody {
		deleg = append(deleg, "body")
	}
	deleg = append(deleg, "RequestOptions.NONE")
	fmt.Fprintf(b, "        return %s(%s);\n    }\n", name, strings.Join(deleg, ", "))

	// Full overload (with RequestOptions): the real implementation. The route
	// template (op.Path) travels alongside the concrete path so the core dedups
	// deprecation signals per ENDPOINT, not per resource.
	b.WriteString("\n")
	writeJavaDoc(b, op, true)
	if op.Deprecated {
		b.WriteString("    @Deprecated\n")
	}
	full := append([]string{}, pathDecl...)
	if bodyDecl != "" {
		full = append(full, bodyDecl)
	}
	full = append(full, "RequestOptions options")
	fmt.Fprintf(b, "    public %s %s(%s) {\n", ret, name, strings.Join(full, ", "))
	switch {
	case op.RawBody:
		fmt.Fprintf(b, "        return doRaw(%q, %q, %s, options);\n    }\n", op.Method, op.Path, javaPathExpr(op.Path))
	case op.RawReqBody:
		// Raw REQUEST body: bytes are sent as-is under the contract's exact
		// media type; the success body is still the JSON envelope.
		if op.RequestContentType == "" {
			fmt.Fprintf(b, "        return doReqRaw(%q, %q, %s, body, options);\n    }\n", op.Method, op.Path, javaPathExpr(op.Path))
		} else {
			fmt.Fprintf(b, "        return doReqRawWithType(%q, %q, %s, body, %q, options);\n    }\n", op.Method, op.Path, javaPathExpr(op.Path), op.RequestContentType)
		}
	default:
		bodyArg := "null"
		if op.HasBody {
			bodyArg = "body"
		}
		jsonSeam := "doJson"
		if op.HasBody && op.bodyRequiredInSignature() {
			jsonSeam = "doJsonRequired"
		}
		fmt.Fprintf(b, "        return %s(%q, %q, %s, %s, options);\n    }\n", jsonSeam, op.Method, op.Path, javaPathExpr(op.Path), bodyArg)
	}
}

// writeJavaDoc renders the Javadoc for one overload. The convenience form
// carries the full description (summary, stability, deprecation); the
// options form is concise. Both carry @deprecated (and the @Deprecated
// annotation, written by the caller) so either entry point flags the sunset.
func writeJavaDoc(b *strings.Builder, op Operation, withOptions bool) {
	b.WriteString("    /**\n")
	if withOptions {
		fmt.Fprintf(b, "     * %s %s with explicit per-call {@link RequestOptions}.\n", op.Method, op.Path)
	} else {
		fmt.Fprintf(b, "     * %s %s — %s\n", op.Method, op.Path, sentence(op.Summary))
		if op.Stability != "" {
			fmt.Fprintf(b, "     *\n     * <p>Stability: %s.\n", op.Stability)
		}
	}
	if lines := javaBodyDocLines[op.javaBodyDoc()]; len(lines) > 0 {
		b.WriteString("     *\n")
		for index, line := range lines {
			if index == 0 {
				fmt.Fprintf(b, "     * <p>%s\n", line)
			} else {
				fmt.Fprintf(b, "     * %s\n", line)
			}
		}
	}
	if op.Deprecated {
		fmt.Fprintf(b, "     *\n     * @deprecated %s\n", op.docDeprecation())
	}
	b.WriteString("     */\n")
}

// javaBodyDoc is how the Java operation layer actually carries an operation's request
// body, and therefore what its Javadoc may claim about it. It is derived from the SAME
// predicates that pick the transport seam in emitJavaOp and emitJavaSessionsCommunicationOp,
// so the prose cannot describe a different contract than the code beneath it.
//
// ⛔ It exists because the prose used to be keyed on bodyRequiredInSignature alone. That is
// a SIGNATURE rule — false for every stable operation, since the stable document publishes
// no disposition — so the typed capability projection, whose input record rejects a null
// body and whose seam is doJsonRequired, was documented as "optional; pass null to omit it"
// (independent review of N3-A, 2026-09-07). The same predicate called the stable bodies the
// contract declares required "optional" and said nothing at all about a classified
// required body, whose null does not disappear but travels as the JSON value null.
type javaBodyDoc int

const (
	javaBodyNone             javaBodyDoc = iota // no request body reaches the wire from this method
	javaBodyTypedRequired                       // typed input record; a null body is rejected on construction
	javaBodyJSONRequired                        // Object body over doJsonRequired; null travels as JSON null
	javaBodyRawRequired                         // byte[] body the contract requires; null sends no body
	javaBodyDeclaredRequired                    // contract-required body behind the stable nullable signature
	javaBodyOptional                            // contract-optional body; null omits it
)

func (o Operation) javaBodyDoc() javaBodyDoc {
	if o.sessionsCommunicationTyped() {
		if o.sessionsCommunicationBodyType() != "" {
			return javaBodyTypedRequired
		}
		return javaBodyNone
	}
	switch {
	case !o.HasBody:
		return javaBodyNone
	case o.bodyRequiredInSignature() && o.RawReqBody:
		return javaBodyRawRequired
	case o.bodyRequiredInSignature():
		return javaBodyJSONRequired
	case o.BodyRequired:
		return javaBodyDeclaredRequired
	default:
		return javaBodyOptional
	}
}

// javaBodyDocLines is the Javadoc paragraph for each body class. javaBodyNone has none,
// which is what keeps an operation without a body distinct from one whose body is optional.
// Each null clause states what ClientCore does with it (noBody for a raw or legacy null,
// Json.write(null) for a required JSON null), not what the server will answer.
var javaBodyDocLines = map[javaBodyDoc][]string{
	javaBodyTypedRequired: {
		"The request body is required: the {@code input} record rejects a {@code null} body.",
	},
	javaBodyJSONRequired: {
		"The request body is required; {@code null} is sent as the JSON value {@code null},",
		"never omitted.",
	},
	javaBodyRawRequired: {
		"The request body is required and travels as raw bytes; {@code null} sends no body.",
	},
	javaBodyDeclaredRequired: {
		"The contract declares the request body required. This stable signature keeps its",
		"historical nullable parameter, so {@code null} omits the body instead of satisfying it.",
	},
	javaBodyOptional: {
		"The request body is optional; pass {@code null} to omit it.",
	},
}

// emitJavaVersion writes ApiMetadata.java: the API contract provenance the
// operation layer was generated from. Public so callers can read it (parity
// with Go's APIVersion/SpecHash and TS's API_VERSION/SPEC_HASH exports); the
// hand-written core reads ApiMetadata.API_VERSION for the User-Agent.
func emitJavaVersion(doc *Document) []byte {
	var b strings.Builder
	b.WriteString(genHeaderJava)
	b.WriteString("\npackage ai.olivares.client;\n\n")
	b.WriteString("/**\n")
	b.WriteString(" * The API contract this client's operation layer was generated against. The SDK's\n")
	b.WriteString(" * own semantic version is {@link ClientCore#VERSION}; its MAJOR tracks\n")
	b.WriteString(" * {@link #API_VERSION} from GA on (the stability policy).\n")
	b.WriteString(" */\n")
	b.WriteString("public final class ApiMetadata {\n")
	b.WriteString("    private ApiMetadata() {\n    }\n\n")
	b.WriteString("    /** The control-plane API contract major this client is generated against. */\n")
	fmt.Fprintf(&b, "    public static final String API_VERSION = %q;\n\n", doc.APIVersion)
	b.WriteString("    /** SHA-256 binding the OpenAPI snapshots (stable core + beta module routes). */\n")
	fmt.Fprintf(&b, "    public static final String SPEC_HASH = %q;\n", doc.SpecHash)
	if doc.StabilityPolicy != "" {
		b.WriteString("\n    /** The public versioning/deprecation/sunset policy governing this surface. */\n")
		fmt.Fprintf(&b, "    public static final String STABILITY_POLICY = %q;\n", doc.StabilityPolicy)
	}
	b.WriteString("}\n")
	return []byte(b.String())
}
