// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"strings"
)

const genHeaderJava = "// Code generated by clients/generator from the Olivares OpenAPI snapshots\n// (stable core + beta module routes); DO NOT EDIT.\n"

// javaPathExpr renders the Java expression building a request path:
// /v1/agents/{id} → "/v1/agents/" + escapePath(id). escapePath is the
// hand-written core's RFC 3986 path-segment escaper (matching Go's pathEscape,
// Python's quote(safe="") and JS's encodeURIComponent).
func javaPathExpr(path string) string {
	var parts []string
	lit := ""
	for _, seg := range strings.Split(path, "/")[1:] {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			parts = append(parts, fmt.Sprintf("%q", lit+"/"))
			parts = append(parts, "escapePath("+paramIdent(seg[1:len(seg)-1])+")")
			lit = ""
			continue
		}
		lit += "/" + seg
	}
	if lit != "" || len(parts) == 0 {
		parts = append(parts, fmt.Sprintf("%q", lit))
	}
	return strings.Join(parts, " + ")
}

// emitJava writes the generated operation layer (Client.java): one public
// method per published operation on top of the hand-written ClientCore. Java
// has neither variadic options (Go) nor optional params (TS) nor kwargs
// (Python), so each operation is emitted as TWO overloads — a convenience form
// without RequestOptions (the common case) delegating to the full form — so a
// caller has the same "no options needed" ergonomics the other three SDKs give.
func emitJava(doc *Document) []byte {
	var b strings.Builder
	b.WriteString(genHeaderJava)
	fmt.Fprintf(&b, "// API %s, spec sha256:%s.\n\n", doc.APIVersion, doc.SpecHash)
	b.WriteString("package ai.olivares.client;\n\n")
	b.WriteString("import java.util.Map;\n\n")
	b.WriteString("/**\n")
	b.WriteString(" * The control-plane API client: one method per published operation, on top of the\n")
	b.WriteString(" * hand-written transport core ({@link ClientCore}). Construct it from\n")
	b.WriteString(" * {@link ClientOptions}, or use {@link #of(String, String)} for the common case.\n")
	b.WriteString(" *\n")
	b.WriteString(" * <p>Published JSON schemas use generic values ({@code Object} / {@code Map}) rather\n")
	b.WriteString(" * than generated DTOs; raw request bytes retain their declared media type. Auth,\n")
	b.WriteString(" * tenancy, the single error envelope, cursor pagination, Retry-After-aware retries\n")
	b.WriteString(" * and the deprecation signal all live in {@link ClientCore}.\n")
	b.WriteString(" */\n")
	b.WriteString("public final class Client extends ClientCore {\n\n")
	b.WriteString("    /** Build a client from explicit options. */\n")
	b.WriteString("    public Client(ClientOptions options) {\n")
	b.WriteString("        super(options);\n")
	b.WriteString("    }\n\n")
	b.WriteString("    /**\n")
	b.WriteString("     * Build a client for {@code endpoint} (e.g. {@code https://olivares.example:8443})\n")
	b.WriteString("     * authenticating with the opaque bearer {@code token} (an {@code olvs_} session or\n")
	b.WriteString("     * {@code olvk_} API key; pass {@code \"\"} for the unauthenticated surface only).\n")
	b.WriteString("     */\n")
	b.WriteString("    public static Client of(String endpoint, String token) {\n")
	b.WriteString("        return new Client(ClientOptions.builder().endpoint(endpoint).token(token).build());\n")
	b.WriteString("    }\n")

	for _, op := range doc.Operations {
		emitJavaOp(&b, op)
	}
	b.WriteString("}\n")
	return []byte(b.String())
}

// emitJavaOp writes the two overloads for one operation.
func emitJavaOp(b *strings.Builder, op Operation) {
	name := op.javaName()
	ret := "Map<String, Object>"
	if op.RawBody {
		ret = "String"
	}

	var pathDecl, pathArgs []string
	for _, p := range op.PathParams {
		id := paramIdent(p)
		pathDecl = append(pathDecl, "String "+id)
		pathArgs = append(pathArgs, id)
	}
	bodyDecl := ""
	if op.HasBody {
		if op.RawReqBody {
			bodyDecl = "byte[] body"
		} else {
			bodyDecl = "Object body"
		}
	}

	// Convenience overload (no RequestOptions): carries the full javadoc and
	// delegates to the full form with RequestOptions.NONE.
	b.WriteString("\n")
	writeJavaDoc(b, op, false)
	if op.Deprecated {
		b.WriteString("    @Deprecated\n")
	}
	conv := append([]string{}, pathDecl...)
	if bodyDecl != "" {
		conv = append(conv, bodyDecl)
	}
	fmt.Fprintf(b, "    public %s %s(%s) {\n", ret, name, strings.Join(conv, ", "))
	deleg := append([]string{}, pathArgs...)
	if op.HasBody {
		deleg = append(deleg, "body")
	}
	deleg = append(deleg, "RequestOptions.NONE")
	fmt.Fprintf(b, "        return %s(%s);\n    }\n", name, strings.Join(deleg, ", "))

	// Full overload (with RequestOptions): the real implementation. The route
	// template (op.Path) travels alongside the concrete path so the core dedups
	// deprecation signals per ENDPOINT, not per resource.
	b.WriteString("\n")
	writeJavaDoc(b, op, true)
	if op.Deprecated {
		b.WriteString("    @Deprecated\n")
	}
	full := append([]string{}, pathDecl...)
	if bodyDecl != "" {
		full = append(full, bodyDecl)
	}
	full = append(full, "RequestOptions options")
	fmt.Fprintf(b, "    public %s %s(%s) {\n", ret, name, strings.Join(full, ", "))
	switch {
	case op.RawBody:
		fmt.Fprintf(b, "        return doRaw(%q, %q, %s, options);\n    }\n", op.Method, op.Path, javaPathExpr(op.Path))
	case op.RawReqBody:
		// Raw REQUEST body: bytes are sent as-is under the contract's exact
		// media type; the success body is still the JSON envelope.
		if op.RequestContentType == "" {
			fmt.Fprintf(b, "        return doReqRaw(%q, %q, %s, body, options);\n    }\n", op.Method, op.Path, javaPathExpr(op.Path))
		} else {
			fmt.Fprintf(b, "        return doReqRawWithType(%q, %q, %s, body, %q, options);\n    }\n", op.Method, op.Path, javaPathExpr(op.Path), op.RequestContentType)
		}
	default:
		bodyArg := "null"
		if op.HasBody {
			bodyArg = "body"
		}
		jsonSeam := "doJson"
		if op.HasBody && op.bodyRequiredInSignature() {
			jsonSeam = "doJsonRequired"
		}
		fmt.Fprintf(b, "        return %s(%q, %q, %s, %s, options);\n    }\n", jsonSeam, op.Method, op.Path, javaPathExpr(op.Path), bodyArg)
	}
}

// writeJavaDoc renders the Javadoc for one overload. The convenience form
// carries the full description (summary, stability, deprecation); the
// options form is concise. Both carry @deprecated (and the @Deprecated
// annotation, written by the caller) so either entry point flags the sunset.
func writeJavaDoc(b *strings.Builder, op Operation, withOptions bool) {
	b.WriteString("    /**\n")
	if withOptions {
		fmt.Fprintf(b, "     * %s %s with explicit per-call {@link RequestOptions}.\n", op.Method, op.Path)
	} else {
		fmt.Fprintf(b, "     * %s %s — %s\n", op.Method, op.Path, sentence(op.Summary))
		if op.Stability != "" {
			fmt.Fprintf(b, "     *\n     * <p>Stability: %s.\n", op.Stability)
		}
	}
	if op.HasBody && !op.bodyRequiredInSignature() {
		b.WriteString("     *\n     * <p>The request body is optional; pass {@code null} to omit it.\n")
	}
	if op.Deprecated {
		fmt.Fprintf(b, "     *\n     * @deprecated %s\n", op.docDeprecation())
	}
	b.WriteString("     */\n")
}

// emitJavaVersion writes ApiMetadata.java: the API contract provenance the
// operation layer was generated from. Public so callers can read it (parity
// with Go's APIVersion/SpecHash and TS's API_VERSION/SPEC_HASH exports); the
// hand-written core reads ApiMetadata.API_VERSION for the User-Agent.
func emitJavaVersion(doc *Document) []byte {
	var b strings.Builder
	b.WriteString(genHeaderJava)
	b.WriteString("\npackage ai.olivares.client;\n\n")
	b.WriteString("/**\n")
	b.WriteString(" * The API contract this client's operation layer was generated against. The SDK's\n")
	b.WriteString(" * own semantic version is {@link ClientCore#VERSION}; its MAJOR tracks\n")
	b.WriteString(" * {@link #API_VERSION} from GA on (the stability policy).\n")
	b.WriteString(" */\n")
	b.WriteString("public final class ApiMetadata {\n")
	b.WriteString("    private ApiMetadata() {\n    }\n\n")
	b.WriteString("    /** The control-plane API contract major this client is generated against. */\n")
	fmt.Fprintf(&b, "    public static final String API_VERSION = %q;\n\n", doc.APIVersion)
	b.WriteString("    /** SHA-256 binding the OpenAPI snapshots (stable core + beta module routes). */\n")
	fmt.Fprintf(&b, "    public static final String SPEC_HASH = %q;\n", doc.SpecHash)
	if doc.StabilityPolicy != "" {
		b.WriteString("\n    /** The public versioning/deprecation/sunset policy governing this surface. */\n")
		fmt.Fprintf(&b, "    public static final String STABILITY_POLICY = %q;\n", doc.StabilityPolicy)
	}
	b.WriteString("}\n")
	return []byte(b.String())
}
