// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"strings"
)

// pyPathExpr renders the Python expression building a request path:
// /v1/agents/{id} → "/v1/agents/" + quote(str(id), safe="").
func pyPathExpr(path string) string {
	var parts []string
	lit := ""
	for _, seg := range strings.Split(path, "/")[1:] {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			parts = append(parts, fmt.Sprintf("%q", lit+"/"))
			parts = append(parts, `quote(str(`+paramIdent(seg[1:len(seg)-1])+`), safe="")`)
			lit = ""
			continue
		}
		lit += "/" + seg
	}
	if lit != "" || len(parts) == 0 {
		parts = append(parts, fmt.Sprintf("%q", lit))
	}
	return strings.Join(parts, " + ")
}

func emitPython(doc *Document) []byte {
	var b strings.Builder
	b.WriteString("# Code generated by clients/generator from the Olivares OpenAPI snapshots (stable core + beta module routes); DO NOT EDIT.\n")
	fmt.Fprintf(&b, "\"\"\"Generated operation layer for the Olivares AI control plane API (%s).\n\nTransport, auth, the error envelope, pagination and deprecation signaling live\nin the hand-written core (:mod:`olivares_client._core`).\n\"\"\"\n\n", doc.APIVersion)
	b.WriteString("from urllib.parse import quote\n\n")
	fmt.Fprintf(&b, "API_VERSION = %q\nSPEC_HASH = %q\n", doc.APIVersion, doc.SpecHash)
	if doc.StabilityPolicy != "" {
		fmt.Fprintf(&b, "STABILITY_POLICY = %q\n", doc.StabilityPolicy)
	}
	b.WriteString("\n\nclass OperationsMixin:\n")
	b.WriteString("    \"\"\"One method per published operation (mixed into ``Client``).\"\"\"\n")

	for _, op := range doc.Operations {
		var args []string
		args = append(args, "self")
		for _, p := range op.PathParams {
			args = append(args, paramIdent(p))
		}
		if op.HasBody {
			if op.bodyRequiredInSignature() {
				args = append(args, "body")
			} else {
				args = append(args, "body=None")
			}
		}
		args = append(args, "*", "tenant=None", "**query")
		fmt.Fprintf(&b, "\n    def %s(%s):\n", op.pyName(), strings.Join(args, ", "))
		fmt.Fprintf(&b, "        \"\"\"%s %s — %s", op.Method, op.Path, sentence(op.Summary))
		if op.Stability != "" {
			fmt.Fprintf(&b, "\n\n        Stability: %s.", op.Stability)
		}
		if op.Deprecated {
			fmt.Fprintf(&b, "\n\n        .. deprecated:: %s", op.docDeprecation())
		}
		b.WriteString("\n        \"\"\"\n")
		// The route template (op.Path) travels alongside the concrete path so
		// the core dedups deprecation signals per ENDPOINT, not per resource.
		if op.RawBody {
			fmt.Fprintf(&b, "        return self._do_raw(%q, %q, %s, query=query, tenant=tenant)\n",
				op.Method, op.Path, pyPathExpr(op.Path))
			continue
		}
		bodyArg := ""
		jsonSeam := "_do"
		if op.HasBody {
			bodyArg = "body=body, "
			if op.bodyRequiredInSignature() {
				jsonSeam = "_do_json_required"
			}
		}
		// Raw REQUEST body: the bytes are sent as-is under the declared media type.
		if op.RawReqBody {
			jsonSeam = "_do"
			if op.RequestContentType == "" {
				bodyArg = "body=body, raw_request=True, "
			} else {
				bodyArg = fmt.Sprintf("body=body, raw_request_content_type=%q, ", op.RequestContentType)
			}
		}
		fmt.Fprintf(&b, "        return self.%s(%q, %q, %s, %squery=query, tenant=tenant)\n",
			jsonSeam, op.Method, op.Path, pyPathExpr(op.Path), bodyArg)
	}
	return []byte(b.String())
}
