// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"strings"
)

// pyPathExpr renders the Python expression building a request path:
// /v1/agents/{id} → "/v1/agents/" + quote(str(id), safe="").
func pyPathExpr(path string, params map[string]string) string {
	var parts []string
	lit := ""
	for _, seg := range strings.Split(path, "/")[1:] {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			parts = append(parts, fmt.Sprintf("%q", lit+"/"))
			parts = append(parts, `quote(str(`+params[seg[1:len(seg)-1]]+`), safe="")`)
			lit = ""
			continue
		}
		lit += "/" + seg
	}
	if lit != "" || len(parts) == 0 {
		parts = append(parts, fmt.Sprintf("%q", lit))
	}
	return strings.Join(parts, " + ")
}

// pyPathParams keeps working keyword calls intact and aliases only names that
// collide with the method's receiver, transport arguments or typed parameters.
func pyPathParams(op Operation) map[string]string {
	reserved := map[string]bool{"self": true, "tenant": true, "query": true}
	if op.HasBody {
		reserved["body"] = true
	}
	if op.sessionsCommunicationTyped() {
		reserved["headers"] = true
		for _, p := range op.Parameters {
			reserved[paramIdent(p.Name)] = true
		}
	}
	// Reserve existing path identifiers before allocating aliases, so {tenant}
	// cannot steal the working keyword name of a sibling {tenant_path}.
	used := make(map[string]bool)
	for name := range reserved {
		used[name] = true
	}
	for _, p := range op.PathParams {
		used[paramIdent(p)] = true
	}
	params := make(map[string]string, len(op.PathParams))
	for _, p := range op.PathParams {
		name := paramIdent(p)
		if reserved[name] {
			for name += "_path"; used[name]; name += "_path" {
			}
		}
		params[p] = name
		used[name] = true
	}
	return params
}

func emitPython(doc *Document) []byte {
	var b strings.Builder
	b.WriteString("# Code generated by clients/generator from the Olivares OpenAPI snapshots (stable core + beta module routes); DO NOT EDIT.\n")
	fmt.Fprintf(&b, "\"\"\"Generated operation layer for the Olivares AI control plane API (%s).\n\nTransport, auth, the error envelope, pagination and deprecation signaling live\nin the hand-written core (:mod:`olivares_client._core`).\n\"\"\"\n\n", doc.APIVersion)
	b.WriteString("from __future__ import annotations\n\nfrom typing import TypedDict, cast\nfrom urllib.parse import quote\n\n")
	fmt.Fprintf(&b, "API_VERSION = %q\nSPEC_HASH = %q\n", doc.APIVersion, doc.SpecHash)
	if doc.StabilityPolicy != "" {
		fmt.Fprintf(&b, "STABILITY_POLICY = %q\n", doc.StabilityPolicy)
	}
	if documentHasSessionsCommunication(doc) {
		emitSessionsCommunicationPythonTypes(&b, doc.sessionsCommunicationSchemas)
	}
	b.WriteString("\n\nclass OperationsMixin:\n")
	b.WriteString("    \"\"\"One method per published operation (mixed into ``Client``).\"\"\"\n")

	for _, op := range doc.Operations {
		if op.sessionsCommunicationTyped() {
			emitPythonSessionsCommunicationOp(&b, op)
			continue
		}
		var args []string
		params := pyPathParams(op)
		args = append(args, "self")
		for _, p := range op.PathParams {
			args = append(args, params[p])
		}
		if op.HasBody {
			if op.bodyRequiredInSignature() {
				args = append(args, "body")
			} else {
				args = append(args, "body=None")
			}
		}
		args = append(args, "*", "tenant=None", "**query")
		fmt.Fprintf(&b, "\n    def %s(%s):\n", op.pyName(), strings.Join(args, ", "))
		fmt.Fprintf(&b, "        \"\"\"%s %s — %s", op.Method, op.Path, sentence(op.Summary))
		if op.Stability != "" {
			fmt.Fprintf(&b, "\n\n        Stability: %s.", op.Stability)
		}
		if op.Deprecated {
			fmt.Fprintf(&b, "\n\n        .. deprecated:: %s", op.docDeprecation())
		}
		b.WriteString("\n        \"\"\"\n")
		// The route template (op.Path) travels alongside the concrete path so
		// the core dedups deprecation signals per ENDPOINT, not per resource.
		if op.RawBody {
			fmt.Fprintf(&b, "        return self._do_raw(%q, %q, %s, query=query, tenant=tenant)\n",
				op.Method, op.Path, pyPathExpr(op.Path, params))
			continue
		}
		bodyArg := ""
		jsonSeam := "_do"
		if op.HasBody {
			bodyArg = "body=body, "
			if op.bodyRequiredInSignature() {
				jsonSeam = "_do_json_required"
			}
		}
		// Raw REQUEST body: the bytes are sent as-is under the declared media type.
		if op.RawReqBody {
			jsonSeam = "_do"
			if op.RequestContentType == "" {
				bodyArg = "body=body, raw_request=True, "
			} else {
				bodyArg = fmt.Sprintf("body=body, raw_request_content_type=%q, ", op.RequestContentType)
			}
		}
		fmt.Fprintf(&b, "        return self.%s(%q, %q, %s, %squery=query, tenant=tenant)\n",
			jsonSeam, op.Method, op.Path, pyPathExpr(op.Path, params), bodyArg)
	}
	return []byte(b.String())
}

func emitPythonSessionsCommunicationOp(b *strings.Builder, op Operation) {
	params := pyPathParams(op)
	args := []string{"self"}
	for _, p := range op.PathParams {
		args = append(args, params[p]+": str")
	}
	if bodyType := op.sessionsCommunicationBodyType(); bodyType != "" {
		args = append(args, "body: "+bodyType)
	}
	args = append(args, "*")
	for _, parameter := range op.Parameters {
		if !parameter.Required {
			continue
		}
		typ := "str"
		if parameter.Type == "integer" {
			typ = "int"
		}
		args = append(args, paramIdent(parameter.Name)+": "+typ)
	}
	for _, parameter := range op.Parameters {
		if parameter.Required {
			continue
		}
		typ := "str"
		if parameter.Type == "integer" {
			typ = "int"
		}
		args = append(args, paramIdent(parameter.Name)+": "+typ+" | None = None")
	}
	args = append(args, "tenant: str | None = None")
	fmt.Fprintf(b, "\n    def %s(%s) -> %s:\n", op.pyName(), strings.Join(args, ", "), op.sessionsCommunicationResultType())
	fmt.Fprintf(b, "        \"\"\"%s %s — typed published communication contract.\"\"\"\n", op.Method, op.Path)
	b.WriteString("        query = {}\n        headers = {}\n")
	for _, parameter := range op.Parameters {
		target := "query"
		if parameter.In == "header" {
			target = "headers"
		}
		field := paramIdent(parameter.Name)
		if parameter.Required {
			fmt.Fprintf(b, "        %s[%q] = str(%s)\n", target, parameter.Name, field)
		} else {
			fmt.Fprintf(b, "        if %s is not None:\n            %s[%q] = str(%s)\n", field, target, parameter.Name, field)
		}
	}
	body := ""
	seam := "_do"
	if op.sessionsCommunicationBodyType() != "" {
		body = "body=body, "
		seam = "_do_json_required"
	}
	fmt.Fprintf(b, "        return cast(%s, self.%s(%q, %q, %s, %squery=query, headers=headers, tenant=tenant))\n",
		op.sessionsCommunicationResultType(), seam, op.Method, op.Path, pyPathExpr(op.Path, params), body)
}
