// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"strings"
)

// tsPathExpr renders the TS template literal building a request path:
// /v1/agents/{id} → `/v1/agents/${encodeURIComponent(id)}`.
func tsPathExpr(path string) string {
	if !strings.Contains(path, "{") {
		return fmt.Sprintf("%q", path)
	}
	var b strings.Builder
	b.WriteString("`")
	for _, seg := range strings.Split(path, "/")[1:] {
		b.WriteString("/")
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			b.WriteString("${encodeURIComponent(" + paramIdent(seg[1:len(seg)-1]) + ")}")
			continue
		}
		b.WriteString(seg)
	}
	b.WriteString("`")
	return b.String()
}

// emitTypeScriptVersion writes the version constants into their own module so
// the hand-written core can import API_VERSION (for the User-Agent) without an
// import cycle: operations.gen.ts → core.ts → version.gen.ts.
func emitTypeScriptVersion(doc *Document) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by clients/generator from the Olivares OpenAPI snapshots (stable core + beta module routes); DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "/** The control-plane API contract major this client is generated against. */\nexport const API_VERSION = %q;\n", doc.APIVersion)
	fmt.Fprintf(&b, "/** SHA-256 binding the OpenAPI snapshots (stable + beta) the operation layer was generated from. */\nexport const SPEC_HASH = %q;\n", doc.SpecHash)
	if doc.StabilityPolicy != "" {
		fmt.Fprintf(&b, "/** The public versioning/deprecation/sunset policy governing this surface. */\nexport const STABILITY_POLICY = %q;\n", doc.StabilityPolicy)
	}
	return []byte(b.String())
}

func emitTypeScript(doc *Document) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by clients/generator from the Olivares OpenAPI snapshots (stable core + beta module routes); DO NOT EDIT.\n")
	b.WriteString("// Transport, auth, the error envelope, pagination and deprecation signaling\n")
	b.WriteString("// live in the hand-written core (./core.ts); version constants in version.gen.ts.\n\n")
	b.WriteString("import { ClientCore, type Json, type JsonInput, type RequestOptions } from \"./core.js\";\n")
	if documentHasSessionsCommunication(doc) {
		emitSessionsCommunicationTypeScriptTypes(&b, doc.sessionsCommunicationSchemas)
		for _, op := range doc.Operations {
			if op.sessionsCommunicationTyped() && op.sessionsCommunicationHasInput() {
				emitTypeScriptSessionsCommunicationInput(&b, op)
			}
		}
	}
	b.WriteString("\nexport class Client extends ClientCore {\n")

	for _, op := range doc.Operations {
		if op.sessionsCommunicationTyped() {
			emitTypeScriptSessionsCommunicationOp(&b, op)
			continue
		}
		b.WriteString("  /**\n")
		fmt.Fprintf(&b, "   * %s %s — %s\n", op.Method, op.Path, sentence(op.Summary))
		if op.Stability != "" {
			fmt.Fprintf(&b, "   *\n   * Stability: %s.\n", op.Stability)
		}
		if op.Deprecated {
			fmt.Fprintf(&b, "   * @deprecated %s\n", op.docDeprecation())
		}
		b.WriteString("   */\n")
		var params []string
		for _, p := range op.PathParams {
			params = append(params, paramIdent(p)+": string")
		}
		if op.HasBody {
			optional := "?"
			if op.bodyRequiredInSignature() {
				optional = ""
			}
			if op.RawReqBody {
				params = append(params, "body"+optional+": Uint8Array")
			} else {
				params = append(params, "body"+optional+": JsonInput")
			}
		}
		params = append(params, "opts?: RequestOptions")
		// The route template travels alongside the concrete path so the core
		// dedups deprecation signals per ENDPOINT, not per resource.
		if op.RawBody {
			fmt.Fprintf(&b, "  %s(%s): Promise<string> {\n", op.tsName(), strings.Join(params, ", "))
			fmt.Fprintf(&b, "    return this.doRaw(%q, %q, %s, opts);\n  }\n\n", op.Method, op.Path, tsPathExpr(op.Path))
			continue
		}
		// Raw REQUEST body: the bytes are sent as-is under the declared media type.
		if op.RawReqBody {
			fmt.Fprintf(&b, "  %s(%s): Promise<Json> {\n", op.tsName(), strings.Join(params, ", "))
			if op.RequestContentType == "" {
				fmt.Fprintf(&b, "    return this.doReqRaw(%q, %q, %s, body, opts);\n  }\n\n", op.Method, op.Path, tsPathExpr(op.Path))
			} else {
				fmt.Fprintf(&b, "    return this.doReqRawWithType(%q, %q, %s, body, %q, opts);\n  }\n\n", op.Method, op.Path, tsPathExpr(op.Path), op.RequestContentType)
			}
			continue
		}
		bodyArg := "undefined"
		if op.HasBody {
			bodyArg = "body"
		}
		jsonSeam := "do"
		if op.HasBody && op.bodyRequiredInSignature() {
			jsonSeam = "doJsonRequired"
		}
		fmt.Fprintf(&b, "  %s(%s): Promise<Json> {\n", op.tsName(), strings.Join(params, ", "))
		fmt.Fprintf(&b, "    return this.%s(%q, %q, %s, %s, opts);\n  }\n\n", jsonSeam, op.Method, op.Path, tsPathExpr(op.Path), bodyArg)
	}
	b.WriteString("}\n")
	return []byte(b.String())
}

func emitTypeScriptSessionsCommunicationOp(b *strings.Builder, op Operation) {
	inputType := op.sessionsCommunicationInputType()
	b.WriteString("  /**\n")
	fmt.Fprintf(b, "   * %s %s — %s\n", op.Method, op.Path, sentence(op.Summary))
	// ⛔ THE OPERATION'S OWN STABILITY, NOT A CONSTANT. This line used to read
	// "Stability: beta." because the only family routed through this emitter WAS beta,
	// and the literal was true for every caller of the day. Adding a second family made
	// it false without touching it: a stable published operation started advertising
	// itself as beta in the TypeScript SDK, while the same operation's Go, Python and
	// Java neighbours — which never wrote the line at all — said nothing and so said
	// nothing wrong. A hard-coded fact about "everyone who uses this function" expires
	// the moment somebody else uses it.
	if op.Stability != "" {
		fmt.Fprintf(b, "   * Stability: %s.\n", op.Stability)
	}
	b.WriteString("   */\n")
	params := make([]string, 0, len(op.PathParams)+2)
	for _, p := range op.PathParams {
		params = append(params, paramIdent(p)+": string")
	}
	if op.sessionsCommunicationHasInput() {
		params = append(params, "input: "+inputType)
	}
	params = append(params, "opts?: RequestOptions")
	fmt.Fprintf(b, "  %s(%s): Promise<%s> {\n", op.tsName(), strings.Join(params, ", "), op.sessionsCommunicationResultType())
	if len(op.Parameters) > 0 {
		b.WriteString("    const query: Record<string, string> = {};\n    const headers: Record<string, string> = {};\n")
		for _, parameter := range op.Parameters {
			target := "query"
			if parameter.In == "header" {
				target = "headers"
			}
			field := "input." + paramIdent(parameter.Name)
			value := field
			if parameter.Type == "integer" {
				value = "String(" + field + ")"
			}
			if parameter.Required {
				fmt.Fprintf(b, "    %s[%q] = %s;\n", target, parameter.Name, value)
			} else {
				condition := field + " !== undefined"
				if parameter.Type != "integer" {
					condition += " && " + field + " !== \"\""
				}
				fmt.Fprintf(b, "    if (%s) %s[%q] = %s;\n", condition, target, parameter.Name, value)
			}
		}
		b.WriteString("    const callOpts: RequestOptions = { ...opts, query: { ...(opts?.query ?? {}), ...query }, headers: { ...(opts?.headers ?? {}), ...headers } };\n")
	} else {
		b.WriteString("    const callOpts = opts;\n")
	}
	body := "undefined"
	if op.sessionsCommunicationBodyType() != "" {
		body = "input.body as unknown as JsonInput"
	}
	seam := "do"
	if op.sessionsCommunicationBodyType() != "" {
		seam = "doJsonRequired"
	}
	fmt.Fprintf(b, "    return this.%s(%q, %q, %s, %s, callOpts) as unknown as Promise<%s>;\n  }\n\n",
		seam, op.Method, op.Path, tsPathExpr(op.Path), body, op.sessionsCommunicationResultType())
}

func emitTypeScriptSessionsCommunicationInput(b *strings.Builder, op Operation) {
	fmt.Fprintf(b, "export interface %s {\n", op.sessionsCommunicationInputType())
	if bodyType := op.sessionsCommunicationBodyType(); bodyType != "" {
		fmt.Fprintf(b, "  body: %s;\n", bodyType)
	}
	for _, parameter := range op.Parameters {
		typ := "string"
		if parameter.Type == "integer" {
			typ = "number"
		}
		optional := ""
		if !parameter.Required {
			optional = "?"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", paramIdent(parameter.Name), optional, typ)
	}
	b.WriteString("}\n\n")
}
