// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"strings"
)

// tsPathExpr renders the TS template literal building a request path:
// /v1/agents/{id} → `/v1/agents/${encodeURIComponent(id)}`.
func tsPathExpr(path string) string {
	if !strings.Contains(path, "{") {
		return fmt.Sprintf("%q", path)
	}
	var b strings.Builder
	b.WriteString("`")
	for _, seg := range strings.Split(path, "/")[1:] {
		b.WriteString("/")
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			b.WriteString("${encodeURIComponent(" + paramIdent(seg[1:len(seg)-1]) + ")}")
			continue
		}
		b.WriteString(seg)
	}
	b.WriteString("`")
	return b.String()
}

// emitTypeScriptVersion writes the version constants into their own module so
// the hand-written core can import API_VERSION (for the User-Agent) without an
// import cycle: operations.gen.ts → core.ts → version.gen.ts.
func emitTypeScriptVersion(doc *Document) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by clients/generator from the Olivares OpenAPI snapshots (stable core + beta module routes); DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "/** The control-plane API contract major this client is generated against. */\nexport const API_VERSION = %q;\n", doc.APIVersion)
	fmt.Fprintf(&b, "/** SHA-256 binding the OpenAPI snapshots (stable + beta) the operation layer was generated from. */\nexport const SPEC_HASH = %q;\n", doc.SpecHash)
	if doc.StabilityPolicy != "" {
		fmt.Fprintf(&b, "/** The public versioning/deprecation/sunset policy governing this surface. */\nexport const STABILITY_POLICY = %q;\n", doc.StabilityPolicy)
	}
	return []byte(b.String())
}

func emitTypeScript(doc *Document) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by clients/generator from the Olivares OpenAPI snapshots (stable core + beta module routes); DO NOT EDIT.\n")
	b.WriteString("// Transport, auth, the error envelope, pagination and deprecation signaling\n")
	b.WriteString("// live in the hand-written core (./core.ts); version constants in version.gen.ts.\n\n")
	b.WriteString("import { ClientCore, type Json, type JsonInput, type RequestOptions } from \"./core.js\";\n")
	b.WriteString("\nexport class Client extends ClientCore {\n")

	for _, op := range doc.Operations {
		b.WriteString("  /**\n")
		fmt.Fprintf(&b, "   * %s %s — %s\n", op.Method, op.Path, sentence(op.Summary))
		if op.Stability != "" {
			fmt.Fprintf(&b, "   *\n   * Stability: %s.\n", op.Stability)
		}
		if op.Deprecated {
			fmt.Fprintf(&b, "   * @deprecated %s\n", op.docDeprecation())
		}
		b.WriteString("   */\n")
		var params []string
		for _, p := range op.PathParams {
			params = append(params, paramIdent(p)+": string")
		}
		if op.HasBody {
			optional := "?"
			if op.bodyRequiredInSignature() {
				optional = ""
			}
			if op.RawReqBody {
				params = append(params, "body"+optional+": Uint8Array")
			} else {
				params = append(params, "body"+optional+": JsonInput")
			}
		}
		params = append(params, "opts?: RequestOptions")
		// The route template travels alongside the concrete path so the core
		// dedups deprecation signals per ENDPOINT, not per resource.
		if op.RawBody {
			fmt.Fprintf(&b, "  %s(%s): Promise<string> {\n", op.tsName(), strings.Join(params, ", "))
			fmt.Fprintf(&b, "    return this.doRaw(%q, %q, %s, opts);\n  }\n\n", op.Method, op.Path, tsPathExpr(op.Path))
			continue
		}
		// Raw REQUEST body: the bytes are sent as-is under the declared media type.
		if op.RawReqBody {
			fmt.Fprintf(&b, "  %s(%s): Promise<Json> {\n", op.tsName(), strings.Join(params, ", "))
			if op.RequestContentType == "" {
				fmt.Fprintf(&b, "    return this.doReqRaw(%q, %q, %s, body, opts);\n  }\n\n", op.Method, op.Path, tsPathExpr(op.Path))
			} else {
				fmt.Fprintf(&b, "    return this.doReqRawWithType(%q, %q, %s, body, %q, opts);\n  }\n\n", op.Method, op.Path, tsPathExpr(op.Path), op.RequestContentType)
			}
			continue
		}
		bodyArg := "undefined"
		if op.HasBody {
			bodyArg = "body"
		}
		jsonSeam := "do"
		if op.HasBody && op.bodyRequiredInSignature() {
			jsonSeam = "doJsonRequired"
		}
		fmt.Fprintf(&b, "  %s(%s): Promise<Json> {\n", op.tsName(), strings.Join(params, ", "))
		fmt.Fprintf(&b, "    return this.%s(%q, %q, %s, %s, opts);\n  }\n\n", jsonSeam, op.Method, op.Path, tsPathExpr(op.Path), bodyArg)
	}
	b.WriteString("}\n")
	return []byte(b.String())
}
