#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Olivares.AI
# SPDX-License-Identifier: AGPL-3.0-only
# Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.

"""Bind the module spec's constructors and console entries; --check refuses stale generated code."""

import argparse
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = """// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.
"""


def generate_constructors(rows) -> str:
    imports = {}
    cases = []
    for row in rows:
        alias = row["constructor"].split(".", 1)[0]
        imports[alias] = row["package"]
        body = [f'case {json.dumps(row["namespace"])}:']
        for name, dependency in row.get("constructor_inputs", {}).items():
            namespace = json.dumps(dependency["namespace"])
            body.append(f'{name}, ok := built[{namespace}].({dependency["type"]})')
            body.append(
                'if !ok { return nil, fmt.Errorf('
                '"module %s needs a %s constructor input", '
                f'{json.dumps(row["namespace"])}, {namespace}) }}'
            )
        body.append(f'return {row["constructor"]}, nil')
        cases.append("\n".join(body))
    source = HEADER + '''
// Code generated by scripts/generate-module-spec.py; DO NOT EDIT.
package registry

import (
"fmt"

"github.com/olivaresai/olivares/core/api"
'''
    source += "\n".join(
        f'{alias} "github.com/olivaresai/olivares/modules/{package}"'
        for alias, package in sorted(imports.items())
    )
    source += '''
)

func newDefault(namespace string, built map[string]api.Module) (api.Module, error) {
switch namespace {
'''
    source += "\n".join(cases)
    source += '''
default:
return nil, fmt.Errorf("module spec %q has no generated constructor; run scripts/generate-module-spec.py", namespace)
}
}
'''
    return subprocess.run(
        ["gofmt"], input=source, text=True, capture_output=True, check=True
    ).stdout


def quote(name: str) -> str:
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9-]*", name):
        raise SystemExit(f"module spec: invalid console name {name!r}")
    return f"'{name}'"


def generate_console(rows) -> str:
    """The console's copy of each row's console entries, written as prettier prints it."""
    lines = [
        HEADER,
        "// Code generated by scripts/generate-module-spec.py; DO NOT EDIT.",
        "",
        "/** The console views each built-in module's state governs (module spec",
        " * `console_entries`), in registration order. One row at most names a view. */",
        "export const CONSOLE_ENTRIES: Readonly<Record<string, readonly string[]>> = {",
    ]
    for row in rows:
        namespace = row["namespace"]
        bare = re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", namespace)
        key = namespace if bare else quote(namespace)
        views = [quote(view) for view in row.get("console_entries", [])]
        line = f"  {key}: [{', '.join(views)}],"
        if len(line) <= 80:
            lines.append(line)
        else:
            lines += [f"  {key}: ["] + [f"    {view}," for view in views] + ["  ],"]
    lines.append("}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rows = json.loads((ROOT / "core/modulespec/modules.json").read_text())
    outputs = {
        ROOT / "modules/registry/constructors.gen.go": generate_constructors(rows),
        ROOT / "web/src/features/module-spec.gen.ts": generate_console(rows),
    }
    for output, expected in outputs.items():
        if args.check:
            if not output.exists() or output.read_text() != expected:
                raise SystemExit(
                    f"{output.relative_to(ROOT)} is stale: "
                    "run python3 scripts/generate-module-spec.py"
                )
        else:
            output.write_text(expected)
