#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Olivares.AI
# SPDX-License-Identifier: AGPL-3.0-only
# Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.
"""Build tiny deterministic native-package fixtures for the DIST-24-06 battery."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import io
import os
import struct
import tarfile
from pathlib import Path


EPOCH = 1704067200
VERSION = "26.9.0"


def gzip_bytes(payload: bytes) -> bytes:
    encoded = bytearray(gzip.compress(payload, compresslevel=9, mtime=0))
    encoded[9] = 255
    return bytes(encoded)


def tar_bytes(files: list[tuple[str, bytes, int]]) -> bytes:
    stream = io.BytesIO()
    with tarfile.open(fileobj=stream, mode="w", format=tarfile.USTAR_FORMAT) as archive:
        for name, payload, mode in files:
            info = tarfile.TarInfo(name)
            info.size = len(payload)
            info.mode = mode
            info.uid = 0
            info.gid = 0
            info.uname = ""
            info.gname = ""
            info.mtime = EPOCH
            archive.addfile(info, io.BytesIO(payload))
    return stream.getvalue()


def ar_member(name: str, payload: bytes) -> bytes:
    header = (
        f"{name + '/':<16}{EPOCH:<12}{0:<6}{0:<6}{'100644':<8}{len(payload):<10}`\n"
    ).encode("ascii")
    if len(header) != 60:
        raise RuntimeError("fixture ar header is not 60 bytes")
    return header + payload + (b"\n" if len(payload) % 2 else b"")


def make_deb(arch: str, variant: str) -> bytes:
    control = (
        "Package: olivares\n"
        f"Version: {VERSION}\n"
        f"Architecture: {arch}\n"
        "Maintainer: Olivares AI <release@olivares.ai>\n"
        "Installed-Size: 1\n"
        "Homepage: https://olivares.ai\n"
        f"Description: DIST-24-06 {variant} deterministic fixture\n"
    ).encode("utf-8")
    executable = f"#!/bin/sh\nprintf '%s\\n' '{variant}'\n".encode("utf-8")
    control_archive = gzip_bytes(tar_bytes([("./control", control, 0o644)]))
    data_archive = gzip_bytes(tar_bytes([("./usr/bin/olivares", executable, 0o755)]))
    return (
        b"!<arch>\n"
        + ar_member("debian-binary", b"2.0\n")
        + ar_member("control.tar.gz", control_archive)
        + ar_member("data.tar.gz", data_archive)
    )


def rpm_header(entries: list[tuple[int, int, object]]) -> bytes:
    indexes: list[tuple[int, int, int, int]] = []
    store = bytearray()
    for tag, kind, value in entries:
        if kind == 4:
            while len(store) % 4:
                store.append(0)
            offset = len(store)
            store.extend(struct.pack(">I", int(value)))
            count = 1
        elif kind in (6, 8):
            values = [value] if isinstance(value, str) else list(value)
            offset = len(store)
            for item in values:
                store.extend(str(item).encode("utf-8") + b"\0")
            count = len(values)
        else:
            raise RuntimeError(f"unsupported fixture RPM kind: {kind}")
        indexes.append((tag, kind, offset, count))
    header = b"\x8e\xad\xe8\x01" + b"\0" * 4 + struct.pack(">II", len(indexes), len(store))
    return header + b"".join(struct.pack(">IIII", *item) for item in indexes) + bytes(store)


def make_rpm(arch: str, variant: str) -> bytes:
    lead = bytearray(96)
    lead[:4] = b"\xed\xab\xee\xdb"
    lead[4:6] = b"\x03\x00"
    lead[10:10 + len(b"olivares-26.9.0-1")] = b"olivares-26.9.0-1"
    signature = rpm_header([])
    entries: list[tuple[int, int, object]] = [
        (1000, 6, "olivares"),
        (1001, 6, VERSION),
        (1002, 6, "1"),
        (1003, 4, 0),
        (1004, 6, f"DIST-24-06 {variant} fixture"),
        (1005, 6, f"DIST-24-06 {variant} deterministic fixture"),
        (1006, 4, EPOCH),
        (1009, 4, 64),
        (1011, 6, "Olivares.AI"),
        (1014, 6, "AGPL-3.0-only"),
        (1015, 6, "Olivares AI <release@olivares.ai>"),
        (1016, 6, "Applications/System"),
        (1020, 6, "https://olivares.ai"),
        (1021, 6, "linux"),
        (1022, 6, arch),
        (1047, 8, ["olivares"]),
    ]
    padding = b"\0" * ((8 - ((len(lead) + len(signature)) % 8)) % 8)
    payload = f"DIST-24-06:{variant}:{arch}\n".encode("utf-8")
    return bytes(lead) + signature + padding + rpm_header(entries) + payload


def make_apk(arch: str, variant: str) -> bytes:
    data = tar_bytes([("usr/bin/olivares", f"#!/bin/sh\necho {variant}\n".encode(), 0o755)])
    datahash = hashlib.sha256(data).hexdigest()
    pkginfo = (
        "# Generated by DIST-24-06\n"
        "pkgname = olivares\n"
        f"pkgver = {VERSION}-r0\n"
        f"pkgdesc = DIST-24-06 {variant} deterministic fixture\n"
        "url = https://olivares.ai\n"
        "builddate = 1704067200\n"
        "packager = Olivares AI <release@olivares.ai>\n"
        "size = 64\n"
        f"arch = {arch}\n"
        "license = AGPL-3.0-only\n"
        f"datahash = {datahash}\n"
        "provides = olivares\n"
    ).encode("utf-8")
    control = tar_bytes([(".PKGINFO", pkginfo, 0o644)])
    return gzip_bytes(control) + gzip_bytes(data)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--variant", required=True, choices=("stable", "security"))
    args = parser.parse_args()
    if args.out.exists() or not args.out.parent.is_dir():
        parser.error("--out must be an absent path below an existing parent")
    args.out.mkdir(mode=0o755)
    formats = {
        "deb": (make_deb, {"amd64": "amd64", "arm64": "arm64"}),
        "rpm": (make_rpm, {"amd64": "x86_64", "arm64": "aarch64"}),
        "apk": (make_apk, {"amd64": "x86_64", "arm64": "aarch64"}),
    }
    rows = []
    for fmt, (builder, arches) in formats.items():
        for asset_arch, internal_arch in arches.items():
            name = f"olivares_{VERSION}_linux_{asset_arch}.{fmt}"
            payload = builder(internal_arch, args.variant)
            path = args.out / name
            path.write_bytes(payload)
            path.chmod(0o644)
            os.utime(path, (EPOCH, EPOCH))
            rows.append((name, hashlib.sha256(payload).hexdigest()))
    checksums = args.out / "checksums.txt"
    checksums.write_text("".join(f"{digest}  {name}\n" for name, digest in sorted(rows)), encoding="utf-8")
    checksums.chmod(0o644)
    os.utime(checksums, (EPOCH, EPOCH))
    print(f"package-repository-test-fixtures: OK — {args.variant}, 6 native assets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
