#!/bin/sh
# SPDX-FileCopyrightText: 2026 Olivares.AI
# SPDX-License-Identifier: AGPL-3.0-only
# Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.
# Render the package layout from the same template as install-service.sh.
set -eu

root="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
unit="$(sed \
  -e 's|@USER_LINE@|User=olivares|g' \
  -e 's|@GROUP_LINE@|Group=olivares|g' \
  -e 's|@BINARY@|/usr/bin/olivares|g' \
  -e 's|@DATA_DIR@|/var/lib/olivares|g' \
  -e 's|@CONFIG@|/etc/olivares/olivares.env|g' \
  -e 's|@STATE_DIRECTORY_LINE@|StateDirectory=olivares|g' \
  -e 's|@WANTED_BY@|multi-user.target|g' \
  "$root/packaging/service/systemd.service")"
if printf '%s\n' "$unit" | grep -Eq '@[A-Z_]+@'; then
  printf '%s\n' 'error: unresolved package systemd template marker' >&2
  exit 1
fi
printf '%s\n' '# Generated by scripts/render-package-systemd.sh; edit packaging/service/systemd.service.' "$unit"
