#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Olivares.AI
# SPDX-License-Identifier: AGPL-3.0-only
# Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.
#
# security-report.sh — consolidate the security gate into one legible report
# (E4): SAST (full informational gosec scan), dependency vulnerabilities
# (govulncheck fail-closed gate), secret scan (gitleaks) and SBOM presence,
# rendered to docs/security/gate-report.md.
#
# This is the product-led assurance artifact the trust center links in place of
# an external audit (D22). It is regenerable and consumed by the re-executable
# adversarial campaign. It reports HONESTLY: a tool that is unavailable or
# errors is recorded as "not run", never as a pass.
set -euo pipefail

# The ambient git environment OUTRANKS `-C`: with GIT_DIR exported — which git does
# from every LINKED worktree, i.e. from every parallel session — this script's throwaway
# repositories would be driven into the LIVE repository instead. Measured 2026-08-06;
# it left the branch of PR #526 pointing at a fixture commit. Fail closed: a missing
# sanitiser is "I could not isolate", never "isolation was not needed".
_olivares_git_env="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" && pwd)/lib/git-env.sh"
# shellcheck source=/dev/null
. "$_olivares_git_env" || {
	echo "FATAL: cannot source $_olivares_git_env (git-env isolation)" >&2
	exit 2
}
unset _olivares_git_env

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

OUT="docs/security/gate-report.md"
mkdir -p docs/security

COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

# --- SAST full informational scan (every rule) ---
sast_status="not run"
sast_total="?"
sast_table=""
if bash scripts/sast.sh --report "${work}/sast.json" >/dev/null 2>&1; then
	sast_status="ran"
	sast_total="$(python3 -c 'import json;print(json.load(open("'"${work}"'/sast.json"))["total"])' 2>/dev/null || echo '?')"
	sast_table="$(python3 - "${work}/sast.json" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
rows = d.get("by_rule", [])
if not rows:
    print("_No gosec findings under any rule._")
else:
    print("| Rule | Severity | Count |")
    print("|------|----------|-------|")
    for r in rows:
        print(f"| {r['rule']} | {r['severity']} | {r['count']} |")
PY
)"
fi

# --- Blocking SAST gate status ---
# Both gates report THREE outcomes and this report must too: 0 clean, 1 findings, >=2
# the gate could not run. The vulnerability line used to read `|| true` and then default
# to PASS, flipping to FAIL only if the literal word "BLOCKING" appeared — so a gate that
# crashed, or one whose refusal is worded differently, published a clean bill of health
# nobody had checked. That is doubly wrong now: as of 2026-08-01 govulncheck-gate.sh
# refuses with exit 2 and the words "certifies nothing", which contain no "BLOCKING".
# Status codes, not string matching.
sast_rc=0
bash scripts/sast.sh >/dev/null 2>&1 || sast_rc=$?
case "${sast_rc}" in
0) sast_gate="PASS (0 blocking findings)" ;;
1) sast_gate="FAIL (blocking findings)" ;;
*) sast_gate="UNVERIFIED (the gate could not run — exit ${sast_rc})" ;;
esac

# --- govulncheck fail-closed gate ---
vuln_rc=0
vuln_out="$(bash scripts/govulncheck-gate.sh 2>&1)" || vuln_rc=$?
case "${vuln_rc}" in
0) vuln_gate="PASS" ;;
1) vuln_gate="FAIL" ;;
*) vuln_gate="UNVERIFIED (the gate could not run — exit ${vuln_rc})" ;;
esac

# --- gitleaks (secret scan, full history) ---
secrets_gate="not run"
if command -v gitleaks >/dev/null 2>&1 || [ -x "$(go env GOPATH)/bin/gitleaks" ]; then
	if task lint:secrets >/dev/null 2>&1; then secrets_gate="PASS (clean)"; else secrets_gate="FAIL"; fi
fi

# --- SBOM presence ---
sbom_state="not generated (run 'task build:repro && task sbom')"
[ -f bin/olivares.spdx.sbom.json ] && sbom_state="present (bin/olivares.spdx.sbom.json)"

{
	echo "<!-- SPDX-FileCopyrightText: 2026 Olivares.AI -->"
	echo "<!-- SPDX-License-Identifier: AGPL-3.0-only -->"
	echo "<!-- GENERATED by scripts/security-report.sh (task security:report). Do not edit by hand. -->"
	echo ""
	echo "# Security gate report"
	echo ""
	echo "- **Generated:** ${STAMP}"
	echo "- **Commit:** \`${COMMIT}\`"
	echo ""
	echo "This is the product-led assurance evidence the trust center links in place of an"
	echo "external audit (decision D22: automate/analyse/test in pre-release sessions, no"
	echo "external pen-test yet). Regenerate with \`task security:report\`."
	echo ""
	echo "## Summary"
	echo ""
	echo "| Check | Gate | Result |"
	echo "|-------|------|--------|"
	echo "| SAST — high-signal blocking rules (gosec) | pre-push + CI | ${sast_gate} |"
	echo "| Dependency vulnerabilities (govulncheck, fail-closed) | CI-REL | ${vuln_gate} |"
	echo "| Secret scan (gitleaks, full history) | CI-REL | ${secrets_gate} |"
	echo "| SBOM (SPDX) | release | ${sbom_state} |"
	echo ""
	echo "## SAST — full informational scan (every gosec rule)"
	echo ""
	echo "The blocking gate runs only the high-signal rules (injection, SSRF, weak crypto,"
	echo "TLS misconfig) and requires zero findings. The table below is the FULL scan across"
	echo "every gosec rule, including the high-false-positive classes that are documented as"
	echo "non-blocking in \`docs/security/SECURITY-GATE.md\` — visible here so nothing is hidden."
	echo ""
	echo "- SAST scan: **${sast_status}** — ${sast_total} total informational findings."
	echo ""
	echo "${sast_table:-_scan not run_}"
	echo ""
	echo "## Dependency vulnerabilities"
	echo ""
	echo '```'
	echo "${vuln_out}"
	echo '```'
	echo ""
	echo "## Notes"
	echo ""
	echo "- The blocking SAST gate and its \`#nosec\` justifications are enforced by"
	echo "  \`scripts/sast.sh\` with gosec \`-nosec-require-rules -nosec-require-justification\`."
	echo "- Vulnerability exceptions (if any) are dated and justified in \`.govulncheck-allow.yaml\`."
	echo "- The adversarial security campaign re-runs on top of this evidence."
} >"${OUT}"

echo "security:report: wrote ${OUT} (SAST ${sast_status}, ${sast_total} informational; vuln ${vuln_gate}; secrets ${secrets_gate})."
