// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.

//go:build !enterprise

package permcensus

// These published routes remain in Community after edition placement. Refusals
// are executed by the recorder; retained record reads/exports/removal are API-only
// portability surfaces of paid views. Shared risk, budgets and admission remain
// console-required. See the owning APIRoutes and Community edition tests.
var communityRouteSurfaces = map[string]string{
	"compliance PUT /nis2/incidents/{id}":             "api-only",
	"compliance DELETE /aims/pack/{id}":               "api-only",
	"compliance DELETE /depth/fedramp/{id}":           "api-only",
	"compliance DELETE /depth/sector/{id}":            "api-only",
	"compliance DELETE /depth/us-law/{id}":            "api-only",
	"compliance DELETE /dora/incidents/{id}":          "api-only",
	"compliance DELETE /dora/register/{id}":           "api-only",
	"compliance DELETE /nis2/incidents/{id}":          "api-only",
	"compliance DELETE /oscal/profiles/{id}":          "api-only",
	"compliance GET /aims/pack":                       "api-only",
	"compliance GET /aims/pack/{id}":                  "api-only",
	"compliance GET /aims/pack/{id}/export":           "api-only",
	"compliance GET /calendar":                        "edition-refusal",
	"compliance GET /capabilities":                    "edition-refusal",
	"compliance GET /depth/ccm/drift":                 "api-only",
	"compliance GET /depth/ccm/snapshots":             "api-only",
	"compliance GET /depth/ccm/snapshots/{id}":        "api-only",
	"compliance GET /depth/fedramp":                   "api-only",
	"compliance GET /depth/fedramp/{id}":              "api-only",
	"compliance GET /depth/fedramp/{id}/export":       "api-only",
	"compliance GET /depth/sector":                    "api-only",
	"compliance GET /depth/sector/{id}":               "api-only",
	"compliance GET /depth/sector/{id}/export":        "api-only",
	"compliance GET /depth/us-law":                    "api-only",
	"compliance GET /depth/us-law/{id}":               "api-only",
	"compliance GET /depth/us-law/{id}/export":        "api-only",
	"compliance GET /dora":                            "edition-refusal",
	"compliance GET /dora/incidents":                  "api-only",
	"compliance GET /dora/incidents/{id}":             "api-only",
	"compliance GET /dora/incidents/{id}/report":      "api-only",
	"compliance GET /dora/register":                   "api-only",
	"compliance GET /dora/register/{id}":              "api-only",
	"compliance GET /dora/register/{id}/export":       "api-only",
	"compliance GET /frameworks":                      "edition-refusal",
	"compliance GET /frameworks/{id}":                 "edition-refusal",
	"compliance GET /frameworks/{id}/gaps":            "edition-refusal",
	"compliance GET /frameworks/{id}/status":          "edition-refusal",
	"compliance GET /hipaa/gap-report":                "edition-refusal",
	"compliance GET /nis2/incidents":                  "api-only",
	"compliance GET /nis2/incidents/{id}":             "api-only",
	"compliance GET /nis2/incidents/{id}/export":      "api-only",
	"compliance GET /oscal/profiles":                  "api-only",
	"compliance GET /oscal/profiles/{id}":             "api-only",
	"compliance GET /summary":                         "edition-refusal",
	"compliance POST /aims/pack":                      "edition-refusal",
	"compliance POST /depth/ccm/drift":                "edition-refusal",
	"compliance POST /depth/ccm/snapshot":             "edition-refusal",
	"compliance POST /depth/fedramp":                  "edition-refusal",
	"compliance POST /depth/sector":                   "edition-refusal",
	"compliance POST /depth/us-law":                   "edition-refusal",
	"compliance POST /dora/incidents":                 "edition-refusal",
	"compliance POST /dora/register":                  "edition-refusal",
	"compliance POST /frameworks/{id}/evidence":       "edition-refusal",
	"compliance POST /nis2/incidents/classify":        "edition-refusal",
	"compliance POST /oscal/profiles":                 "edition-refusal",
	"finops DELETE /cost-centers/{id}":                "edition-refusal",
	"finops DELETE /cost-centers/{id}/mappings/{mid}": "edition-refusal",
	"finops DELETE /model-rates/{id}":                 "edition-refusal",
	"finops GET /analytics/team-summary":              "edition-refusal",
	"finops GET /comparison":                          "edition-refusal",
	"finops GET /cost-centers":                        "edition-refusal",
	"finops GET /cost-centers/{id}":                   "edition-refusal",
	"finops GET /cost-centers/{id}/mappings":          "edition-refusal",
	"finops GET /forecast":                            "edition-refusal",
	"finops GET /model-rates":                         "edition-refusal",
	"finops GET /model-rates/{id}":                    "edition-refusal",
	"finops GET /outcomes":                            "edition-refusal",
	"finops GET /recommendations":                     "edition-refusal",
	"finops GET /seats/utilization":                   "edition-refusal",
	"finops GET /spend":                               "edition-refusal",
	"finops GET /spend/allocation":                    "edition-refusal",
	"finops GET /spend/export":                        "api-only",
	"finops GET /spend/reconciliation":                "edition-refusal",
	"finops GET /spend/summary":                       "edition-refusal",
	"finops GET /spend/trend":                         "edition-refusal",
	"finops GET /spend/unified":                       "edition-refusal",
	"finops GET /statements":                          "edition-refusal",
	"finops GET /statements/{id}":                     "edition-refusal",
	"finops GET /statements/{id}/export":              "edition-refusal",
	"finops GET /value":                               "edition-refusal",
	"finops GET /value/summary":                       "edition-refusal",
	"finops POST /budgets":                            "edition-refusal",
	"finops POST /cost-centers":                       "edition-refusal",
	"finops POST /cost-centers/{id}/mappings":         "edition-refusal",
	"finops POST /model-rates":                        "edition-refusal",
	"finops POST /outcomes":                           "edition-refusal",
	"finops POST /seats":                              "edition-refusal",
	"finops POST /statements/generate":                "edition-refusal",
	"finops PUT /budgets/{id}":                        "edition-refusal",
	"finops PUT /cost-centers/{id}":                   "edition-refusal",
	"finops PUT /model-rates/{id}":                    "edition-refusal",
	"governance GET /breakglass":                      "edition-refusal",
	"governance GET /breakglass/{id}":                 "edition-refusal",
	"governance GET /breakglass/{id}/uses":            "edition-refusal",
	"governance POST /breakglass":                     "edition-refusal",
	"governance POST /breakglass/consume":             "edition-refusal",
	"governance POST /breakglass/{id}/review":         "edition-refusal",
	"governance POST /breakglass/{id}/revoke":         "edition-refusal",
	"observability GET /traces/{id}/export":           "edition-refusal",
	"posture GET /export":                             "edition-refusal",
	"redteam GET /catalog":                            "edition-refusal",
	"redteam GET /runs":                               "edition-refusal",
	"redteam GET /runs/{id}":                          "edition-refusal",
	"redteam GET /runs/{id}/results":                  "edition-refusal",
	"redteam GET /targets":                            "edition-refusal",
	"redteam GET /targets/{id}":                       "edition-refusal",
	"redteam POST /runs":                              "edition-refusal",
	"redteam POST /targets":                           "edition-refusal",
	"redteam POST /targets/{id}/authorize":            "edition-refusal",
	"reporting DELETE /schedules/{id}":                "edition-refusal",
	"reporting DELETE /templates/{type}":              "edition-refusal",
	"reporting GET /branding":                         "edition-refusal",
	"reporting GET /enterprise/bundle":                "edition-refusal",
	"reporting GET /enterprise/posture":               "edition-refusal",
	"reporting GET /enterprise/risk":                  "edition-refusal",
	"reporting GET /reports":                          "edition-refusal",
	"reporting GET /reports/{type}":                   "edition-refusal",
	"reporting GET /schedules":                        "edition-refusal",
	"reporting GET /schedules/{id}/runs":              "edition-refusal",
	"reporting GET /schedules/{id}/runs/{rid}":        "edition-refusal",
	"reporting GET /templates/{type}":                 "edition-refusal",
	"reporting POST /schedules":                       "edition-refusal",
	"reporting PUT /branding":                         "edition-refusal",
	"reporting PUT /templates/{type}":                 "edition-refusal",
}

// Community's table replaces the Business base whole, never merges into it, so a
// Business-only route can not be credited here.
func init() {
	Business = false
	editionRouteSurfaces = communityRouteSurfaces
}
