// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.
//
// Deterministic models/providers fixtures shaped like the contract. Key refs
// carry ONLY a masked hint — the fixtures contain no usable secret, by design.
import type {
  CatalogResponse,
  Decision,
  GovernedModel,
  KeyRef,
  RoutingPolicy,
} from './types'

export const catalogFixture: CatalogResponse = {
  capabilities: [
    'streaming',
    'tool_use',
    'vision',
    'pdf',
    'structured_outputs',
    'prompt_caching',
    'batch',
    'files',
    'extended_thinking',
    'computer_use',
    'memory_tool',
    'context_management',
    'citations',
  ],
  pricing_as_of: '2026-06-01',
  pricing_note:
    'declared list-price defaults; verify against each provider and override per model',
  models: [
    {
      family: 'claude-opus',
      provider_ref: 'anthropic',
      capabilities: [
        'streaming',
        'tool_use',
        'vision',
        'pdf',
        'structured_outputs',
        'prompt_caching',
        'batch',
        'files',
        'extended_thinking',
        'computer_use',
        'memory_tool',
        'context_management',
        'citations',
      ],
      context_window: 200000,
      max_output_tokens: 32000,
      modality: 'vision',
      pricing: {
        input_per_mtok_usd: 15,
        output_per_mtok_usd: 75,
        cache_write_per_mtok_usd: 18.75,
        cache_write_1h_per_mtok_usd: 30,
        cache_read_per_mtok_usd: 1.5,
        currency: 'USD',
        as_of: '2026-06-01',
        source: 'list',
      },
      service_tier_eligibility: [
        'standard',
        'batch',
        'priority',
        'priority_on_demand',
        'flex',
        'flex_discount',
      ],
      data_residency: ['global', 'us'],
      us_inference_burndown_mult: 1.1,
    },
    {
      family: 'claude-haiku',
      provider_ref: 'anthropic',
      capabilities: [
        'streaming',
        'tool_use',
        'vision',
        'structured_outputs',
        'prompt_caching',
        'batch',
      ],
      context_window: 200000,
      max_output_tokens: 16000,
      modality: 'vision',
      pricing: {
        input_per_mtok_usd: 1,
        output_per_mtok_usd: 5,
        cache_write_per_mtok_usd: 1.25,
        cache_write_1h_per_mtok_usd: 2,
        cache_read_per_mtok_usd: 0.1,
        currency: 'USD',
        as_of: '2026-06-01',
        source: 'list',
      },
      // Haiku 4.5 predates inference_geo (Feb 2026 / 4.6+), so no US-residency tier.
      service_tier_eligibility: [
        'standard',
        'batch',
        'priority',
        'priority_on_demand',
        'flex',
        'flex_discount',
      ],
    },
    {
      family: 'gemini-pro',
      provider_ref: 'google',
      capabilities: [
        'streaming',
        'tool_use',
        'vision',
        'pdf',
        'structured_outputs',
        'context_management',
      ],
      context_window: 1000000,
      max_output_tokens: 8192,
      modality: 'vision',
      pricing: {
        input_per_mtok_usd: 3.5,
        output_per_mtok_usd: 10.5,
        currency: 'USD',
        as_of: '2026-06-01',
        source: 'list',
      },
    },
    {
      family: 'mistral-large',
      provider_ref: 'mistral',
      capabilities: ['streaming', 'tool_use', 'structured_outputs'],
      context_window: 128000,
      max_output_tokens: 8192,
      modality: 'text',
      pricing: null,
    },
    {
      // A freshly-announced preview: the model EXISTS but its capabilities and pricing
      // are NOT verified — listed with caps flagged to-confirm and pricing null, never
      // fabricated. Priority Tier is documented as unavailable on this preview.
      family: 'claude-mythos',
      provider_ref: 'anthropic',
      capabilities: [],
      caps_to_confirm: true,
      context_window: 200000,
      max_output_tokens: 0,
      modality: 'vision',
      pricing: null,
      service_tier_eligibility: ['standard', 'batch'],
      data_residency: ['global', 'us'],
    },
  ],
}

export const governedModelsFixture: GovernedModel[] = [
  {
    id: 'mdl-opus',
    name: 'claude-opus-4-8',
    provider_id: 'prv-anthropic',
    provider: 'anthropic',
    family: 'claude-opus',
    context_window: 200000,
    input_cost_micro_usd: 15,
    output_cost_micro_usd: 75,
    modality: 'vision',
    status: 'active',
    capabilities: [
      'streaming',
      'tool_use',
      'vision',
      'prompt_caching',
      'extended_thinking',
    ],
    enriched: true,
  },
  {
    id: 'mdl-flash',
    name: 'gemini-1.5-flash',
    provider_id: 'prv-google',
    provider: 'google',
    family: 'gemini-flash',
    context_window: 1000000,
    input_cost_micro_usd: 0,
    output_cost_micro_usd: 0,
    modality: 'vision',
    status: 'active',
    capabilities: ['streaming', 'tool_use', 'vision'],
    enriched: true,
  },
  {
    id: 'mdl-local',
    name: 'llama-3.3-70b-local',
    provider_id: 'prv-local',
    provider: 'local',
    family: '',
    context_window: 128000,
    input_cost_micro_usd: 0,
    output_cost_micro_usd: 0,
    modality: 'text',
    status: 'active',
    capabilities: ['streaming', 'tool_use'],
    enriched: false,
  },
]

export const routingPoliciesFixture: RoutingPolicy[] = [
  {
    id: 'pol-cheap',
    name: 'cheap-default',
    enabled: true,
    strategy: 'cost',
    required_capabilities: ['vision'],
    preferred_providers: ['google', 'anthropic'],
    min_context_window: 100000,
    pinned_model: '',
    allow_deprecated: false,
    gateway_endpoint: 'http://litellm:4000',
  },
  {
    id: 'pol-pinned',
    name: 'reviewer-pinned',
    enabled: false,
    strategy: 'pinned',
    required_capabilities: [],
    preferred_providers: [],
    min_context_window: 0,
    pinned_model: 'claude-sonnet-4-6',
    allow_deprecated: false,
    gateway_endpoint: '',
  },
]

export const decisionFixture: Decision = {
  resolved: true,
  policy: 'cost',
  primary: {
    provider_ref: 'google',
    model_ref: 'gemini-1.5-flash',
    via_gateway: true,
    endpoint: 'http://litellm:4000',
  },
  fallbacks: [{ provider_ref: 'anthropic', model_ref: 'claude-haiku-4-5' }],
  chain: [
    {
      provider_ref: 'google',
      model_ref: 'gemini-1.5-flash',
      via_gateway: true,
    },
    { provider_ref: 'anthropic', model_ref: 'claude-haiku-4-5' },
  ],
  reason: 'cost: 4 candidate(s), primary google/gemini-1.5-flash',
}

export const keyRefsFixture: KeyRef[] = [
  {
    id: 'key-ci',
    ref_kind: 'api_key',
    provider_ref: 'anthropic',
    ext_id: 'apikey_01',
    name: 'ci-bot key',
    workspace_ref: 'ws_123',
    status: 'active',
    hint: 'sk-ant-…aB12',
    owner_ref: 'team:ci',
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: 'key-google',
    ref_kind: 'workspace',
    provider_ref: 'google',
    ext_id: 'projects/olivares-prod',
    name: 'prod workspace',
    workspace_ref: '',
    status: 'active',
    hint: '…prod',
    owner_ref: 'team:platform',
    created_at: '2026-05-20T00:00:00Z',
  },
]
