// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * — THE ANCHOR FOR A HAND-WRITTEN CLIENT.
 *
 * types.ts mirrors modules/sessions by hand, because the generated client covers no
 * `/v1/m/` route and that is deliberate (Taskfile.yml:1771 — the console consumes the
 * STABLE openapi.json, which has zero module routes). The encargo that commissioned
 * this surface asked for a cheap way to make the gate notice the drift instead of
 * leaving it to discipline. This is it.
 *
 * It reads the GO SOURCE and compares field names, rather than trusting a snapshot of
 * them: a snapshot would have to be regenerated by the same person who changed the
 * engine, and would agree with whatever they did.
 *
 * WHAT IT CAN AND CANNOT SEE, stated so nobody reads more into a green run:
 *  - it compares the JSON NAMES of a struct's fields against the TS interface's keys,
 *    in both directions. A renamed, added or removed field fires.
 *  - it does NOT compare types. `version: number` against a Go `string` still passes.
 *    Closing that needs a real schema, which is what openapi.beta.json already is — the
 *    honest next step is to feed that document to a generator, not to grow this test.
 *  - it reads only the structs named below. A NEW struct is invisible to it, which is
 *    why the route table is asserted separately: a new endpoint shows up there.
 */

const REPO = resolve(__dirname, '../../../..')
const goSource = (rel: string) => readFileSync(resolve(REPO, rel), 'utf8')

/** Pull the `json:"…"` names out of one Go struct body. */
function goStructJSONFields(src: string, name: string): string[] {
  const start = src.indexOf(`type ${name} struct {`)
  if (start < 0)
    throw new Error(`Go struct ${name} not found — the anchor moved`)
  const body = src.slice(start, src.indexOf('\n}', start))
  const out: string[] = []
  for (const line of body.split('\n')) {
    const m = line.match(/json:"([^"]+)"/)
    if (!m) continue
    const tag = m[1].split(',')[0]
    // `json:"-"` is deliberately not on the wire (CommandResult.Replayed), so it must
    // not be expected in the TS interface either.
    if (tag === '' || tag === '-') continue
    out.push(tag)
  }
  return out.sort()
}

/** Pull the declared keys out of one TS interface in types.ts. */
function tsInterfaceKeys(src: string, name: string): string[] {
  const re = new RegExp(`export interface ${name}[^{]*\\{`)
  const m = re.exec(src)
  if (!m) throw new Error(`TS interface ${name} not found — the anchor moved`)
  const start = m.index + m[0].length
  let depth = 1
  let i = start
  while (i < src.length && depth > 0) {
    if (src[i] === '{') depth++
    else if (src[i] === '}') depth--
    i++
  }
  const body = src.slice(start, i - 1)
  const keys: string[] = []
  for (const raw of body.split('\n')) {
    const line = raw.trim()
    if (
      !line ||
      line.startsWith('//') ||
      line.startsWith('*') ||
      line.startsWith('/*')
    )
      continue
    const km = line.match(/^([a-z_][a-z0-9_]*)\??\s*:/i)
    if (km) keys.push(km[1])
  }
  return keys.sort()
}

const workModel = goSource('modules/sessions/work_model.go')
const workApi = goSource('modules/sessions/work_api.go')
const types = readFileSync(resolve(__dirname, 'types.ts'), 'utf8')

describe('the hand-written mirror matches the engine', () => {
  // CONTROL: types.ts cannot drift from modules/sessions without the gate noticing.
  // FIRES IF: a field is added, removed or renamed on either side.
  // DOES NOT FIRE FOR: a comment change, a reordering, or a `json:"-"` field — none of
  //   which alters the wire, and any of which would make this a nuisance test that gets
  //   deleted.
  it.each([
    ['WorkItem', 'WorkItem'],
    ['Assessment', 'Assessment'],
    ['CommandResult', 'CommandResult'],
    ['WorkCheck', 'WorkCheck'],
    // Añadido el 2026-08-16 por el contraste `sol max`: los nombres coincidían HOY, y ésa es
    // exactamente la razón de meterlo — la tabla no existe para descubrir una deriva presente,
    // sino para que la futura no sea invisible.
    ['WorkLease', 'WorkLease'],
  ])('%s field names agree', (goName, tsName) => {
    expect(tsInterfaceKeys(types, tsName)).toEqual(
      goStructJSONFields(workModel, goName),
    )
  })

  it('Plan agrees once its embedded Assessment is accounted for', () => {
    // Go embeds Assessment into Plan; TS extends it. Comparing the flattened sets keeps
    // the two spellings of the same fact comparable.
    const goPlan = [
      ...goStructJSONFields(workModel, 'Plan'),
      ...goStructJSONFields(workModel, 'Assessment'),
    ].sort()
    const tsPlan = [
      ...tsInterfaceKeys(types, 'Plan'),
      ...tsInterfaceKeys(types, 'Assessment'),
    ].sort()
    expect(tsPlan).toEqual(goPlan)
  })

  /**
   * THE DECISION ROW IS ANCHORED TO THE SCHEMA, NOT TO work_model.go, because it has no
   * Go struct: the engine serialises the store record straight out
   * (handleGenericWorkGet, work_api.go:524). Its field names therefore live in
   * work_schema.go as CONSTANTS whose names differ from their values — which is exactly
   * how this client shipped `head_state` and `decided_at` when the wire says `state`
   * and `effective_at`. Reading the constant's NAME instead of resolving its VALUE
   * produced two fields that silently arrived undefined: the decision badge never
   * showed and the revoke button was permanently hidden.
   *
   * So this case resolves the constants out of the Go source and compares the VALUES.
   */
  it('WorkDecision matches the schema field VALUES, not the constant names', () => {
    const schema = goSource('modules/sessions/work_schema.go')
    const constants = new Map<string, string>()
    for (const m of schema.matchAll(/^\s*(col[A-Za-z]+)\s*=\s*"([^"]+)"/gm)) {
      constants.set(m[1], m[2])
    }
    const block = schema.slice(
      schema.indexOf('Kind: workDecisionKind,'),
      schema.indexOf('Indexes:', schema.indexOf('Kind: workDecisionKind,')),
    )
    const fields = [...block.matchAll(/Name:\s*(col[A-Za-z]+)/g)]
      .map((m) => constants.get(m[1]))
      .filter((v): v is string => !!v)

    const ts = new Set(tsInterfaceKeys(types, 'WorkDecision'))
    for (const f of fields) {
      expect(ts.has(f), `WorkDecision is missing the wire field "${f}"`).toBe(
        true,
      )
    }
    // The head projection's state column, added onto the row at work_api.go:666.
    expect(constants.get('colDecisionHeadState')).toBe('state')
    expect(ts.has('state')).toBe(true)
    // And the two names that were wrong must not come back.
    expect(ts.has('head_state')).toBe(false)
    expect(ts.has('decided_at')).toBe(false)
  })

  it('the engine mounts twenty-seven work routes, including the nine K2 routes', () => {
    // Parsed from workRoutes, so a new endpoint or a changed permission fires here even
    // though the struct comparison above cannot see it. The K2 routes are named rather
    // than absorbed into a count: the hand-written console client does not consume them.
    const block = workApi.slice(
      workApi.indexOf('func (m *Module) workRoutes('),
      workApi.indexOf('\n}\n', workApi.indexOf('func (m *Module) workRoutes(')),
    )
    const routes = [
      ...block.matchAll(
        /reg\.Handle(?:Entity)?\("([A-Z]+)",\s*"([^"]+)",\s*(perm[A-Za-z]+)/g,
      ),
    ].map((m) => `${m[1]} ${m[2]} ${m[3]}`)
    expect(routes).toHaveLength(27)

    const k2Routes = routes.filter(
      (route) => route.includes('/lease') || route.includes('/work-events/'),
    )
    expect(k2Routes.sort()).toEqual(
      [
        'GET /leases permLeaseRead',
        'GET /work-items/{id}/lease permLeaseRead',
        'POST /work-items/{id}/lease/acquire permLeaseWrite',
        'POST /work-items/{id}/lease/clock-rebase permLeaseAdmin',
        'POST /work-items/{id}/lease/release permLeaseWrite',
        'POST /work-items/{id}/lease/renew permLeaseWrite',
        'POST /work-items/{id}/lease/revoke permLeaseAdmin',
        'POST /work-items/{id}/lease/takeover permLeaseAdmin',
        'POST /work-events/{event_id}/replay permWorkAdmin',
      ].sort(),
    )

    // Every path the client builds must be one the engine mounts. The client's paths
    // are literal in api.ts, so this is a real cross-check rather than a restatement.
    const mounted = new Set(routes.map((r) => r.split(' ')[1]))
    for (const p of [
      '/work-items',
      '/work-items/{id}',
      '/work-items/{id}/transitions',
      '/work-items/{id}/assignments',
      '/work-items/{id}/dependencies',
      '/work-items/{id}/dependencies/{dep_id}',
      '/work-items/{id}/acceptance',
      '/work-items/{id}/acceptance/{criterion_id}',
      '/work-items/{id}/events',
      '/decisions',
      '/decisions/{id}',
      '/decisions/{id}/revoke',
      '/work-stream',
    ]) {
      expect(mounted.has(p)).toBe(true)
    }
  })

  it('the work-item query allowlist is the one the client builds', () => {
    // handleWorkList answers 400 invalid_command to an unknown key, so a param the
    // client sends and the engine does not accept is a broken screen, not a no-op.
    // Anchor to the function definition: the route registration appears first, and K2
    // inserted handleWorkLeaseList between that reference and handleWorkList itself.
    const fn = workApi.indexOf('func (m *Module) handleWorkList(')
    expect(
      fn,
      'handleWorkList moved — the anchor must follow it',
    ).toBeGreaterThan(0)
    const allowed = workApi.slice(
      workApi.indexOf('allowed := map[string]bool{', fn),
    )
    const keys = [
      ...allowed.slice(0, allowed.indexOf('}')).matchAll(/"([a-z_]+)":/g),
    ].map((m) => m[1])
    const api = readFileSync(resolve(__dirname, 'api.ts'), 'utf8')
    const built = [...api.matchAll(/put\('([a-z_]+)',\s*p\./g)].map((m) => m[1])
    for (const k of built) {
      // `view` is the client's own abstraction over effective/revoked and is asserted
      // in api.test.ts; every other key it puts on a work-item query must be allowed.
      if (!keys.includes(k)) {
        expect(
          [
            'work_item_id',
            'decision_key',
            'subject_kind',
            'subject_ref',
            'decided_by_kind',
            'decided_by_ref',
          ],
          `${k} is not in the work-item allowlist and is not a decision filter`,
        ).toContain(k)
      }
    }
    expect(keys).toContain('archived')
  })
})
