// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.

package main

// The battery that proves this gate can fail.
//
// Every trap the generator exists to catch is planted on a throwaway repository and must
// produce the RIGHT answer — not merely a non-zero one. The three verdicts are distinct on
// purpose (0 in sync / 1 drift / 2 CANNOT LOOK), so each case asserts the exact code AND,
// for the red ones, that the offender is NAMED in the output. "It went red" is not
// evidence: a gate that fails for the wrong reason satisfies a whole red column while
// checking nothing.
//
// The GREEN cases are not filler either. Without them a gate that failed unconditionally
// would pass every red case above and be indistinguishable from a working one.
//
// The fixtures are whole small repositories, not mocks: the same loaders, the same parsers
// and the same renderer run over them as over the real tree. A battery that exercised a
// simplified path would prove that the simplified path works.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

// ── the fixture tree ───────────────────────────────────────────────────────────────────

// fixtureViews builds a console above the population floor: 45 registered views spread
// over the five hubs plus the five routes mounted outside the registry.
func fixtureViews() (views []string, census []string) {
	hubs := []string{"operate", "automate", "connect", "govern", "prove"}
	for i := 0; i < 45; i++ {
		id := fmt.Sprintf("view%02d", i)
		p := "/" + id
		perm := fmt.Sprintf(`"permission": "mod%02d:thing:read", `, i)
		if i == 3 {
			perm = "" // a view with no permission: any signed-in user
		}
		hide := ""
		if i == 9 {
			hide = `"hideInNav": true, `
		}
		views = append(views, fmt.Sprintf(
			`{"id": %q, "path": %q, "hub": %q, %s%s"helpHref": "/reference/fixture", "where": "web/src/features/registry.tsx:%d"}`,
			id, p, hubs[i%len(hubs)], perm, hide, 100+i))
		census = append(census, p)
	}
	return views, census
}

const fixtureStandalone = `[
  {"path": "/accept-invite", "parent": "rootRoute", "authenticated": false, "where": "web/src/app/routes.tsx:55"},
  {"path": "/login", "parent": "rootRoute", "authenticated": false, "where": "web/src/app/routes.tsx:41"},
  {"path": "/settings", "parent": "appRoute", "authenticated": true, "where": "web/src/app/routes.tsx:83"},
  {"path": "/setup", "parent": "rootRoute", "authenticated": false, "where": "web/src/app/routes.tsx:46"},
  {"path": "/status-page", "parent": "rootRoute", "authenticated": false, "where": "web/src/app/routes.tsx:62"}
]`

// The generated registration table, in the shape protoc-gen-go emits. 22 unary methods
// plus 3 streams across two files puts the fixture above the gRPC floor.
func fixtureGRPCFile(pkg, svcPrefix, metadata string, n int, withStream bool) (gen string, rpcs int) {
	var iface, desc, streams strings.Builder
	fmt.Fprintf(&iface, "type %sClient interface {\n", svcPrefix)
	for i := 0; i < n; i++ {
		fmt.Fprintf(&iface, "\tCall%02d(ctx context.Context, in *Req%02d, opts ...grpc.CallOption) (*Resp%02d, error)\n", i, i, i)
		fmt.Fprintf(&desc, "\t\t{\n\t\t\tMethodName: \"Call%02d\",\n\t\t\tHandler:    _h,\n\t\t},\n", i)
		rpcs++
	}
	if withStream {
		fmt.Fprintf(&iface, "\tWatch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tick], error)\n")
		fmt.Fprintf(&iface, "\tFeed(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Item, Receipt], error)\n")
		streams.WriteString("\t\t{\n\t\t\tStreamName:    \"Watch\",\n\t\t\tHandler:       _h,\n\t\t\tServerStreams: true,\n\t\t},\n")
		streams.WriteString("\t\t{\n\t\t\tStreamName:    \"Feed\",\n\t\t\tHandler:       _h,\n\t\t\tClientStreams: true,\n\t\t},\n")
		rpcs += 2
	}
	iface.WriteString("}\n")
	gen = fmt.Sprintf(`// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package genpb

import (
	context "context"
	grpc "google.golang.org/grpc"
)

%s
var %s_ServiceDesc = grpc.ServiceDesc{
	ServiceName: %q,
	HandlerType: (*%sServer)(nil),
	Methods: []grpc.MethodDesc{
%s	},
	Streams: []grpc.StreamDesc{
%s	},
	Metadata: %q,
}
`, iface.String(), svcPrefix, pkg+"."+svcPrefix, svcPrefix, desc.String(), streams.String(), metadata)
	return gen, rpcs
}

// fixtureProto is only ever read for the rpc CROSS-CHECK, so it carries the declarations
// and nothing else. The comment and the string literal are there on purpose: they mention
// `rpc` in places a grep would count and a token scan must not.
func fixtureProto(svc string, n int, withStream bool) string {
	var b strings.Builder
	b.WriteString("syntax = \"proto3\";\n\n")
	b.WriteString("// This comment says rpc Decoy(Empty) returns (Empty); and must not be counted.\n")
	b.WriteString("option go_package = \"example/genpb\";\n")
	b.WriteString("option (note) = \"rpc Ghost(Empty) returns (Empty);\";\n\n")
	fmt.Fprintf(&b, "service %s {\n", svc)
	for i := 0; i < n; i++ {
		fmt.Fprintf(&b, "  rpc Call%02d(Req%02d) returns (Resp%02d);\n", i, i, i)
	}
	if withStream {
		b.WriteString("  rpc Watch(WatchRequest) returns (stream Tick);\n")
		b.WriteString("  rpc Feed(stream Item) returns (Receipt);\n")
	}
	b.WriteString("}\n")
	return b.String()
}

const fixtureRelease = `package release

// Channel names.
const (
	ChannelStable   = "stable"
	ChannelSecurity = "security"
	ChannelLTS      = "lts"
)

// Channels lists the recognised channels in escalating-stability order.
var Channels = []string{ChannelStable, ChannelSecurity, ChannelLTS}
`

const fixtureCmdUpgrade = `package main

func newUpgradeCmd() *cobra.Command {
	o := &upgradeOptions{}
	cmd := &cobra.Command{Use: "upgrade"}
	f := cmd.Flags()
	f.BoolVar(&o.check, "check", false, "show the plan without swapping")
	f.StringVar(&o.channel, "channel", "stable", "release channel")
	f.StringVar(&o.bundle, "bundle", "", "install from a local bundle")
	f.StringVar(&o.pubkey, "pubkey", "", "key to verify against")
	f.BoolVar(&o.forceRollback, "force-rollback", false, "allow an older version")
	f.BoolVar(&o.ifEligible, "if-eligible", false, "only when in the cohort")
	f.BoolVar(&o.installTimer, "install-timer", false, "emit a systemd timer")
	f.StringVar(&o.timerDir, "timer-dir", "", "write the units here")
	f.StringVar(&o.timerSchedule, "timer-schedule", "Sun *-*-* 03:00:00", "OnCalendar")
	f.StringVar(&o.currentVersion, "current-version", "", "declare the installed version")
	f.StringVar(&o.target, "target", "", "binary to replace")
	f.BoolVarP(&o.assumeYes, "yes", "y", false, "do not prompt")
	return cmd
}
`

// The written guide's fixture. It prints command lines so the flag-claim check has
// something to check; two of them are the anti-vacuity control.
const fixtureUpgradePage = `---
title: fixture
---

Prose above.

## Release channels

` + "```sh" + `
olivares upgrade --check
olivares upgrade --channel security --yes
` + "```" + `

<!-- BEGIN GENERATED olivares-upgrade-channels — regenerate with ` + "`bash scripts/check-guide-docs.sh --write`" + `; do not edit by hand -->

<!-- END GENERATED olivares-upgrade-channels -->

Prose below.
`

type fixture struct {
	dir      string
	dumpPath string
	// the console dump's pieces, so a case can mutate one and rewrite it
	views      []string
	census     []string
	standalone string
	hubOrder   string
}

func (f *fixture) writeDump() error {
	body := fmt.Sprintf(`{
  "schema": %q,
  "hubOrder": %s,
  "census": ["%s"],
  "views": [%s],
  "standalone": %s
}
`, dumpSchema, f.hubOrder, strings.Join(f.census, `", "`), strings.Join(f.views, ",\n    "), f.standalone)
	return os.WriteFile(f.dumpPath, []byte(body), 0o600)
}

func write(base, rel, body string) error {
	full := filepath.Join(base, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return err
	}
	return os.WriteFile(full, []byte(body), 0o600)
}

func emptyPage(id string) string {
	return "---\ntitle: fixture\n---\n\nProse above.\n\n" + beginMarker(id) + "\n" + endMarker(id) + "\n\nProse below.\n"
}

// newFixture lays down a complete, in-sync repository.
func newFixture(base string) (*fixture, error) {
	views, census := fixtureViews()
	f := &fixture{
		dir:        base,
		dumpPath:   filepath.Join(base, "console-dump.json"),
		views:      views,
		standalone: fixtureStandalone,
		hubOrder:   `["operate", "automate", "connect", "govern", "prove"]`,
	}
	f.census = append(census, "/accept-invite", "/login", "/settings", "/setup", "/status-page")

	nav := `{"hubs": {"operate": "Operate", "automate": "Automate", "connect": "Connect", "govern": "Govern", "prove": "Prove"},
 "items": {` + navPairs("items") + `},
 "descriptions": {` + navPairs("descriptions") + `}}`
	if err := write(base, navEnRel, nav); err != nil {
		return nil, err
	}

	// The console catalog covers exactly what nav.json leaves out: the four pre-session
	// legs. Every registered view is described by the console itself.
	consoleCat := "# fixture\n" +
		"/accept-invite\tAccept an invitation\tWhere an emailed invitation link lands, with no prior session.\n" +
		"/login\tSign in\tThe credential and token sign-in page for a provisioned account.\n" +
		"/setup\tFirst-run setup\tThe one-time page that turns a fresh deployment into a usable one.\n" +
		"/status-page\tPublic status\tComponent health for people who are not signed in.\n"
	if err := write(base, consoleCatalogRel, consoleCat); err != nil {
		return nil, err
	}

	coreGen, coreRPCs := fixtureGRPCFile("fixture.api.v1", "ControlPlane", "apiv1/api.proto", 12, false)
	sdkGen, sdkRPCs := fixtureGRPCFile("fixture.sdk.v1", "PluginService", "olivaresv1/v1.proto", 10, true)
	if err := write(base, coreGRPCRel, coreGen); err != nil {
		return nil, err
	}
	if err := write(base, sdkGRPCRel, sdkGen); err != nil {
		return nil, err
	}
	if err := write(base, coreProtoRel, fixtureProto("ControlPlane", 12, false)); err != nil {
		return nil, err
	}
	if err := write(base, sdkProtoRel, fixtureProto("PluginService", 10, true)); err != nil {
		return nil, err
	}

	var grpcCat strings.Builder
	grpcCat.WriteString("# fixture\n")
	for i := 0; i < coreRPCs; i++ {
		fmt.Fprintf(&grpcCat, "/fixture.api.v1.ControlPlane/Call%02d\tDoes the %02dth thing the control plane can do for a caller.\n", i, i)
	}
	for i := 0; i < 10; i++ {
		fmt.Fprintf(&grpcCat, "/fixture.sdk.v1.PluginService/Call%02d\tDoes the %02dth thing a plugin can be asked to do.\n", i, i)
	}
	grpcCat.WriteString("/fixture.sdk.v1.PluginService/Watch\tStreams ticks to the caller until the caller goes away.\n")
	grpcCat.WriteString("/fixture.sdk.v1.PluginService/Feed\tAccepts a stream of items and answers with one receipt.\n")
	_ = sdkRPCs
	if err := write(base, grpcCatalogRel, grpcCat.String()); err != nil {
		return nil, err
	}

	if err := write(base, releaseRel, fixtureRelease); err != nil {
		return nil, err
	}
	if err := write(base, cmdUpgradeRel, fixtureCmdUpgrade); err != nil {
		return nil, err
	}

	if err := write(base, consolePageRel, emptyPage(consoleRegionID)); err != nil {
		return nil, err
	}
	if err := write(base, grpcPageRel, emptyPage(grpcRegionID)); err != nil {
		return nil, err
	}
	if err := write(base, upgradePageRel, fixtureUpgradePage); err != nil {
		return nil, err
	}
	// The page every view's helpHref points at, so the positive link check has a target.
	if err := write(base, "docs-site/src/content/docs/reference/fixture.md", "---\ntitle: fixture\n---\n"); err != nil {
		return nil, err
	}

	if err := f.writeDump(); err != nil {
		return nil, err
	}
	if rc, out := runCapturing(base, f.dumpPath, true, false); rc != 0 {
		return nil, fmt.Errorf("could not put the fixture in sync: rc=%d\n%s", rc, out)
	}
	return f, nil
}

func navPairs(kind string) string {
	var parts []string
	for i := 0; i < 45; i++ {
		id := fmt.Sprintf("view%02d", i)
		if kind == "items" {
			parts = append(parts, fmt.Sprintf("%q: %q", id, fmt.Sprintf("View %02d", i)))
		} else {
			parts = append(parts, fmt.Sprintf("%q: %q", id, fmt.Sprintf("What view %02d is for, in a sentence a reader can use.", i)))
		}
	}
	if kind == "items" {
		parts = append(parts, `"settings": "Settings"`)
	} else {
		parts = append(parts, `"settings": "Workspace and account settings"`)
	}
	return strings.Join(parts, ", ")
}

// ── the harness ────────────────────────────────────────────────────────────────────────

func runCapturing(root, dumpPath string, write, list bool) (int, string) {
	oldOut, oldErr := os.Stdout, os.Stderr
	r, w, err := os.Pipe()
	if err != nil {
		return -1, ""
	}
	os.Stdout, os.Stderr = w, w
	done := make(chan string, 1)
	go func() {
		var b strings.Builder
		buf := make([]byte, 4096)
		for {
			n, err := r.Read(buf)
			if n > 0 {
				b.Write(buf[:n])
			}
			if err != nil {
				break
			}
		}
		done <- b.String()
	}()
	rc, runErr := run(root, dumpPath, write, list)
	if runErr != nil {
		if isCannotLook(runErr) {
			fmt.Fprintf(os.Stderr, "guide-docs: CANNOT LOOK — %v\n", runErr)
			rc = 2
		} else {
			fmt.Fprintf(os.Stderr, "guide-docs: %v\n", runErr)
			rc = 2
		}
	}
	_ = w.Close()
	out := <-done
	_ = r.Close()
	os.Stdout, os.Stderr = oldOut, oldErr
	return rc, out
}

type caseResult struct {
	name   string
	wantRC int
	gotRC  int
	needle string
	out    string
}

func (c caseResult) ok() bool {
	return c.gotRC == c.wantRC && (c.needle == "" || strings.Contains(c.out, c.needle))
}

// stage1Script is where the wrapper says console-dump.mjs lives.
var stage1Script string

func runSelfTest() int {
	base, err := os.MkdirTemp("", "guide-docs-selftest-")
	if err != nil {
		fmt.Fprintf(os.Stderr, "guide-docs self-test: CANNOT LOOK — no scratch dir: %v\n", err)
		return 2
	}
	defer func() { _ = os.RemoveAll(base) }()

	var results []caseResult
	n := 0
	newTree := func(mutate func(*fixture) error) (*fixture, error) {
		n++
		f, err := newFixture(filepath.Join(base, fmt.Sprintf("t%02d", n)))
		if err != nil {
			return nil, err
		}
		if mutate != nil {
			if err := mutate(f); err != nil {
				return nil, err
			}
		}
		return f, nil
	}
	add := func(name string, wantRC int, needle string, mutate func(*fixture) error) {
		f, err := newTree(mutate)
		if err != nil {
			results = append(results, caseResult{name: name, wantRC: wantRC, gotRC: -1, out: err.Error()})
			return
		}
		rc, out := runCapturing(f.dir, f.dumpPath, false, false)
		results = append(results, caseResult{name: name, wantRC: wantRC, gotRC: rc, needle: needle, out: out})
	}

	// ── GREEN ──────────────────────────────────────────────────────────────────────────
	add("in-sync-tree", 0, "all published and in sync", nil)

	// Regeneration must be a fixed point: a page that churns on every run makes every
	// later diff unreadable and trains a reviewer to skip it.
	n++
	if f, err := newFixture(filepath.Join(base, fmt.Sprintf("t%02d", n))); err == nil {
		before := map[string]string{}
		for _, rel := range []string{consolePageRel, grpcPageRel, upgradePageRel} {
			raw, _ := os.ReadFile(filepath.Join(f.dir, rel))
			before[rel] = string(raw)
		}
		runCapturing(f.dir, f.dumpPath, true, false)
		rc := 0
		var which string
		for _, rel := range []string{consolePageRel, grpcPageRel, upgradePageRel} {
			raw, _ := os.ReadFile(filepath.Join(f.dir, rel))
			if string(raw) != before[rel] {
				rc, which = 1, rel
			}
		}
		results = append(results, caseResult{name: "regeneration-is-a-fixed-point", wantRC: 0, gotRC: rc, out: which})
	} else {
		results = append(results, caseResult{name: "regeneration-is-a-fixed-point", wantRC: 0, gotRC: -1, out: err.Error()})
	}

	// Some properties are invisible in an exit code: they are facts about the PAGE. These
	// assert on the rendered bytes, because a gate that only ever compared a region with
	// itself would be green over a table of empty cells.
	page := func(name, rel, needle string) {
		f, err := newTree(nil)
		if err != nil {
			results = append(results, caseResult{name: name, wantRC: 0, gotRC: -1, out: err.Error()})
			return
		}
		raw, err := os.ReadFile(filepath.Join(f.dir, rel))
		if err != nil {
			results = append(results, caseResult{name: name, wantRC: 0, gotRC: -1, out: err.Error()})
			return
		}
		results = append(results, caseResult{name: name, wantRC: 0, gotRC: 0, needle: needle, out: string(raw)})
	}

	// A view with NO permission is a real shape (two exist in the real console) and must
	// render as "any signed-in user", not as an empty cell that reads like a missing value.
	page("no-permission-renders-as-any-user", consolePageRel, "| any signed-in user |")

	// The pre-session legs must be marked. If this cell were blank, the page would
	// describe /login as needing the same sign-in it exists to perform.
	page("public-legs-are-marked", consolePageRel, "**no sign-in**")

	// A deep-link-only screen must SAY so: its path 404s if it is typed literally, and a
	// table that printed it like any other route would send a reader to a dead end.
	page("deep-link-only-is-marked", consolePageRel, "(deep link only)")

	// The streaming shape is the one thing a client author cannot guess from a name.
	page("streaming-kinds-are-published", grpcPageRel, "server-streaming")
	page("client-streaming-is-published", grpcPageRel, "client-streaming")

	// The `rpc` tokens inside a comment and inside a string in the .proto must NOT be
	// counted, or the cross-check reports a mismatch on a tree that is perfectly in sync.
	// This is the green half of the mutant M11 below.
	add("proto-decoys-are-not-counted", 0, "all published and in sync", nil)

	// ── RED: the roster moved and the page did not ─────────────────────────────────────
	add("route-added-not-regenerated", 1, "/view99", func(f *fixture) error {
		f.views = append(f.views, `{"id": "view99", "path": "/view99", "hub": "operate", "permission": "mod99:thing:read", "helpHref": "/reference/fixture", "where": "web/src/features/registry.tsx:999"}`)
		f.census = append(f.census, "/view99")
		return f.writeDump()
	})

	add("route-removed-still-published", 1, "/view44", func(f *fixture) error {
		f.views = f.views[:len(f.views)-1] // drops view44
		out := f.census[:0]
		for _, p := range f.census {
			if p != "/view44" {
				out = append(out, p)
			}
		}
		f.census = out
		return f.writeDump()
	})

	add("rpc-added-not-regenerated", 1, "/fixture.api.v1.ControlPlane/Call12", func(f *fixture) error {
		gen, _ := fixtureGRPCFile("fixture.api.v1", "ControlPlane", "apiv1/api.proto", 13, false)
		if err := write(f.dir, coreGRPCRel, gen); err != nil {
			return err
		}
		if err := write(f.dir, coreProtoRel, fixtureProto("ControlPlane", 13, false)); err != nil {
			return err
		}
		return appendLine(f.dir, grpcCatalogRel,
			"/fixture.api.v1.ControlPlane/Call12\tDoes the twelfth thing the control plane can do for a caller.\n")
	})

	add("channel-added-not-regenerated", 1, "`edge`", func(f *fixture) error {
		return write(f.dir, releaseRel, strings.Replace(
			strings.Replace(fixtureRelease, `ChannelLTS      = "lts"`, "ChannelLTS      = \"lts\"\n\tChannelEdge     = \"edge\"", 1),
			"ChannelStable, ChannelSecurity, ChannelLTS}", "ChannelStable, ChannelSecurity, ChannelLTS, ChannelEdge}", 1))
	})

	// The roster can be intact while a DESCRIPTION moves. Without this case the gate
	// would only be a route counter, and the sentence a reader actually uses could rot.
	add("description-changed-not-regenerated", 1, "a description, a permission or a type moved", func(f *fixture) error {
		nav, err := os.ReadFile(filepath.Join(f.dir, navEnRel))
		if err != nil {
			return err
		}
		return write(f.dir, navEnRel, strings.Replace(string(nav),
			"What view 00 is for, in a sentence a reader can use.",
			"Something else entirely, and a reader would never know.", 1))
	})

	// ── RED: the hand-written catalog and the tree disagree, BOTH directions ───────────
	add("view-with-no-description-anywhere", 1, "supplies none — add a row", func(f *fixture) error {
		nav, err := os.ReadFile(filepath.Join(f.dir, navEnRel))
		if err != nil {
			return err
		}
		return write(f.dir, navEnRel, strings.Replace(string(nav),
			`"view07": "What view 07 is for, in a sentence a reader can use."`, `"view07": ""`, 1))
	})

	add("catalog-row-for-a-route-that-does-not-exist", 1, "/ghost-screen", func(f *fixture) error {
		return appendLine(f.dir, consoleCatalogRel,
			"/ghost-screen\tGhost\tA screen that was retired two releases ago and is still described.\n")
	})

	add("catalog-shadows-the-console-s-own-words", 1, "the console already describes it", func(f *fixture) error {
		return appendLine(f.dir, consoleCatalogRel,
			"/view01\t-\tA second, different description of a screen the console already describes.\n")
	})

	add("rpc-with-no-catalog-row", 1, "has no row in", func(f *fixture) error {
		raw, err := os.ReadFile(filepath.Join(f.dir, grpcCatalogRel))
		if err != nil {
			return err
		}
		var kept []string
		for _, l := range strings.Split(string(raw), "\n") {
			if !strings.HasPrefix(l, "/fixture.sdk.v1.PluginService/Watch\t") {
				kept = append(kept, l)
			}
		}
		return write(f.dir, grpcCatalogRel, strings.Join(kept, "\n"))
	})

	add("catalog-row-for-an-rpc-that-was-removed", 1, "no generated descriptor registers it", func(f *fixture) error {
		return appendLine(f.dir, grpcCatalogRel,
			"/fixture.sdk.v1.PluginService/Vanished\tA method that was renamed and whose description outlived it.\n")
	})

	add("summary-left-as-todo", 1, "regenerating would publish the placeholder", func(f *fixture) error {
		raw, err := os.ReadFile(filepath.Join(f.dir, consoleCatalogRel))
		if err != nil {
			return err
		}
		return write(f.dir, consoleCatalogRel, strings.Replace(string(raw),
			"The credential and token sign-in page for a provisioned account.", "TODO", 1))
	})

	// A THIRD generated registration table appearing in the tree is a service surface this
	// gate does not read. Counting only the two it knows about would keep every number
	// correct and the new service undocumented — the exact shape of the defect this whole
	// gate exists to remove.
	add("a-third-grpc-source-appears", 1, "served and undocumented", func(f *fixture) error {
		gen, _ := fixtureGRPCFile("fixture.extra.v1", "ExtraService", "extrav1/extra.proto", 3, false)
		return write(f.dir, "modules/extra/genpb/extrav1/extra_grpc.pb.go", gen)
	})

	// The Metadata field names the contract the table was generated from. Paired with the
	// wrong .proto, the rpc cross-check below compares two unrelated numbers and reports a
	// tree as in sync whenever they happen to agree.
	add("generated-table-names-a-different-contract", 2, "the pairing is wrong", func(f *fixture) error {
		gen, _ := fixtureGRPCFile("fixture.api.v1", "ControlPlane", "somewhere/else.proto", 12, false)
		return write(f.dir, coreGRPCRel, gen)
	})

	// ── RED: the contract and the generated code disagree ──────────────────────────────
	add("proto-edited-without-regenerating", 1, "run buf generate", func(f *fixture) error {
		return write(f.dir, coreProtoRel, fixtureProto("ControlPlane", 14, false))
	})

	// ── RED: the written guide's claims ────────────────────────────────────────────────
	add("guide-documents-a-flag-that-does-not-exist", 1, "--dry-run", func(f *fixture) error {
		raw, err := os.ReadFile(filepath.Join(f.dir, upgradePageRel))
		if err != nil {
			return err
		}
		return write(f.dir, upgradePageRel, strings.Replace(string(raw),
			"olivares upgrade --check", "olivares upgrade --check --dry-run", 1))
	})

	// ANTI-VACUITY: the flag check must fail when it had nothing to check, not pass.
	add("guide-with-no-command-line-at-all", 1, "verified nothing at all", func(f *fixture) error {
		raw, err := os.ReadFile(filepath.Join(f.dir, upgradePageRel))
		if err != nil {
			return err
		}
		s := strings.Replace(string(raw), "olivares upgrade --check\n", "", 1)
		s = strings.Replace(s, "olivares upgrade --channel security --yes\n", "", 1)
		return write(f.dir, upgradePageRel, s)
	})

	// ── RED: the console mounts something the census does not record ───────────────────
	add("route-mounted-and-not-in-the-census", 1, "does not record it", func(f *fixture) error {
		f.views = append(f.views, `{"id": "sneak", "path": "/sneak", "hub": "operate", "permission": "x:y:read", "helpHref": "/reference/fixture", "where": "web/src/features/registry.tsx:1234"}`)
		return f.writeDump()
	})

	add("census-records-a-route-nothing-mounts", 1, "the route was lost", func(f *fixture) error {
		f.census = append(f.census, "/orphaned")
		return f.writeDump()
	})

	add("in-product-help-points-at-a-page-that-does-not-exist", 1, "no page publishes that route", func(f *fixture) error {
		return os.Remove(filepath.Join(f.dir, "docs-site/src/content/docs/reference/fixture.md"))
	})

	// ── CANNOT LOOK (exit 2), never a quiet green ──────────────────────────────────────
	add("page-lost-its-markers", 2, "could not be located", func(f *fixture) error {
		raw, err := os.ReadFile(filepath.Join(f.dir, consolePageRel))
		if err != nil {
			return err
		}
		return write(f.dir, consolePageRel, strings.Replace(string(raw), beginMarker(consoleRegionID), "", 1))
	})

	add("page-has-two-regions", 2, "copies of the", func(f *fixture) error {
		raw, err := os.ReadFile(filepath.Join(f.dir, grpcPageRel))
		if err != nil {
			return err
		}
		return write(f.dir, grpcPageRel, string(raw)+"\n"+beginMarker(grpcRegionID)+"\n"+endMarker(grpcRegionID)+"\n")
	})

	add("page-is-missing-entirely", 2, "could not be read", func(f *fixture) error {
		return os.Remove(filepath.Join(f.dir, upgradePageRel))
	})

	add("catalog-missing", 2, "could not be read", func(f *fixture) error {
		return os.Remove(filepath.Join(f.dir, consoleCatalogRel))
	})

	add("catalog-empty", 2, "carries no rows at all", func(f *fixture) error {
		return write(f.dir, grpcCatalogRel, "# every row deleted\n")
	})

	add("dump-below-the-population-floor", 2, "below the floor", func(f *fixture) error {
		f.views = f.views[:5]
		f.census = f.census[:5]
		return f.writeDump()
	})

	add("dump-speaks-another-schema", 2, "this gate speaks", func(f *fixture) error {
		raw, err := os.ReadFile(f.dumpPath)
		if err != nil {
			return err
		}
		return os.WriteFile(f.dumpPath, []byte(strings.Replace(string(raw), dumpSchema, "olivares.console.routes/2", 1)), 0o600)
	})

	add("dump-absent", 2, "stage 1", func(f *fixture) error {
		return os.Remove(f.dumpPath)
	})

	// The walk catches this before the parse does, and its message is the better one:
	// "declared as a source and the walk did not find it" says the surface was not
	// enumerated, where a parse error would only say a file was unreadable.
	add("generated-grpc-file-absent", 2, "the walk did not find it", func(f *fixture) error {
		return os.Remove(filepath.Join(f.dir, sdkGRPCRel))
	})

	add("registration-table-disagrees-with-its-own-client-interface", 2, "inconsistent with itself", func(f *fixture) error {
		raw, err := os.ReadFile(filepath.Join(f.dir, coreGRPCRel))
		if err != nil {
			return err
		}
		return write(f.dir, coreGRPCRel, strings.Replace(string(raw),
			`MethodName: "Call03"`, `MethodName: "CallGhost"`, 1))
	})

	add("release-channels-unreadable", 2, "below the floor", func(f *fixture) error {
		return write(f.dir, releaseRel, "package release\n\nvar Channels = []string{}\n")
	})

	add("upgrade-flags-unreadable", 2, "below the floor", func(f *fixture) error {
		return write(f.dir, cmdUpgradeRel, "package main\n\nfunc newUpgradeCmd() *cobra.Command { return nil }\n")
	})

	// ── --write must refuse to publish a roster that did not survive the join ──────────
	// A generator that "fixed" a red tree by regenerating it would publish a page missing
	// exactly the screens the findings are about, and the next check would be GREEN.
	//
	// THESE TWO LEGS ASSERT THE PAGE, AND UNTIL 2026-08-17 THIS ONE ASSERTED THE EXIT
	// CODE. It planted a catalog row for a screen the census does not carry and then
	// checked that --write still exited 1 and still named /ghost-screen. Both stay true
	// with `if len(s.findings) > 0 && write` DELETED from console.go and grpcref.go: the
	// finding is a pre-finding either way, and that fixture renders the identical region
	// with and without the refusal, so no behaviour of applyConsole could have failed the
	// leg. Measured: a mutant that removed the refusal from both files survived the whole
	// battery — the one guard whose name was written on a case nobody had made
	// discriminating. The fixtures below are chosen so the two behaviours produce
	// DIFFERENT BYTES, which is the only way a leg can testify about a page.
	//
	// Console: a view whose nav label is gone is DROPPED from the roster (join reports it
	// and skips the row), so a --write that went ahead would publish a console reference
	// short by one screen while reporting the label as the problem.
	n++
	if f, err := newFixture(filepath.Join(base, fmt.Sprintf("t%02d", n))); err == nil {
		results = append(results, writeRefusalCase("write-refuses-to-paper-over-findings", f,
			consolePageRel, "/view03 has no label", "`/view03` is published in",
			"--write rewrote the console reference while a finding was outstanding; the published page would be short by /view03",
			func() error {
				raw, rerr := os.ReadFile(filepath.Join(f.dir, navEnRel))
				if rerr != nil {
					return rerr
				}
				body := strings.Replace(string(raw), `"view03": "View 03", `, "", 1)
				if body == string(raw) {
					return fmt.Errorf("the fixture's nav catalog no longer spells view03's label; this leg would test nothing")
				}
				return write(f.dir, navEnRel, body)
			}))
	} else {
		results = append(results, caseResult{name: "write-refuses-to-paper-over-findings", wantRC: 1, gotRC: -1, out: err.Error()})
	}

	// gRPC: the same guard lives in applyGRPC and needs its own fixture, or a mutant that
	// removed only that copy would still survive. An rpc with no catalog row renders with
	// an EMPTY "What it does" cell, so a --write that went ahead would publish a reference
	// table with a blank sentence in it.
	n++
	if f, err := newFixture(filepath.Join(base, fmt.Sprintf("t%02d", n))); err == nil {
		results = append(results, writeRefusalCase("write-refuses-to-publish-an-undescribed-rpc", f,
			grpcPageRel, "has no row in", "no longer matches what the tree produces",
			"--write rewrote the gRPC reference while a finding was outstanding; the published table would carry an empty description",
			func() error {
				raw, rerr := os.ReadFile(filepath.Join(f.dir, grpcCatalogRel))
				if rerr != nil {
					return rerr
				}
				var kept []string
				dropped := false
				for _, l := range strings.Split(string(raw), "\n") {
					if strings.HasPrefix(l, "/fixture.api.v1.ControlPlane/Call03\t") {
						dropped = true
						continue
					}
					kept = append(kept, l)
				}
				if !dropped {
					return fmt.Errorf("the fixture's gRPC catalog no longer describes Call03; this leg would test nothing")
				}
				return write(f.dir, grpcCatalogRel, strings.Join(kept, "\n"))
			}))
	} else {
		results = append(results, caseResult{name: "write-refuses-to-publish-an-undescribed-rpc", wantRC: 1, gotRC: -1, out: err.Error()})
	}

	// ── stage 1's own refusals, executed ──────────────────────────────────────────────
	results = append(results, stage1Cases(base, stage1Script)...)

	// ── report ─────────────────────────────────────────────────────────────────────────
	// A case whose output carries the gate's own CANNOT LOOK refusal did not misbehave: it never
	// ran. Line 38 of check-guide-docs.sh states the doctrine this harness has to obey — "2 CANNOT
	// LOOK. Never two: an enumeration that did not run is not 'in sync'" — and until 2026-08-23 the
	// harness itself broke it, reporting exit 1 ("these cases are broken") for cases the box could
	// not execute.
	//
	// Measured that day on a worktree without web/node_modules: five stage-1 cases refused with
	// "no TypeScript compiler under web/node_modules or node_modules" and the summary read
	// "5 of 46 cases misbehaved". Nothing misbehaved. The CI runners install the dependencies, so
	// the false red only ever appears on a developer box — which is exactly where it teaches
	// people to ignore this gate.
	//
	// Strictness is unchanged: blocked still exits non-zero, so nothing that used to stop a push
	// stops being stopped. Only the LABEL changes, from "broken" to "could not look".
	bad, blocked := 0, 0
	for _, c := range results {
		if c.ok() {
			continue
		}
		if strings.Contains(c.out, "CANNOT LOOK") {
			blocked++
			fmt.Fprintf(os.Stderr, "guide-docs self-test: COULD NOT LOOK %s — the case never ran\n", c.name)
			for _, line := range strings.Split(strings.TrimSpace(c.out), "\n") {
				fmt.Fprintf(os.Stderr, "    %s\n", line)
			}
			continue
		}
		bad++
		fmt.Fprintf(os.Stderr, "guide-docs self-test: FAIL %s — wanted exit %d, got %d", c.name, c.wantRC, c.gotRC)
		if c.needle != "" && !strings.Contains(c.out, c.needle) {
			fmt.Fprintf(os.Stderr, "; the output never named %q", c.needle)
		}
		fmt.Fprintln(os.Stderr)
		for _, line := range strings.Split(strings.TrimSpace(c.out), "\n") {
			fmt.Fprintf(os.Stderr, "    %s\n", line)
		}
	}
	red, green := 0, 0
	for _, c := range results {
		if c.wantRC == 0 {
			green++
		} else {
			red++
		}
	}
	if bad > 0 {
		fmt.Fprintf(os.Stderr, "guide-docs self-test: %d of %d cases misbehaved.\n", bad, len(results))
		return 1
	}
	if blocked > 0 {
		fmt.Fprintf(os.Stderr, "guide-docs self-test: COULD NOT LOOK — %d of %d cases never ran; the rest behaved.\n", blocked, len(results))
		return 2
	}
	fmt.Printf("guide-docs self-test: %d cases, every red case red and every green case green (%d red, %d green).\n",
		len(results), red, green)
	return 0
}

// writeRefusalCase runs one --write refusal: it snapshots the page, applies the mutation,
// runs --write, and passes only if the run exited 1, NAMED the finding and left the page
// BYTE-IDENTICAL. The bytes are the assertion that matters — an exit code proves the run
// reported something, never that it kept its hands off the published file, and that
// difference is what let a mutant delete the refusal and survive.
//
// regionNeedle is the CONTROL, and without it this leg would be back where it started: an
// untouched page proves nothing unless the region WOULD otherwise have changed, so a
// read-only run over the same tree has to report the difference too. A fixture that fails
// that control is inert, and an inert fixture reports "refused" for a run that had nothing
// to refuse.
func writeRefusalCase(name string, f *fixture, pageRel, needle, regionNeedle, byteFailure string, mutate func() error) caseResult {
	before, err := os.ReadFile(filepath.Join(f.dir, pageRel))
	if err != nil {
		return caseResult{name: name, wantRC: 1, gotRC: -1, out: err.Error()}
	}
	if err := mutate(); err != nil {
		return caseResult{name: name, wantRC: 1, gotRC: -1, out: err.Error()}
	}
	rcCheck, outCheck := runCapturing(f.dir, f.dumpPath, false, false)
	if rcCheck != 1 || !strings.Contains(outCheck, regionNeedle) {
		return caseResult{name: name, wantRC: 1, gotRC: -1,
			out: "the fixture does not make the published region differ (read-only run: rc=" +
				fmt.Sprint(rcCheck) + ", never named " + strconv.Quote(regionNeedle) +
				"), so this leg cannot tell the refusal from its absence\n" + outCheck}
	}
	rc, out := runCapturing(f.dir, f.dumpPath, true, false)
	after, err := os.ReadFile(filepath.Join(f.dir, pageRel))
	if err != nil {
		return caseResult{name: name, wantRC: 1, gotRC: -1, out: err.Error()}
	}
	if string(after) != string(before) {
		return caseResult{name: name, wantRC: 1, gotRC: -1, out: byteFailure + "\n" + out}
	}
	return caseResult{name: name, wantRC: 1, gotRC: rc, needle: needle, out: out}
}

func appendLine(base, rel, line string) error {
	full := filepath.Join(base, rel)
	raw, err := os.ReadFile(full)
	if err != nil {
		return err
	}
	body := string(raw)
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	return os.WriteFile(full, []byte(body+line), 0o600)
}

// ── stage 1 (the TypeScript dumper) ────────────────────────────────────────────────────
//
// The dumper is a separate process in another language, so it gets its own cases: it is
// the half that can fail by reporting a SHORT roster, which is the failure this whole gate
// is least able to survive. They run it for real — a battery that asserted what the script
// "would" do is a battery that tests this file's opinion of it.

// The registry fixture clears the dumper's own population floor (its whole job is to
// refuse a roster that is too small to be a console), and carries the two shapes that
// matter: an entry hidden inside a COMMENT, which a compiler must not see, and one entry
// whose permission is absent rather than computed.
func stage1RegistrySrc(perm string) string {
	var b strings.Builder
	b.WriteString("import { lazy } from 'react'\n")
	b.WriteString("export const HUB_ORDER: HubId[] = ['operate', 'automate', 'connect', 'govern', 'prove']\n")
	b.WriteString("export const FEATURE_VIEWS: FeatureView[] = [\n")
	fmt.Fprintf(&b, "  { id: 'alpha', path: '/alpha', hub: 'operate', helpHref: '/reference/fixture', permission: %s, element: lazyView(A) },\n", perm)
	b.WriteString("  // A commented-out entry: { id: 'ghost', path: '/ghost', permission: 'ghost:read' }\n")
	b.WriteString("  { id: 'beta', path: '/beta', hub: 'govern', helpHref: '/reference/fixture', element: lazyView(B) },\n")
	for i := 0; i < 24; i++ {
		fmt.Fprintf(&b, "  { id: 'bulk%02d', path: '/bulk%02d', hub: 'prove', helpHref: '/reference/fixture', permission: 'bulk:read', element: lazyView(C) },\n", i, i)
	}
	b.WriteString("]\n")
	return b.String()
}

const stage1Routes = `export const rootRoute = createRootRoute({ component: () => <Outlet /> })
const loginRoute = createRoute({ getParentRoute: () => rootRoute, path: '/login', component: LoginPage })
const settingsRoute = createRoute({ getParentRoute: () => appRoute, path: '/settings', component: SettingsPage })
`

// stage1Cases runs the dumper for real. `script` is passed in by the wrapper rather than
// guessed from the working directory: a path this program guessed wrong would make every
// case below unrunnable, and an unrunnable case that reports itself as skipped is the
// silent pass this battery exists to prevent. Hence — no skip. If the script or node is
// not there, these are FAILURES.
func stage1Cases(base, script string) []caseResult {
	var out []caseResult
	if script == "" || !fileExists(script) {
		return []caseResult{{name: "stage1/script-found", wantRC: 0, gotRC: 1,
			out: fmt.Sprintf("console-dump.mjs was not at %q, so stage 1's refusals were never executed. "+
				"Pass -stage1 <path>; the wrapper does.", script)}}
	}
	if _, err := exec.LookPath("node"); err != nil {
		return []caseResult{{name: "stage1/node-available", wantRC: 0, gotRC: 1,
			out: "no node on PATH, so stage 1's refusals were never executed"}}
	}
	// <root>/scripts/guide-docs/console-dump.mjs -> <root>/web/node_modules
	repoRoot := filepath.Dir(filepath.Dir(filepath.Dir(script)))

	mk := func(name string, mutate func(dir string) error) (string, error) {
		dir := filepath.Join(base, "s1-"+name)
		if err := write(dir, "web/src/features/registry.tsx", stage1RegistrySrc("'a:b:read'")); err != nil {
			return "", err
		}
		if err := write(dir, "web/src/app/routes.tsx", stage1Routes); err != nil {
			return "", err
		}
		if err := write(dir, censusRel, stage1Census()); err != nil {
			return "", err
		}
		// The compiler the console is built with. The fixture borrows the real tree's
		// node_modules by symlink rather than shipping a second copy.
		if realWeb := filepath.Join(repoRoot, "web", "node_modules"); fileExists(realWeb) {
			_ = os.Symlink(realWeb, filepath.Join(dir, "web", "node_modules"))
		}
		if mutate != nil {
			if err := mutate(dir); err != nil {
				return "", err
			}
		}
		return dir, nil
	}
	run1 := func(name string, wantRC int, needle string, mutate func(string) error) {
		dir, err := mk(name, mutate)
		if err != nil {
			out = append(out, caseResult{name: "stage1/" + name, wantRC: wantRC, gotRC: -1, out: err.Error()})
			return
		}
		cmd := exec.Command("node", script, "--root", dir)
		combined, _ := cmd.CombinedOutput()
		rc := cmd.ProcessState.ExitCode()
		out = append(out, caseResult{name: "stage1/" + name, wantRC: wantRC, gotRC: rc, needle: needle, out: string(combined)})
	}

	// GREEN: a tiny but well-formed console dumps, and the entry hidden inside a comment
	// is NOT in it — the whole reason this stage uses a compiler.
	run1("well-formed-console-dumps", 0, `"path": "/beta"`, nil)

	// RED: the registry stopped being an array literal, so nothing could be enumerated.
	run1("registry-is-not-an-array", 2, "not as an array literal", func(dir string) error {
		return write(dir, "web/src/features/registry.tsx",
			"export const HUB_ORDER: HubId[] = ['operate']\nexport const FEATURE_VIEWS: FeatureView[] = buildViews()\n")
	})

	// RED: the roster shrank to a handful. A dumper that emitted it would let the Go half
	// regenerate a four-screen console over a fifty-screen one and call it in sync.
	run1("roster-below-the-population-floor", 2, "not a console", func(dir string) error {
		return write(dir, "web/src/features/registry.tsx",
			"export const HUB_ORDER: HubId[] = ['operate']\nexport const FEATURE_VIEWS: FeatureView[] = [\n"+
				"  { id: 'alpha', path: '/alpha', hub: 'operate', helpHref: '/x', element: lazyView(A) },\n]\n")
	})

	// RED: a permission written as an expression. "Computed and unreadable" must never
	// collapse into "this view needs no permission" — they are opposite facts.
	run1("permission-is-a-computed-expression", 2, "non-literal expression", func(dir string) error {
		return write(dir, "web/src/features/registry.tsx", stage1RegistrySrc("PERMS.alpha"))
	})

	// RED: the census went missing. Without it there is no roster to cover.
	run1("census-missing", 2, "no route roster", func(dir string) error {
		return os.Remove(filepath.Join(dir, censusRel))
	})
	return out
}

func stage1Census() string {
	paths := []string{"/alpha", "/beta", "/login", "/settings"}
	for i := 0; i < 24; i++ {
		paths = append(paths, fmt.Sprintf("/bulk%02d", i))
	}
	return `{"paths": ["` + strings.Join(paths, `", "`) + `"]}`
}

func fileExists(p string) bool {
	_, err := os.Lstat(p)
	return err == nil
}
