// SPDX-FileCopyrightText: 2026 Olivares.AI
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPL-3.0-only section 7(a) disclaim warranty and limit liability: see DISCLAIMER.md at the repository root.
//
// Deterministic voice fixtures shaped exactly like the contract — used by the
// component tests and the visual e2e route mocks. They contain NO audio, NO
// transcription text, NO prompt and NO PII: a `transcript_ref_hash` is a 64-hex
// fingerprint of an external locator only. The set is deliberately mixed: a live
// governed session, an idle one, an ended one, and an UNGOVERNED open (the
// anti-evasion case the honesty test asserts is flagged).
import type { VoiceDecision, VoicePolicy, VoiceSession } from './types'

export const sessionsFixture: VoiceSession[] = [
  {
    id: 'vs-0001',
    session_ref: 'sess-live-01',
    agent_ref: 'support-voice',
    model_ref: 'gpt-4o-realtime',
    provider_ref: 'openai',
    principal_ref: 'user:fran',
    policy_ref: 'vp-default',
    language_code: 'es-ES',
    state: 'live',
    user_turns: 7,
    agent_turns: 7,
    turn_count: 14,
    duration_ms: 184_000,
    latency_avg_ms: 132,
    latency_max_ms: 410,
    governed: true,
    transcript_ref_hash:
      'a1b2c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff00',
    first_event_at: '2026-06-04T11:58:00Z',
    last_event_at: '2026-06-04T12:01:04Z',
    closed_reason: '',
    created_at: '2026-06-04T11:58:00Z',
  },
  {
    id: 'vs-0002',
    session_ref: 'sess-idle-02',
    agent_ref: 'concierge-voice',
    model_ref: 'gemini-2.0-flash-live',
    provider_ref: 'google',
    principal_ref: 'user:ana',
    policy_ref: 'vp-default',
    language_code: 'en-US',
    state: 'idle',
    user_turns: 3,
    agent_turns: 4,
    turn_count: 7,
    duration_ms: 96_000,
    latency_avg_ms: 188,
    latency_max_ms: 520,
    governed: true,
    transcript_ref_hash:
      'ffeeddccbbaa00998877665544332211aabbccddeeff00112233445566778899',
    first_event_at: '2026-06-04T10:40:00Z',
    last_event_at: '2026-06-04T10:41:36Z',
    closed_reason: '',
    created_at: '2026-06-04T10:40:00Z',
  },
  {
    id: 'vs-0003',
    session_ref: 'sess-ended-03',
    agent_ref: 'support-voice',
    model_ref: 'gpt-4o-realtime',
    provider_ref: 'openai',
    principal_ref: 'user:fran',
    policy_ref: 'vp-default',
    language_code: 'es-ES',
    state: 'ended',
    user_turns: 11,
    agent_turns: 12,
    turn_count: 23,
    duration_ms: 612_000,
    latency_avg_ms: 119,
    latency_max_ms: 290,
    governed: true,
    transcript_ref_hash:
      '0011223344556677889900aabbccddeeff112233445566778899aabbccddeeff',
    first_event_at: '2026-06-03T18:02:00Z',
    last_event_at: '2026-06-03T18:12:12Z',
    closed_reason: 'completed',
    created_at: '2026-06-03T18:02:00Z',
  },
  {
    // The anti-evasion case: an open that bypassed gating. Flagged, never hidden.
    id: 'vs-0004',
    session_ref: 'sess-ungov-04',
    agent_ref: 'shadow-agent',
    model_ref: 'claude-haiku-4-5',
    provider_ref: 'anthropic',
    principal_ref: 'user:contractor',
    policy_ref: '',
    language_code: 'en-GB',
    state: 'ended',
    user_turns: 2,
    agent_turns: 2,
    turn_count: 4,
    duration_ms: 41_000,
    latency_avg_ms: 240,
    latency_max_ms: 980,
    governed: false,
    transcript_ref_hash:
      '99aabbccddeeff00112233445566778899aabbccddeeff001122334455667788',
    first_event_at: '2026-06-03T09:15:00Z',
    last_event_at: '2026-06-03T09:15:41Z',
    closed_reason: 'client_hangup',
    created_at: '2026-06-03T09:15:00Z',
  },
]

export const policiesFixture: VoicePolicy[] = [
  {
    id: 'vp-default',
    agent_ref: '*',
    allowed_model_ref: '*',
    allowed_provider_ref: 'openai',
    max_session_minutes: 30,
    max_latency_ms: 400,
    set_by: 'user:fran',
    updated_at: '2026-06-01T08:00:00Z',
  },
  {
    id: 'vp-support',
    agent_ref: 'support-voice',
    allowed_model_ref: 'gpt-4o-realtime',
    allowed_provider_ref: 'openai',
    max_session_minutes: 15,
    max_latency_ms: 300,
    set_by: 'user:ana',
    updated_at: '2026-06-02T14:30:00Z',
  },
]

// El ledger de aperturas, mezclado A PROPÓSITO por desenlace, porque lo que esta
// pantalla tiene que distinguir son los desenlaces y no las filas: una despachada, una
// bloqueada por falta de política —la que NO tiene sesión que la aloje—, una bloqueada
// por presupuesto y una limitada. Ninguna lleva contenido: refs, actor y el texto que
// redacta el motor.
export const decisionsFixture: VoiceDecision[] = [
  {
    id: 'vd-0001',
    session_ref: 'sess-live-01',
    agent_ref: 'support-voice',
    requested_model_ref: 'gpt-4o-realtime',
    requested_provider_ref: 'openai',
    policy_ref: 'vp-0001',
    op: 'open',
    policy_verdict: 'allowed',
    plan_hash: 'b7f0c1a2',
    approval_ref: 'appr-118',
    gate_status: 'approved',
    op_status: 'dispatched',
    dispatch_ref: 'rt-118',
    actor: 'user:fran',
    actor_kind: 'user',
    result: 'dispatched to the realtime plane',
    occurred_at: '2026-08-20T09:14:00Z',
  },
  {
    id: 'vd-0002',
    session_ref: 'sess-ghost-77',
    agent_ref: 'shadow-agent',
    requested_model_ref: 'gpt-4o-realtime',
    requested_provider_ref: 'openai',
    op: 'open_request',
    policy_verdict: 'denied',
    gate_status: 'none',
    op_status: 'blocked',
    actor: 'user:mallory',
    actor_kind: 'user',
    result: 'no allowing voice policy',
    occurred_at: '2026-08-20T09:31:00Z',
  },
  {
    id: 'vd-0003',
    session_ref: 'sess-costly-04',
    agent_ref: 'support-voice',
    requested_model_ref: 'gpt-4o-realtime',
    requested_provider_ref: 'openai',
    policy_ref: 'vp-0001',
    op: 'open',
    policy_verdict: 'allowed',
    plan_hash: 'c9d1e2f3',
    approval_ref: 'appr-119',
    gate_status: 'approved',
    op_status: 'budget_blocked',
    actor: 'user:fran',
    actor_kind: 'user',
    result: 'open denied: budget cap reached',
    occurred_at: '2026-08-20T10:02:00Z',
  },
  {
    id: 'vd-0004',
    session_ref: 'sess-slow-09',
    agent_ref: 'sales-voice',
    requested_model_ref: 'gpt-4o-realtime',
    requested_provider_ref: 'openai',
    policy_ref: 'vp-0002',
    op: 'open',
    policy_verdict: 'allowed',
    gate_status: 'approved',
    op_status: 'budget_throttled',
    actor: 'svc:dialer',
    actor_kind: 'service',
    result: 'throttled: soft budget threshold crossed',
    occurred_at: '2026-08-20T10:20:00Z',
  },
  // Los TRES desenlaces que faltaban. Sin ellos no había testigo para `failed`, y el
  // mutante que lo pinta en VERDE —un fallo leído como éxito— escapaba entero.
  {
    id: 'vd-0005',
    session_ref: 'sess-pending-11',
    agent_ref: 'support-voice',
    requested_model_ref: 'gpt-4o-realtime',
    requested_provider_ref: 'openai',
    policy_ref: 'vp-0001',
    op: 'open_request',
    policy_verdict: 'allowed',
    plan_hash: 'd4e5f6a7',
    approval_ref: 'appr-120',
    gate_status: 'pending',
    op_status: 'requested',
    actor: 'user:fran',
    actor_kind: 'user',
    result: 'approval requested',
    occurred_at: '2026-08-20T10:35:00Z',
  },
  {
    id: 'vd-0006',
    session_ref: 'sess-declared-02',
    agent_ref: 'sales-voice',
    requested_model_ref: 'gpt-4o-realtime',
    requested_provider_ref: 'openai',
    policy_ref: 'vp-0002',
    op: 'close',
    policy_verdict: 'allowed',
    gate_status: 'approved',
    op_status: 'declared_not_opened',
    actor: 'svc:dialer',
    actor_kind: 'service',
    result: 'declared by telemetry, never opened through the gate',
    occurred_at: '2026-08-20T10:41:00Z',
  },
  {
    id: 'vd-0007',
    session_ref: 'sess-broken-03',
    agent_ref: 'support-voice',
    requested_model_ref: 'gpt-4o-realtime',
    requested_provider_ref: 'openai',
    policy_ref: 'vp-0001',
    op: 'open',
    policy_verdict: 'allowed',
    plan_hash: 'e5f6a7b8',
    approval_ref: 'appr-121',
    gate_status: 'approved',
    op_status: 'failed',
    actor: 'user:fran',
    actor_kind: 'user',
    result: 'dispatcher refused the realtime leg',
    occurred_at: '2026-08-20T10:52:00Z',
  },
]
